### ISSUE TITLE
QA Toolkit - QA Concurrence Response Form - Revisions to Form

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#155]
Please implement the following updates to the QA Concurrence Response Form:
1. **Remove the "New Request" text**
2. **Update the "Title" value - remove the text input box control and display as read-only text, pre-populate the value using the title from the original request.**
3. **Enable the QA Response dropdown for the Inspector role. (the dropdown should be enabled for 2 roles - ESC Manager & Inspector)**
 
![image](https://cloud.githubusercontent.com/assets/4098544/6870634/9f5c044a-d473-11e4-9a77-70f8535d176d.png)

**Comment by kanglu666** [comment]
done at KCI

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by slmessier** [comment]
related to #150

**Comment by Tad-Daniel** [comment]
This appears to be complete and implemented in production.  Item complete
