### ISSUE TITLE
QA2 Inspection Form - "No" Radio Button Selections not persisting in UI

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#190]
**The system does not display the "No" radio buttons as selected after the user has selected it. Likewise the selections are not displayed within the output PDF report either.**

Please see the screenshots below - in that example all "No" buttons were selected but the UI does not display their selection.

UI:
![image](https://cloud.githubusercontent.com/assets/4098544/7727693/6ecf3998-fed8-11e4-97c2-dcd579a7f9e8.png)

PDF:
![image](https://cloud.githubusercontent.com/assets/4098544/7727710/9a3d7770-fed8-11e4-8a01-2fa1492978c0.png)

**Comment by kanglu666** [comment]
this is working correct to me

**Comment by slmessier** [comment]
this issue appears to be specific to the browser version - please see below. If possible please investigate a fix for IE:

Firefox - success
Chrome - success
IE9 - failure

**Comment by kanglu666** [comment]
fixed for IE.

**Comment by slmessier** [comment]
validated in KCI DEV - updated to ready for staging.
