### ISSUE TITLE
QA Toolkit - Update Yellow Card & Expiration Date

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#203]
Move Yellow Card and expiration date field from the project record to the user account rercord. 
1.	Relocate ESC Manager, Yellow Card, & Exp Date onto the same horizontal line; relocate superintendent to the line below - high
2.	Secondary task – re-architect data model, user profile UI, & Project details UI to link yellow card/esc manager/superintendent to user account information – low priority

**Comment by kanglu666** [comment]
# 1 updated at KCI.
# 2 need more effort, need db schema update and code update. (will do later)

**Comment by rwingender** [comment]
The scope of this issue has become obsolete after the development of GH issue #’s 260, 261, 262, and 263. This issue will be closed.
