### ISSUE TITLE
Add New QA2 Inspection Workflow - Sort Selectable Project List by Contract # Ascending from A to Z

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#216]
**For the workflow to Add New QA Inspection Report, update the system so that the selectable project 
list is ascending (A to Z) by contract number.**

Steps to navigate to screen that is to be updated:
1. Click on Inspections Tab
2. Click on QA2 Tab as authorized user
3. Click on the Add Inspection Button
4. The Selectable Project List is the grid that should be updated to sort on Contract # from A to Z

![image](https://cloud.githubusercontent.com/assets/4098544/8555398/dd449f20-24bd-11e5-86f9-8305cf45ef2a.png)

**Comment by kanglu666** [comment]
done

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Staging

**Comment by Tad-Daniel** [comment]
Can this be moved to stagging for testing

**Comment by Tad-Daniel** [comment]
Didn't mean to close.

**Comment by slmessier** [comment]
Hi Tad - I believe this functionality has already been implemented in PRODUCTION, and that GitHub was never updated accordingly to reflect as much (my mistake!).

**Could you please confirm and close if applicable?**

**Comment by Tad-Daniel** [comment]
You are correct, item complete
