### ISSUE TITLE
Modification Request Page - Update System to Automatically Save after Authentication / Signature

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#218]
**Please update the Modification Request Page to automatically execute a save after each time any user is authenticated using the login prompt for the _Contractor_, _SHA P.E._, or _Rec/QA_.**

Note: **the system should not navigate away from the Modification Request Page for this case after the successful save.**

![image](https://cloud.githubusercontent.com/assets/4098544/8655019/5bdb7b86-295c-11e5-8b05-896713d96a12.png)

**Comment by magregory** [comment]
This functionality has been added. After successfully authenticating a field the request is saved regardless of hitting save and submit button.  After authenticating, the system does not navigate away from current page.

**Comment by Tad-Daniel** [comment]
Appears to work

**Comment by Tad-Daniel** [comment]
Appears to function correctly, ready for production.

**Comment by Tad-Daniel** [comment]
Item complete
