### ISSUE TITLE
MDE Toolkit - Assign All Projects to User Account

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#22]
the system produces an error message after the user has attempted to assigned all available projects to a user.

Steps to replicate:
1. Admin menu --> user list--> add new user
2. Check the checkboxes for all available projects --> click 'right arrow' icon
3. system will display error (does not error out in original app)
![image](https://cloud.githubusercontent.com/assets/4098544/3330768/8613fb0e-f7d4-11e3-8fb4-41a5c41c39ff.png)

error message:
![image](https://cloud.githubusercontent.com/assets/4098544/3330746/2a5bcbc0-f7d4-11e3-8946-f4cd087a1047.png)

**Comment by kanglu666** [comment]
looks like this is only happening for MDE toolkit. both qa and emt work fine.
they all use same code base. so not sure what's the issue is. the same thing happens in SHA pro.

**Comment by slmessier** [comment]
this issue also occurs after updating any of the attribute information for an existing user.

**Comment by slmessier** [comment]
note the overlap in scope with GH issue #27 . It is expected that one solution will resolve both issues.

**Comment by slmessier** [comment]
this issue was successfully validated in DEVELOPMENT, and will be updated to "Ready for Staging".

**Comment by rwingender** [comment]
Validated in Staging.

**Comment by Tad-Daniel** [comment]
ready for production

**Comment by slmessier** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Issue resolved, item complete.
