### ISSUE TITLE
QA Toolkit - Develop New System Notification - Pending Modification Request Without User Activity for 14+ days

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#225]
Please create a new system notification that is delivered to all users currently assigned to a modification.

The notification is triggered when: Request Status = 'Pending'  **AND** 14+ days since most recent modification update date

Tad will provide a mock-up of the notification including the text of the notification message.

Note: this issue was originally requested as **No. 12 (Green) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository

**Comment by Tad-Daniel** [comment]
See screen shot.  The status request should be placed in the standard email

![2weekstatus](https://cloud.githubusercontent.com/assets/7913678/12922571/00a42140-cf20-11e5-9a11-ac22416187d6.png)

**Comment by slmessier** [comment]
This notification should be triggered when each of the following conditions have been met
1. _**Request Status = Pending**_
AND
2. _**14+ days have elapsed since the modifications' previous response**_
![image](https://cloud.githubusercontent.com/assets/4098544/13231153/7183b884-d976-11e5-8a10-aa4a2eb097a3.png)

**Comment by slmessier** [comment]
this issue has been validated in DEVELOPMENT environment. Issue will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Will be verified in production...

**Comment by Tad-Daniel** [comment]
I am currently watching this process in production.  It appears some notifications happened on Tuesday night and again on Wednesday morning.  Will these notification happen everyday until a comment is added?

If so, I would like the system add a comment into the response record noting that an email reminded has been sent to all stakeholders. This entry would reset the 2 week process. This also provides a solid tracking of all time-frames.

**Comment by vijme** [comment]
Yes, it occurs on everyday basis now.  If a comment as stated above needed to be added as a new response, then we will need a response creator (user) to save that response. Some other options that could be done are :
1. Change the schedule to run on specific day (like 1st or 15th of every month)
2. Run the program everyday but select only requests whose last response was 14, 28, 42.......(multiples of 14)dates from current date.

**Comment by Tad-Daniel** [comment]
After further review and discussing with users, The system should stay as is.  This functionality works as intended to constantly remind everyone of the need to comment.  The only changes I ask for are to the email formating.   See graphic for adjustments.

![capture](https://cloud.githubusercontent.com/assets/7913678/14710330/fdf3b2e2-07a2-11e6-93dc-e37f8446e9e4.PNG)

**Comment by vijme** [comment]
Line spacing and character spacing has been updated in production.

**Comment by Tad-Daniel** [comment]
Working well in production, item complete
