### ISSUE TITLE
QA Toolkit - Develop New System Notification - Project On-Hold for 30+ days

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#226]
Please create a new system notification that is:

1. **triggered / issued on the 1st day of each month**
2. **a distinct email is delivered to each user that has been assigned as QA Inspector to project, _exclusively for projects that have status = "On-Hold" for 30+ days_**
3. **listing all of the projects the QA Inspector has on hold**

**Tad has provided the text details for the notification message below.**

Note: this issue was originally requested as **No. 17 (Blue) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14749664/d5f51e06-088e-11e6-804f-da2568e6ac44.png)

**Comment by Tad-Daniel** [comment]
Weren't we going with setting a day each month (1 day of the month) to send out this notification as it is simply a reminder to the field inspectors and may not invoke a response from them in the system.

I am good with either of these two options:
- 1 email per inspector listing all of the projects they have on hold.
          or
- an email to the inspector for each project they have on hold.

The subject should be "Projects on Hold reminder"

With text to the inspector: "This is a reminder that the following project(s) are on hold in your system and should be checked on to confirm the current status of the project."  this text may vary some depending on the email approach you choose.

**Comment by vijme** [comment]
One email to the inspector for each project on hold is being implemented. Please check the format and let know if any additional modifications needed on this email message.


![image](https://cloud.githubusercontent.com/assets/6668314/14572240/afd4f5a2-031b-11e6-93ab-743b8d8bfa8c.png)

**Comment by Tad-Daniel** [comment]
Looks good.  Just add the project number prior to the project description   What will the email subject line be?

**Comment by vijme** [comment]
The subject is "Project On Hold Reminder". Contract Number has been added before description. Please check


![capture1](https://cloud.githubusercontent.com/assets/6668314/14678017/139ff306-06e2-11e6-9484-25fe4054c197.PNG)

**Comment by vijme** [comment]
Development done. Can be moved to production after confirmation. Trigger will be 1st of every month.

**Comment by Tad-Daniel** [comment]
Push to production.  We will verify first of the month.

**Comment by Tad-Daniel** [comment]
I am soliciting feedback from the team but it appears the notifications did no go out as expected. Some inspectors got a few and others got none.  I got 1.  What are the logic/rules for the notification.

**Comment by vijme** [comment]
Any user who has been assigned as QA Inspector to a project (either through user page, or through stakeholder subtab of project page), will be notified if the corresponding project was on hold for 30+ days. Based on the above logic, i have attached a text file that lists the 79 users who would have been notified today. The same list appears twice in the text file one sorted by name and other by project.


[OnHoldList.txt](https://github.com/kcigeospatial/sha_oed_issues/files/296213/OnHoldList.txt)

**Comment by vijme** [comment]
Same file in excel

[OnHoldProjs1.xlsx](https://github.com/kcigeospatial/sha_oed_issues/files/296510/OnHoldProjs1.xlsx)

**Comment by Tad-Daniel** [comment]
I am working with the QA team to verify some info but I am now starting to believe the system is working correctly.  It appears that the system only sends an email to the individual that actually placed the project on HOLD.  Does that sound correct?

**Comment by Tad-Daniel** [comment]
System appears to be working correctly.  Item complete.
