### ISSUE TITLE
QA Toolkit - Inspection Form - Automatically Populate General Notes with Standard Text

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#227]
On the Inspection form, **please add new functionality that allows the user to automatically populate the _General Notes_ text value with a standard text value that is stored within the system and retrieved in support this new functionality.**

1. **add a button to the User Interface (shown below) that allows the user to trigger the system to automatically retrieve populate the text.**
2. **Standard Text values exist exclusively for Grades C, D, & E. The new functionality must include system logic to automatically determine the appropriate text to values based on the inspection grade** at the time the user executes the function.

**Tad has provided the standard text for each grade (C, D, & E) and the graphic to use for the button below.**

![image](https://cloud.githubusercontent.com/assets/4098544/12902504/a53ad6fe-ce8f-11e5-8ee3-6baead7960b5.png)

**Comment by Tad-Daniel** [comment]
The notes are as follows for each instance

C grade:

 A “C” rating has been accessed as a result of the inspection on this date. The project is in compliance; however, deficiencies noted require corrections. Shutdown conditions described elsewhere herein could arise quickly. Correct all deficiencies within 72 hours. The project will be re-inspected at the end of this period. If the deficiencies have not been satisfactorily corrected, the project will be rated a “D” and all earthwork operations will be shut down until the project is rated a “B” or better. See the 2008 SHA Standard Specifications Book 308.01.03 for the “D” rating.

D grade:

This project is in non-compliance. (fill in blank from project information)

A “D” rating has been accessed as a result of the inspection on this date. All of the deficiencies are noted on this QA Report issued this date. 

The Administration will shut down all earth work operations. All work efforts shall focus on correcting erosion and sediment control deficiencies. The project will be re-inspected within 72 hrs. All required corrective actions shall be completed within the 72 hour period for the project to be upgraded to a “B” rating. Failure to upgrade the project from a “D” rating to a “B” or better will result in the project being rated an “F”. Liquidated damages in the amount of $ ____ will be imposed for each day the project has a “D” rating. Refer to Shutdowns elsewhere in this Specification for additional requirements. 

First occurrence of an F grade on a project:  

This project is in non-compliance. (fill in blank from project information)

An “F” rating has been accessed as a result of the inspection on this date. The Administration will shut down the entire project until the project receives a “B” or better rating. All work efforts shall focus on correcting erosion and sediment control deficiencies. Liquidated damages in the amount of $ ____ will be imposed for each day the project has an “F” rating. 

It is the responsibility of the Contractors ESCM and SHA- Project Engineer to verify that all deficiencies have been corrected in a timely manner and that all E&S controls, Permit requirements and SHA Specifications have been met. When the outstanding issues have been corrected, the SHA-QA Representative (QA Inspector) shall be contacted for the follow-up inspection.

Per Specification 308.01.03 Should this project receive a second ‘F’ rating, the Erosion and Sediment Control Training Certificate “Yellow Card” issued by the Administration will be immediately revoked from the project Superintendent and the Erosion and Sediment Control Manager for at least a six month period and until successful completion of the Administration’s Erosion and Sediment Control Certification Program.  Neither the project Superintendent nor the Erosion and Sediment Control Manager will be allowed to oversee the installation and maintenance of erosion and sediment controls during the period the certification is revoked on any project of the Administration.  Replacement of the project Superintendent and the Erosion and Sediment Control Manager with certified personnel will be required as well. Work may not commence until the certified personnel are in place.

Second occurrence of an F grade on a project:  (fill in blank from project information)

This project is in non-compliance. 

An “F” rating has been accessed as a result of the inspection on this date. The Administration will shut down the entire project until the project receives a “B” or better rating. All work efforts shall focus on correcting erosion and sediment control deficiencies. Liquidated damages in the amount of $ ____ will be imposed for each day the project has an “F” rating. 

It is the responsibility of the Contractors ESCM and SHA- Project Engineer to verify that all deficiencies have been corrected in a timely manner and that all E&S controls, Permit requirements and SHA Specifications have been met. When the outstanding issues have been corrected, the SHA-QA Representative (QA Inspector) shall be contacted for the follow-up inspection.

This is the second time that this project has been rated 'F', per Specification 308.01.03 the Erosion and Sediment Control Training Certificate “Yellow Card” issued by the Administration is revoked from the project Superintendent and the Erosion and Sediment Control Manager for at least a six month period and until successful completion of the Administration’s Erosion and Sediment Control Certification Program.  Neither the project Superintendent nor the Erosion and Sediment Control Manager will be allowed to oversee the installation and maintenance of erosion and sediment controls during the period the certification is revoked on any project of the Administration. Replace the project Superintendent and the Erosion and Sediment Control Manager with certified personnel. Work may not commence until the certified personnel are in place with the exception of correcting the outstanding defensives.

The button:

![biggrpaste](https://cloud.githubusercontent.com/assets/7913678/12922098/1e6f5354-cf1e-11e5-8846-ecff1feca774.png)

**Comment by slmessier** [comment]
![image](https://cloud.githubusercontent.com/assets/4098544/14061730/d13f5f0c-f35d-11e5-9d05-9baac7a674bf.png)

**Comment by slmessier** [comment]
![image](https://cloud.githubusercontent.com/assets/4098544/14212171/91dbc57a-f7ff-11e5-83ab-a91e9cec6ff1.png)

**Comment by rwingender** [comment]
Tested and validated in DEV.  Button generates the correct prompt according to the grade/number of F grades.  It also generates the correct amount for the liquidated damages.

**Comment by slmessier** [comment]
I was unable to successfully populate the text for F grade (neither the first nor second iteration). **The system loads a comment but is loading the text for a _"Grade D"_ comment when it is expected to load the _"F Grade"_ .** please note the picture below (fyi - the system does accurately produce the associated text for Grades C and D)
![image](https://cloud.githubusercontent.com/assets/4098544/14482015/1cb25880-0106-11e6-9f13-b129597d6016.png)

**Comment by vijme** [comment]
For some reason, the dev server was not updated to the latest after correcting for the liquidated damages.. Ready for testing

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Appears to be working correctly.  Ready for production

**Comment by slmessier** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Appears to function correctly in production.  Item complete
