### ISSUE TITLE
QA Toolkit - New Email Notification - Notify QA Division Representatives upon Assignment to Modification

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#232]
Please create a new automatically-triggered system email notification using the specifications below:

**Recipients** of the notification may be retrieved by referencing the UI functionality shown below from  the ADMIN-->UserEdit page (QA Group Membership): 
![image](https://cloud.githubusercontent.com/assets/4098544/13085318/a3fb03f0-d4ab-11e5-88f9-6494a6787478.png)

**The trigger of the notification** is when an authorized user (package approver) uses the Modification Response Page to update/select the QA Group checkboxes (see below) and then clicks save. (triggered on the save)
![image](https://cloud.githubusercontent.com/assets/4098544/13085725/ab3a6e92-d4ad-11e5-866d-a03f7475aebf.png)

**Tad will provide the text for the notification, or a mockup if more complex formatting is desired.**

Note: this issue was originally requested as **No. 13 (Green) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/13085906/82229b1e-d4ae-11e5-9a68-896e128e2ad8.png)

**Comment by slmessier** [comment]
From: Scott Messier 
Sent: Tuesday, February 16, 2016 1:13 PM
To: Tad Daniel (tdaniel@sha.state.md.us)
Subject: QA Toolkit - Text Needed for New Notification

Hi Tad,

At your earliest convenience, could you please update GitHub issue 232 to include the text you desire for the notification associated with the QA Group Membership notification?
https://github.com/BC89/sha_oed_issues/issues/232

A mockup may be preferred if you would like formatting, spacing, etc

Please let me know if you have any questions – thank you!

Scott Messier

**Comment by Tad-Daniel** [comment]
No need for any new email.  The current email format is to be used as designed in the modification response system.  The plan for this is to have the system automatically include (check off) the individuals per the approval permission set in the user account.  

Example when I select Highway Hydraulics as a needed approver when submitting the package through the response page the system would automatically select/include all of the users who have approval permission for HHD and include them in the email chain.

**Comment by magregory** [comment]
Updated in KCI Dev. Ready for staging.

**Comment by slmessier** [comment]
this issue has been validated in DEVELOPMENT environment. Issue will be updated to "Ready for Staging".

**Comment by slmessier** [comment]
Hi Viji - I was unable to successfully trigger the notification using my test workflow.

Please reference the document below which details my testing workflow procedure. 

Please let me know if you would like to hold a brief call to review any of the specifics - thank you!

[GH_Issue232Testing.docx](https://github.com/BC89/sha_oed_issues/files/155635/GH_Issue232Testing.docx)

**Comment by Tad-Daniel** [comment]
Could we pause this item.   I have received some feedback from a few users and wish to consider all the implications of this type of system

**Comment by Tad-Daniel** [comment]
Continue to hold this issue

**Comment by slmessier** [comment]
@Tad-Daniel - Is this issue from February 2016 still valid or has it become obsolete and could be closed at this time? Please research and advise when you have an opportunity. Otherwise not time-sensitive. Thank you!

**Comment by Tad-Daniel** [comment]
No longer a concern,  Time and budget is not going to allow for thie enhancement and I was never sure exactly how it would work.  Issue Closed.
