### ISSUE TITLE
QA Toolkit - Inspections Tab-->Reports Subtab - Add New Searchable Filter: Non-Compliance Checkbox

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#235]
Please add new user interface controls and functionality to provide a new searchable filter parameter for QA1 Inspections: **_Non-Compliance Checkbox_**

**Existing QA1 Inspection Searchable Filters:**
![image](https://cloud.githubusercontent.com/assets/4098544/13299565/adf08c9a-db09-11e5-8600-4ca23826b710.png)

**Mockup of Updated QA1 Inspection Searchable Filters:**
![image](https://cloud.githubusercontent.com/assets/4098544/13323886/7f0a5550-dba9-11e5-8f89-816701bd749b.png)

**Note: the source of the non-compliance information in the database is the database location in which the system User Interface saves the following information:**
![image](https://cloud.githubusercontent.com/assets/4098544/13299618/e66f9502-db09-11e5-92be-5082dbaafb16.png)

Note: this issue was originally requested as **No. 4 (Purple) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository

**Comment by vijme** [comment]
Implemented in development

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
This does not appear to be finding all of the "non-compliance reports"

**Comment by Tad-Daniel** [comment]
This appears to have been included in the RC 2016_03.
It also appears to be functioning properly.
If someone else can verify this, it can be closed.

**Comment by slmessier** [comment]
I was able to validate the search filtering functionality for existing projects in the PRODUCTION environment after implementation of RC 2016_03
