### ISSUE TITLE
QA Toolkit - Inspections Tab-->Reports Subtab - Add New Searchable Filter: Project Description Wildcard Text Search

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#236]
Please add new user interface controls and functionality to provide a new searchable filter parameter for QA1 Inspections: **_Project Description_**

**Existing QA1 Inspection Searchable Filters:**
![image](https://cloud.githubusercontent.com/assets/4098544/13299565/adf08c9a-db09-11e5-8600-4ca23826b710.png)

**Mockup of Updated QA1 Inspection Searchable Filters:**
![image](https://cloud.githubusercontent.com/assets/4098544/13323803/162e2d4a-dba9-11e5-9947-c721a1580dcd.png)

**Note: the Project Description wildcard search should re-use the search functionality that exists currently within the Project Search Filters (see below)**
![image](https://cloud.githubusercontent.com/assets/4098544/13323959/beab423c-dba9-11e5-9104-019f27670bd5.png)

Note: this issue was originally requested as **No. 5 (Purple) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository

**Comment by vijme** [comment]
Implemented in development

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good fro production

**Comment by slmessier** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Appears to work in production.  Item complete.
