### ISSUE TITLE
QA Toolkit - Replace / Update Searchable Filter Functionality for District

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#237]
Please replace / update the existing functionality for the searchable filter parameter - **_District_** - for all existing instances within the UX. 

**The updated functionality should filter the associated grid according to the district values the user has selected within the associated checkboxes.**

**Existing District Searchable Filter (Inspections shown as an example):**
![image](https://cloud.githubusercontent.com/assets/4098544/13299565/adf08c9a-db09-11e5-8600-4ca23826b710.png)

**Mockup of District Searchable Filter (Inspections shown as an example):**
![image](https://cloud.githubusercontent.com/assets/4098544/13325981/17b3a3f8-dbb2-11e5-8f5e-1c1e62b06807.png)

**The District Searchable Filter should be updated for each of the following UX instances:**
**1. Inspections --> Reports
2. Inspections --> QA2
3. Inspections --> Project List
4. Inspections --> Project Merge --> Select Project
5. BP/SS --> Non-Compliance
6. BP/SS --> Reports --> QA Projects By District
7. BP/SS --> Reports --> ESC QA Summary for Business Plan Reporting**

Note: this issue was originally requested as **No. 2 (Purple) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository

**Comment by slmessier** [comment]
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Monday, March 14, 2016 2:50 PM
To: Scott Messier
Cc: Heidi Hammel
Subject: RE: District Checkbox Search Filter

Lets put a hold on this until I can get a better grasp of the MDE toolkit.    

Thanks
--------
From: Scott Messier [mailto:Scott.Messier@kci.com] 
Sent: Monday, March 14, 2016 2:40 PM
To: Tad Daniel
Cc: Heidi Hammel
Subject: District Checkbox Search Filter

Hi Tad, 
Viji has indicated that the changes associated with GH issue #37 would be global and affect all toolkits. 
I wanted to inform you of this constraint and seek your determination of whether to move forward.  
Please reference the issue as needed and let me know how you would like to proceed - thank you!

**Comment by Tad-Daniel** [comment]
Continue to hold on this issue

**Comment by slmessier** [comment]
@Tad-Daniel - Is this issue from February 2016 still valid or has it become obsolete and could be closed at this time? Please research and advise when you have an opportunity. Otherwise not time-sensitive. Thank you!

**Comment by Tad-Daniel** [comment]
No longer valid.  Enhancement will not need development
