### ISSUE TITLE
Project Details PDF Report - Update to Wrap Text Values - Page 2

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#238]
**Please update the Project Details PDF Report to display the report text values as wrapped text so that the full values are displayed within the associated report field.** Please update the _Modifications)_ & _QA Concurrence_ sections on page 2 of the report - see the graphics below.

![image](https://cloud.githubusercontent.com/assets/4098544/13960781/1aded808-f030-11e5-9538-f4361c3d2cde.png)

![image](https://cloud.githubusercontent.com/assets/4098544/13960748/f7d7fb32-f02f-11e5-8dc9-eed9fb95bc0b.png)

**Comment by vijme** [comment]
Fixed in development

**Comment by slmessier** [comment]
validated successfully and flagged as _Ready for Staging_

**Comment by Tad-Daniel** [comment]
Looks good, ready for production.

**Comment by slmessier** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Looks good in production. Item complete.
