### ISSUE TITLE
QA Toolkit - Develop New PDF Report Functionality - QA2 Listing

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#239]
**Please produce  a new system report for _QA2 Listing_ using the specifications outlined below:**

**1. Inspections-QA2 UX Screen
2. Launch: from a new Print button (re-use existing print button graphics)
3. Output: A PDF report list of the grid associated with the Inspections-QA2 UX Screen**

![image](https://cloud.githubusercontent.com/assets/4098544/14060531/d2210e22-f33d-11e5-9b7f-a7b71027412c.png)

Note: this issue was originally requested as **No. 1C (Yellow) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14060539/153ef52a-f33e-11e5-8979-3921f039e139.png)

**Comment by magregory** [comment]
QA2 search page print function has been tested and verified in DEV.

**Comment by vijme** [comment]
Implemented in development

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good for production.

**Comment by slmessier** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Appears to work in production.  Item complete.
