### ISSUE TITLE
QA Toolkit - Develop New PDF Report Functionality - Permit Listing

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#240]
**Please produce  a new system report for _Permit Listing_ using the specifications outlined below:**

**1. Permits - Permits UX Screen
2. Launch: from a new Print button (re-use existing print button graphics)
3. Output: A PDF report list of the grid associated with the Permits UX Screen. The output should consider any active filters that the user has configured within the _Search Panel_.**

![image](https://cloud.githubusercontent.com/assets/4098544/14060591/04dfb0a0-f340-11e5-8a84-f0c2079e71ff.png)

Note: this issue was originally requested as **No. 1D (Yellow) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14060539/153ef52a-f33e-11e5-8979-3921f039e139.png)

**Comment by magregory** [comment]
Print function appears to work in DEV.  However the search functions seem to be off.  Example: Searching by all Permits Issued February 10th brings up other issue dates besides just February 10th.

**Comment by vijme** [comment]
Implemented in development

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good for production

**Comment by slmessier** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Appears to work in production.  Item complete.
