### ISSUE TITLE
QA Toolkit - Develop New PDF Report Functionality - Projects On-Hold Listing

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#241]
**Please produce  a new system report for _Projects On-Hold Listing_ using the specifications outlined below:**

**1. Inspections - Schedule UX Screen
2. Launch: update the system response to existing Print button to display a pop up message that allows the user to select between 2 reports: _Inspection Schedule_ (which exists currently) and _Project On Hold_** ![image](https://cloud.githubusercontent.com/assets/4098544/14060762/9298aa7e-f344-11e5-9fb0-89f4519d1137.png)
**3. Output: A PDF report list of the grid associated with the portion of the _Inspection - Schedule_ UX_ shown below, reusing the attribute columns from the UX** 
![image](https://cloud.githubusercontent.com/assets/4098544/14060778/2e25bb76-f345-11e5-99b9-f807f4aa40c5.png)

Note: this issue was originally requested as **No. 1G (Yellow) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14060539/153ef52a-f33e-11e5-8979-3921f039e139.png)

**Comment by vijme** [comment]
Implemented in development

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good with one exception:  Hide or remove the justification reason number from the PDF.  It is not necessary on the PDF.  This can still move to production with the fix implemented later.

![hold list](https://cloud.githubusercontent.com/assets/7913678/14529755/0c4618c8-0224-11e6-853a-6472c32626a8.png)

**Comment by slmessier** [comment]
Justification reason number has been removed from the PDF form. Since this was otherwise validated, it will be updated as "Ready for Production".

**Comment by Tad-Daniel** [comment]
Looks good in production. Item complete.
