### ISSUE TITLE
QA Toolkit - Develop New PDF Report Functionality - ESC QA Business Plan Summary

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#242]
**Please produce  a new system report for _ESC QA Business Plan Summary_ using the specifications outlined below:**

**1. BP/SS - Reports UX Screen - ESC QA Business Plan Reporting Section
2. Launch: update the existing _Report_ button functionality to produce the PDF report
3. Output: A PDF report listing the output of each of the data grids that are currently produced by completing the search function (see below).**

![image](https://cloud.githubusercontent.com/assets/4098544/14060931/4f60142c-f349-11e5-993e-cc1717777820.png)

![image](https://cloud.githubusercontent.com/assets/4098544/14060926/12d39c72-f349-11e5-830c-f0f85eb5762d.png)

Note: this issue was originally requested as **No. 1E (Yellow) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14060539/153ef52a-f33e-11e5-8979-3921f039e139.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good, ready for production

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Production".

**Comment by Tad-Daniel** [comment]
Appears to work in production.  Item complete.

Work continues on #243 related to this item.
