### ISSUE TITLE
QA Toolkit - Develop New PDF Report Functionality - BP/SS Reports - Incorporate Charts / Graphs

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#243]
**Please develop Bar Chart functionality according to the specifications outlined below:**

**1. BP/SS - Reports UX Screen - Update output of each of the (3) Existing Reports 
2. Add an _"Average Score" Column_ to the existing report output, with the associated value.
3. Charting Specifications:**

- **chart displays each grade on horizontal axis, count/frequency of score on vertical axis**
- **for each grade (horizontal), include 3 bars for each of the Monthly, Quarterly, & Yearly counts**
![image](https://cloud.githubusercontent.com/assets/4098544/14061157/a7a1f3de-f34f-11e5-916f-2c1e5e454c75.png)
- **with the PDF report output, insert the bar chart at the top of each _District_ section of the report, considering and user-defined filtering parameters set in the UX.**
![image](https://cloud.githubusercontent.com/assets/4098544/14061048/79b00c16-f34c-11e5-9a8f-b7623738ad64.png)

Note: this issue was originally requested as **No. 1F (Yellow) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14060539/153ef52a-f33e-11e5-8979-3921f039e139.png)

**Comment by vijme** [comment]
Need clarifications on the following:
1.  BP/SS - Reports UX Screen - Update output of each of the (3) Existing Reports : What will be the update with ESC QA Summary Report. Not sure what graph needs to be added in that report.
2. Add an "Average Score" Column to the existing report output, with the associated value: Average Score is already available in Inspector Report, and so does that field needs to be added only in District Report?
3. for each grade (horizontal), include 3 bars for each of the Monthly, Quarterly, & Yearly counts: The user has the option to choose the from date and to date from UX. How can this be split monthly, quarterly or yearly when there could be different "A" Grades count for different months in the whole specified time period.

**Comment by Tad-Daniel** [comment]
1. BP/SS - Reports UX Screen - Update output of each of the (3) Existing Reports : What will be the update with ESC QA Summary Report. Not sure what graph needs to be added in that report.
The update for the should be:

**1. remove the text "5.4 PM#" from each of the data table tieles"**
**2. Add a graphic (bar chart) beside each table reflecting the following information**
     _- projects visited: 2 separate charts, one showing Q1,Q2,Q3,Q4 and another showing current FY total and 3 prior FY totals.
     - Projects with Minimum.......:  chart values from total lines (Q1,Q2,Q3,Q4,FY) Notethat this table appears to be showing percentages and not whole values.
     - Number of active const.......:  chart values from total lines (Q1,Q2,Q3,Q4,FY)
     - Number of Quality Assurance......:   2 separate charts, one showing Q1,Q2,Q3,Q4 and another showing current FY total and 3 prior FY totals.
     - Percentage of projects with scheduled inspections...... :  chart values from total lines (Q1,Q2,Q3,Q4,FY)
     - Percentage of projects with Non-compliance......: 2 separate charts, one showing Q1,Q2,Q3,Q4 and another showing current FY total and 3 prior FY totals.
     - Number of Non-compliance.....:  2 separate charts, one showing Q1,Q2,Q3,Q4 and another showing current FY total and 3 prior FY totals.
     - Number of project with non-compliance.......: 2 separate charts, one showing Q1,Q2,Q3,Q4 and another showing current FY total and 3 prior FY totals._
**3. Wrap the title text in the table to allow for the width to be reduced thus making room on the page for the charts.**
**4. Remove "Number of SHA employees......" table from the PDF.**
**5. Move "Percentage of projects with scheduled inspections......" and "Projects with Minimum......" tables and graphics to the bottom of the PDF and format the document to ensure they appear on a separate page.**

2. Add an "Average Score" Column to the existing report output, with the associated value: Average Score is already available in Inspector Report, and so does that field needs to be added only in District Report?
**Yes, this is only needed in the District report.**

3. for each grade (horizontal), include 3 bars for each of the Monthly, Quarterly, & Yearly counts: The user has the option to choose the from date and to date from UX. How can this be split monthly, quarterly or yearly when there could be different "A" Grades count for different months in the whole specified time period.
**The graph should reflect the time-frame defined in the UX**

**Comment by vijme** [comment]
Implemented in dev. Please check

**Comment by Tad-Daniel** [comment]
See markup, it looks like a lot but it is fairly repetitive.

[QA_BPRSummary markup.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/241127/QA_BPRSummary.markup.pdf)

**Comment by vijme** [comment]
Changed according to markup. "Space above bar" was not implemented as crystal report automatically calculates the range and divisions with the min and max value in each chart. Sometimes,when a max value happens to be on these divisions, they appear on the line.

**Comment by Tad-Daniel** [comment]
Looks really good,  That one set of charts on percentage of compliance looks odd.  Can those two charts be set to only show 95% and above so some variance can be seen.

**Comment by vijme** [comment]
Range changed for the two charts specified. Please check

**Comment by Tad-Daniel** [comment]
Looks great, thanks

**Comment by slmessier** [comment]
Validated in DEVELOPMENT environment and will be marked as "Ready for Staging"

**Comment by Tad-Daniel** [comment]
Looks good, push to production

**Comment by Tad-Daniel** [comment]
Working,  items closed
