### ISSUE TITLE
QA Toolkit - Create New PDF Report Functionality - Inspection Grade Log XLS & PDF

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#244]
**Please develop a new system report for _Inspection Grade Log_ according to the specifications outlined below:**

**1. Inspection - Reports UX Screen - Print Inspection List Pop up - Create 2 new Records: Inspection Grade Log XLS & PDF**
**2. Launch as 2 new hyperlinks on the _Print Inspection List Pop up_ window (see graphic)**
**3.Reuse the functionality of the existing _Inspection Log Reports_**
![image](https://cloud.githubusercontent.com/assets/4098544/14061313/ba2b224c-f353-11e5-98d2-ab0bbf372384.png)
**4. Develop & implement the following additional capabilities/modifications noted in the graphic below for the new report:**
- **Exclude all _Justification_ values from the report output (displayed in red)**
- **Update the syntax of the character string values returned as _Grades_ in the report (displayed in orange)**
- **Remove the footer region (displayed in green)**

![image](https://cloud.githubusercontent.com/assets/4098544/14061382/589c59ae-f355-11e5-97c5-a1d037121ba5.png)

Note: this issue was originally requested as **No. 1B (Yellow) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14060539/153ef52a-f33e-11e5-8979-3921f039e139.png)

**Comment by rwingender** [comment]
Tested and validated in DEV.  Viji suggested moving grades to the side so that it wouldn't look awkward when there is "No Grade". 

![capture](https://cloud.githubusercontent.com/assets/14997365/14184027/1c6880a8-f741-11e5-9958-3323cafabde9.JPG)

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good, ready for production

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good in production.  Item complete.
