### ISSUE TITLE
QA Toolkit - Create New PDF Report Functionality - Project List By Company

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#245]
**Please develop a new system report for _Project List By Company_ according to the specifications outlined below:**

**1. Projects - Projects List UX Screen - Print Button**
**2. Update existing button to launch a new  _Print ProjectList Pop up_ window (see graphic)**
![image](https://cloud.githubusercontent.com/assets/4098544/14061502/dd9c0120-f357-11e5-8714-4fb6c7b7b8db.png)
**3.Reuse the functionality of the existing _Project List Report_**
**4. Develop & implement the following additional capabilities/modifications noted in the graphic below for the new report :**
- **Update the title**
- **Exclude the _FMIS_ column and associated values from the report entirely**
- **Exclude the _E/S Permit_ column and associated values from the report entirely**
- **Add data fields and labels for the following (2) Project attributes: _Project Engineer_, _Contractor Firm Name_**
- **Group returned records by the Contractor Firm Name, and then sort ascending by District**
![image](https://cloud.githubusercontent.com/assets/4098544/14061560/431414ce-f359-11e5-8f61-bfdf2b2cf722.png)

Note: this issue was originally requested as **No. 1H (Yellow) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14060539/153ef52a-f33e-11e5-8979-3921f039e139.png)

**Comment by vijme** [comment]
Implemented in DEV. Please test

**Comment by slmessier** [comment]
Hi Viji - the report looks good aside from one additional specification that does not exist within the report output. **Please update the values to be sorted by Contractor Name (Descending A to Z), and then by District (ascending 1-7). Sort all null values last if possible**

![image](https://cloud.githubusercontent.com/assets/4098544/14477875/d44bfd98-00de-11e6-82cb-c8c8423de810.png)

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good, ready for production

**Comment by slmessier** [comment]
This has been validated in DEVELOPMENT and will be updated to "Ready for Production".

**Comment by Tad-Daniel** [comment]
Appears to work in production.  Item complete.

**Comment by Tad-Daniel** [comment]
Item Complete
