### ISSUE TITLE
QA Toolkit - Approve QA Concurrence Workflow - Unrecoverable Error

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#246]
Users have reported encountering the following system-issued "unrecoverable error" message when executing the Approve QA Concurrence workflow:

**_Project # AX3765L60_ represents a project for which this issue is occurring**

Scott: **I was able to replicate the error in the PRODUCTION environment exclusively**; the workflow appears to be executable as intended within STAGING and DEVELOPMENT environments. 

To Replicate (please also see animated GIF below):
1. **From the QA Concurrence Subtab, Click _New Request_** to initiate a new QA Concurrence Request
2. The system displays the QA Concurrence Request form.
3. **Click the Cancel button or add a comment and click Save**.
4. **The system displays the error message**.
5. Users are also reporting that **the issue occurs for the QA Concurrence Response Page as well. Please apply any future fixes to all instances.**
![application_error](https://cloud.githubusercontent.com/assets/4098544/14215017/575f5e52-f80e-11e5-9632-f16695bcf335.gif)

--------------------------------------
![image](https://cloud.githubusercontent.com/assets/4098544/14184056/47563030-f741-11e5-9fd8-007006b9ec54.png)

**Comment by slmessier** [comment]
# Root Cause
After investigating this issue, the root cause of this issue is described below:

1. On the **“(New) QA Concurrence Request”** and **“QA Response”** pages, **the datagrid listing users to notify is causing rendering issues for the particular case when the datagrid has to display more than 250 records.** ![image](https://cloud.githubusercontent.com/assets/4098544/14325212/4a338dfc-fbf6-11e5-8a58-eaa8734e9aff.png)
2. This condition is **triggered when a particular project has been associated to 250+ users,** and then the system attempts to display the user records within the described datagrid.
3. The STAGING and DEVELOPMENT environments do not meet this condition, while PRODUCTION environment does. Therefore **the issue is currently triggered only in PRODUCTION (has around 400 users).**
4. **Users should avoid assigning all the projects to a particular user while this issue remains in development.**
5. **This root cause is likely also impacting GH issues #22, and #27. They should be re-tested as well after a solution has been developed and is available for testing.**

.

**Comment by slmessier** [comment]
# Potential Solution Identified

The following solution has been identified and is to be developed and tested:

1. **Update the applicable data grids to allow for paging functions which will allow the system to display a list of 250+ users in pages of 250 at a time.** 
2. Because this issue impacts all toolkits (QA, MDE, & EM) in the PROUCTION environment, **please proceed towards resolution for this issue with highest priority over all currently open development requests.**
3. Paging is a UI development technique for displaying large amounts of data by splitting across different page numbers. An existing example of paging functionality can be referenced on the _Project Details_ page (see below), and several other instances within the toolkits.
![image](https://cloud.githubusercontent.com/assets/4098544/14325531/bf73211c-fbf7-11e5-9fe7-139ab6b03946.png)

**Comment by vijme** [comment]
Implemented in dev. Ready for testing

**Comment by slmessier** [comment]
**There is an issue that is occurring in how the UX handles text within the _Request Text_ field when using the distinct user workflow described below**

1. Use the _New Request_ button on the _Project Details - QA Concurrence_ subtab to **initiate the New QA Concurrence Request Workflow**
2. **Add text to the _Request Text_ user input text field** (see “A” in graphic below)
3. Scroll the _Notify Data Grid_ and **click on any of the paging functions** (see “B” in the graphic below). ![image](https://cloud.githubusercontent.com/assets/4098544/14429726/9a797d88-ffcc-11e5-881f-70bad9ee4373.png)
4. **The system does not wrap the text string within the _Request Text_ properly** resulting in the following issue within the UX. **Please also update the associated functionality for the _QA Concurrence Response Page._** ![image](https://cloud.githubusercontent.com/assets/4098544/14429760/c6a3a14a-ffcc-11e5-82b0-56ade9819bb0.png)

**Comment by slmessier** [comment]
Please also assess the design considerations identified below for feasibility from a development standpoint. **If the described specifications are generally achievable, please begin developing at the earliest convenience**, as they represent improvements to the efficiency of the corresponding user workflow:
![image](https://cloud.githubusercontent.com/assets/4098544/14430432/9d820a74-ffcf-11e5-90e9-7a51676be989.png)

**Comment by vijme** [comment]
Buttons moved outside the grid. And pagesize is set to 100. If we set 250 as we discussed, we might not be able to test the paging fuctionality in dev. I will make sure to update it to 250 during staging/production release. And for  the UX issue for misalignment with more text and paging, I am not able to reproduce. DO you still see this as an issue.

**Comment by vijme** [comment]
Also, just found that, the request text and response text for QA Concurrance limit is 255 in database, but 500 in frontend. Should we change either one of them?

**Comment by slmessier** [comment]
I am still encountering the issue with a large number of text characters within the _Request Test_ input field. Note that I am using the clipboard copy/paste function to paste in the text characters.

Please see the graphic below:
![wrap_text](https://cloud.githubusercontent.com/assets/4098544/14437127/c8642876-ffed-11e5-9a7f-6c42cf6247d1.gif)

**Comment by vijme** [comment]
I tried in IE and Chrome and don't see this issue. Can you try clearing your browser cache. Please let me know which browser you are using.

**Comment by rwingender** [comment]
I tested this in Edge and IE and Chrome.  No issue.  Here is my workflow: 
![test_246](https://cloud.githubusercontent.com/assets/14997365/14439341/c83b1d68-fff8-11e5-97be-ca4010d16c8e.gif)

**Comment by slmessier** [comment]
Hi Viji - the issue that was previously reportedis only occurring in IE 9. I've tested according to the browsers with the following outcomes:

1. **IE 11 - Issue not Encountered:** ![image](https://cloud.githubusercontent.com/assets/4098544/14470297/ac632824-00b6-11e6-9ac2-80c305b65eb6.png)
2. **IE 9 - Issue Replicated:** ![image](https://cloud.githubusercontent.com/assets/4098544/14470308/b8686b0c-00b6-11e6-9c24-127015920225.png)

3. **Chrome - Issue not Encountered:** 
![image](https://cloud.githubusercontent.com/assets/4098544/14470359/0d638b6e-00b7-11e6-9df1-e8d3c8b4b688.png)

**Comment by slmessier** [comment]
**The browser-specific issue noted above has been determined to be generally limited to IE 9. Since the issue has not been replicated on IE11 (SHA standard), it can be considered exclusive to a deprecated browser.** (please note the email below in re: compatibility settings tested)

**This Github entry has been otherwise validated and will be updated to "Ready for Staging"**

------

From: Scott Messier 
Sent: Tuesday, April 12, 2016 6:06 PM
To: 'Viji Selvamani'
Cc: Rachel Wingender
Subject: RE: Regarding # 246

Hi Viji –  _I still encountered the same result despite trying a few methods of setting compatibility view. However, I agree that can move forward and update the status of the GitHub issue. I will update GitHub now._

Thank you!

From: Viji Selvamani [mailto:viji.selvamani@ecointegration.com] 
Sent: Tuesday, April 12, 2016 5:11 PM
To: Scott Messier
Cc: Rachel Wingender
Subject: RE: Regarding # 246

Scott,

..._The issue you are having in IE9 is not a newly occurring one.....Since users have not complained of this behavior before, we could assume that this does not affect any user._ 

Having said that I would like to try one more option (apologize for the trouble)

_Could you try to enable compatibility mode in your browser and test this again? Please follow Point No.2 under Method 2 in this article to set the compatibility view. _
https://support.microsoft.com/en-us/kb/2536204#/en-us/kb/2536204

Let me know your thoughts and how it goes. 
Thanks,
Viji

**Comment by Tad-Daniel** [comment]
Ready for production

**Comment by slmessier** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Appears to work in production.  Item complete.
