### ISSUE TITLE
MDE Toolkit - Admin & "Reviewer" Capabilities Produce Unrecoverable Error

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#247]
Users have reported an issue being encountered in the PRODUCTION environment: An "Unrecoverable Error" message is being issued by the system when **_both_** of these (2) conditions have been met:

1. **The user's profile = “Reviewer” system role** 
     AND
2. **The user has ADMIN capabilities**

*The system produces the error message when when these (2) pre-conditions have been met, and then the associated user attempts to log into the toolkit.""

In testing, I was able bypass the issue and log in successfully after removing the ADMIN capability, or modifying the Users' profile role. 

Please also note that there may be some overlap with GH issue #246 since users have indicated the need to assign all projects to this new user as a requirement to complete the business operation.

**Comment by vijme** [comment]
Fixed in ALL Environments. Please open a new task for non-functional Report Tab in MDE Toolkit

**Comment by slmessier** [comment]
I was able to successfully validate this in all environments (including PRODUCTION) and will be closed.

(Note: this issue was not associated to a Milestone release due to being an on-call support request that required an immediate response.)
