### ISSUE TITLE
MDE Toolkit - Assess Capability to Assign All Projects to User

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#248]
**Users of the MDE toolkit have the business need to associate all open projects to a new user. Please assess whether this capability will cause the "Unrecoverable Application Error" to display** due to the causes described within issue #246.

This is the same issue reported and logged within GH issue #22 

![image](https://cloud.githubusercontent.com/assets/4098544/14331084/bc8db9fc-fc11-11e5-9ffb-f71a03ab9c2c.png)

**Comment by vijme** [comment]
Fixed in dev. Please test

**Comment by slmessier** [comment]
this issue was successfully validated in DEVELOPMENT, and will be updated to "Ready for Staging".

**Comment by rwingender** [comment]
Validated in Staging.

**Comment by Tad-Daniel** [comment]
Ready for production

**Comment by slmessier** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Appears to work in production.  Item complete.
