### ISSUE TITLE
QA Toolkit - Update Visual Layout of Tabs within User Interface

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#249]
**Please update the styling that is referenced to visualize the primary tabs within the QA Toolkit user Interface so that the Tabs can be more intuitively distinguished by users visually.**

---
### Email Correspondence

From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Thursday, April 21, 2016 2:16 PM
To: Scott Messier
Subject: Tabs

Scott

Could you check into the possibility of an interface tweak for me.  One of the biggest responses I hear from new users is “OH, I did not realize those were tabs.”  If we could do something similar to the sub tabs with the main tabs that would be a huge help. I believe this is done with the colors and padding in the CCS so  I hope it is not overly difficult.

I have included a concept.  Let me know what you think. It would be a HUGE help.

**(Requested) Concept**
![image](https://cloud.githubusercontent.com/assets/4098544/14785619/b5276a0c-0ac9-11e6-845f-01391479e314.png)

**Existing (Project Details - Subtabs)**
![image](https://cloud.githubusercontent.com/assets/4098544/14785062/c7d472ec-0ac6-11e6-9d68-da73f099d6ae.png)

Thanks
(Tad)

**Comment by slmessier** [comment]
This issue has been successfully validate in the DEVELOPMENT environment and will be marked as "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good in development.  Please make some color changes.  The selected Tab should be (354828) to match the current line color just below the tab and the non-selected tabs color should be (757F72).

**Comment by vijme** [comment]
Color changed in dev. Pls check

**Comment by Tad-Daniel** [comment]
Looks great.

**Comment by Tad-Daniel** [comment]
Looks good on my ipad but does not appear on IE-11 on my computer.  possibly a cache issue so I will try clear some stuff out.

**Comment by Tad-Daniel** [comment]
Looks good in production but I will leave this open as I may ask for some minor adjustments.

**Comment by Tad-Daniel** [comment]
Issue closed. Any additional updates will be with a new task.
