### ISSUE TITLE
QA Toolkit - Develop Email Notification to Active Users

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#250]
Please develop new **functionality to issue a system-delivered email to all active users of the system** using the workflow below:
1. The user clicks a **new button within the ADMIN menu w/ text "Email Active Users" (see graphic below)** ![image](https://cloud.githubusercontent.com/assets/4098544/14865204/8a72f66e-0c8b-11e6-9875-bc9c82fd0884.png)
2. **The system displays a modal screen pop up menu with 2 user input fields: (1) Subject & (2) Text and 2 buttons: _Send_ & _Cancel_**
3. The **user enters text into the Subject & Text user input fields and clicks Send**
4. The system **sends a system-issued email notification with to all active users of the system**, using the user-defined Subject & Text values to populate the email appropriately.

Note: this issue was originally requested as **No. 23 (Gray) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14862663/6d349ae0-0c80-11e6-863d-32cc9685315a.png)

**Comment by slmessier** [comment]
Note: this issue was originally requested as **No. 19 (Gray) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14862663/6d349ae0-0c80-11e6-863d-32cc9685315a.png)

**Comment by vijme** [comment]
Implemented in dev. Users in the current search will be the recipients. Clearing search will email all the users of the system. Please let me know if this needs to be changed.

**Comment by Tad-Daniel** [comment]
Perfect

**Comment by slmessier** [comment]
UI functionality has been successfully validated in the DEVELOPMENT environment. The notification functionality is unable to be verified in the development environment and will be performed against this issue within the STAGING environment.

Otherwise, this issue will be marked as "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Working correctly, push to production

**Comment by rwingender** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Working, Item closed
