### ISSUE TITLE
QA Toolkit - Inspection PDF Report - Append Inspection Document Attachments to PDF

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#251]
Please **enhance the current system functionality** that generates the Inspection Report PDF (shown below) **to automatically iterate through each of the documents attached to the selected inspection (shown below) record, and append each document to the end of the existing Inspection PDF Report** (in order).

**Existing Inspection PDF Launch**
![image](https://cloud.githubusercontent.com/assets/4098544/14866065/b2e1b834-0c8f-11e6-987e-dae1a4ea77d0.png)

**Example of Inspection's Supporting Document Attachment**
![image](https://cloud.githubusercontent.com/assets/4098544/14865950/3a9f2ece-0c8f-11e6-8c1c-f92a870c4c0a.png)

Note: this issue was originally requested as **No. 22 (Gray) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14862663/6d349ae0-0c80-11e6-863d-32cc9685315a.png)

**Comment by slmessier** [comment]
Due to the nature of the existing PDF libraries (PDF Sharp), **inspection attachment PDF packaging capabilities can be supported across the following file formats in batch to support this enhancement: PDF, BMP, PNG, GIF, TIFF, and JPEG.** 

Other file-formats will require additional customization, potentially for each type of file. This capability can be further assessed if necessary. However, **a finite list of supported file types would need to be identified, and then researched and potentially developed distinctly.**

**The compatible file formats listed above will support the majority of inspection document attachment types within the system.**

1. **Please update the system to appropriately append document attachments to the associated PDF Report for the supported file formats** identified above.
2. **When unsupported file-formats exist for an inspection, please include a line of text within the associated PDF Report that indicates as much.** Include the filename of the document in the line of text. If possible, also include a hyperlink to the inspection. Ex. “sample_file.txt – file type is not supported for PDF packaging. Please access manually thru the toolkit.”.

**Comment by vijme** [comment]
Implemented in dev. pLease test

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by slmessier** [comment]
this issue has been validated in the DEVELOPMENT environment and will be marked as "Ready for Staging"

**Comment by Tad-Daniel** [comment]
Item is working but it appears the pictures get resized and thus deformed in the document.  If the items are going to appear one per page then can they be fit to the page as not to distort the picture or document.  Is it possible to have multiple items per page/  Also please add the document description under the item.

**Comment by rwingender** [comment]
Descriptions have been added to the images, and images have been resized to fit to the page.  This issue has been validated in the Staging environment and will be marked as "Ready for Production".

**Comment by rwingender** [comment]
Descriptions have been added to the images, and images have been resized to fit to the page, but this release will need additional work in development.

**Comment by Tad-Daniel** [comment]
In production it seems that a report with attachments cause an "unrecoverable error" see CE4465180 dated 5/12/2016 with a PDF attachment.  Other reports appear to be functioning properly so is this possibly a size issue (3 meg file) or maybe because it's a multi page PDF.

**Comment by vijme** [comment]
After preliminary analysis, looks like the acrobat version which that pdf was created has some features that is not supported by the pdf merge tool that we use. Will check on other options to fix this issue and update

**Comment by vijme** [comment]
Fixed in dev

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by Tad-Daniel** [comment]
please verify that when a picture is resized to fit the page it maintains the original aspect ratio and does not crop any portions of the picture.

**Comment by rwingender** [comment]
Fixed and validated in Dev.  Attached documents now retain their original proportions when resizing to fit entirely on the page.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as Ready for Production.

**Comment by Tad-Daniel** [comment]
Looks good,  Could we give the attachment a naming convention such as "QA-1 (report date)"

**Comment by Tad-Daniel** [comment]
item complete
