### ISSUE TITLE
QA Toolkit - Notifications Triggered by Save Inspection - Automatically Attach Inspection Report PDF to Notifications

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#252]
Please update the existing system email notifications that are triggered **when users click on _Save Inspection_** (on the _Inspections-Reports_ tab) to **automatically attach the associated Inspection PDF form to the email as an email attachment**.
- **Apply to the _Add New Inspection_ screen**
  
  **AND**
- **_Update Existing Inspection_ screen**

![image](https://cloud.githubusercontent.com/assets/4098544/14888579/04f238e4-0d29-11e6-88c5-ff3cfe22a1af.png)

![image](https://cloud.githubusercontent.com/assets/4098544/14888572/0111ad04-0d29-11e6-89b3-2920d8eab8af.png)

Note: this issue was originally requested as **No. 21 (Gray) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14862663/6d349ae0-0c80-11e6-863d-32cc9685315a.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by rwingender** [comment]
UI functionality has been successfully validated in the DEVELOPMENT environment. The notification functionality is unable to be verified in the development environment and will be performed against this issue within the STAGING environment.

Otherwise, this issue will be marked as "Ready for Staging".

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as Ready for Production.

**Comment by Tad-Daniel** [comment]
Looks good, Could we give the attachment a naming convention such as "QA-1 (report date)"

**Comment by vijme** [comment]
Attachments given the same name format as when downloaded from application, which is "QAInsp_contractno_reportdate"

**Comment by Tad-Daniel** [comment]
Items complete
