### ISSUE TITLE
QA Toolkit - Events & Alerts Tab - Enhance Calendar Visualization Functionality

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#253]
**Please update the _Calendar_ that is displayed within the _Events & Alerts_ tab to display additional project information according to 2 distinct cases as described below:**

**Case 1 - Projects with Completed Inspections**
1. Show Projects with (1) association to active user AND (2) have Inspection Status = final
2. List Projects in **Black Font**
3.**Date Source = Inspection Date**
3. Display as Hyperlinks that **generate the associated PDF form when clicked**
4. This list is **accessible to all user profiles**

**Case 2 - Projects with Scheduled Future Inspection**
1. List Projects in **Red font**
2. **Date Source = Reuse logic from "Inspections-Schedule" Tab "Due Date" column**
3. Display as Hyperlinks that **link to the "Add New Inspection Form"**
4. This list is **accessible exclusively to "ESC Manager" & "Inspector" user profiles**

![image](https://cloud.githubusercontent.com/assets/4098544/14896554/53491d78-0d4c-11e6-89e9-cd9acc29203a.png)

Note: this issue was originally requested as **No.16 (Blue) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14896582/6ecb1402-0d4c-11e6-82b3-14acf7947b08.png)

**Comment by vijme** [comment]
Implemented in dev. Please note that I have given green background for final inspections and yellow background for scheduled inspections, because Milestones already had a black font. Please let know if any color changes needed.

**Comment by Tad-Daniel** [comment]
I looked back several years and it appears on some dates the items are repeating.  See screen-shot.  Also can the inspector search box be a dropdown.
![repeats](https://cloud.githubusercontent.com/assets/7913678/15020589/a5678664-11f0-11e6-992b-d6390ae76580.png)

**Comment by Tad-Daniel** [comment]
Also,  Only the Project number needs to show on the calendar.

**Comment by vijme** [comment]
Project number shown and inspector changed to dropdown and duplicates removed. Inspector is only queried for final inspections event since the other two events (milestone and schedule) are project based.

**Comment by slmessier** [comment]
this issue has been successfully tested in DEV and will be marked as "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Please make the font for the project numbers a bit larger.  I am not sure I am seeing all of the completed inspections.  When selecting a scheduled inspection the system should go directly to the draft inspection report instead of a project selection page.

**Comment by rwingender** [comment]
The requested changes have been partially implemented in Staging and will be moved to production, where additional work may be needed after the release. This issue has been validated in the Staging environment and will be marked "Ready for Production".

**Comment by rwingender** [comment]
Font has been enlarged, but this release will need additional work in development.

**Comment by vijme** [comment]
Fixed in dev

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by vijme** [comment]
Minor issue. Fixed in production and staging to show the final inspections. Clicking the link to open the draft inspection instead of project page is implemented in dev and will be available in production after the next release.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as Ready for Production.

**Comment by Tad-Daniel** [comment]
Looks good. item complete
