### ISSUE TITLE
QA Toolkit - Events & Alerts Tab - Enhance Search Filtering Functionality

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#254]
**Please update the Search Filtering functionality that exists within the _Events & Alerts_ Tab according to the following specifications:
**
1. **Remove the _Description_ Search Filter** parameter completely
2. **Add a new free-text wildcard search field for _Inspector_** that queries on the Inspector value
3. **Add a new Checkbox for _Inspections Completed_** that queries on the inspection status = final value
4. **Add a new _Print_ button and capability that generates a PDF** of the calendar on the screen according to the results of the search filter configuration.

![image](https://cloud.githubusercontent.com/assets/4098544/14898792/bdd2eb38-0d56-11e6-8396-9c7bd0f657dc.png)

Note: this issue was originally requested as **No. 15 (Blue) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14896582/6ecb1402-0d4c-11e6-82b3-14acf7947b08.png)

**Comment by vijme** [comment]
Implemented in dev.

**Comment by slmessier** [comment]
I'm not seeing the Print function that was described wihtin the graphic above as no.4 (Red). Otherwise the issue is validated.

**Please add a _Print_ button to the search filter that generates a PDF report of the calendar and active schedule.**

**Comment by slmessier** [comment]
Since the Print calendar function (no. 4 / red within the graphic above) is the only requirement that remains invalidated, a new issue (#264) has been created distinctly for tracking development of that capability.

Otherwise this issue has been validated and will be marked as "Ready for Staging".

**Comment by Tad-Daniel** [comment]
See notes on item 253.....

**Comment by rwingender** [comment]
This release will need additional work in development

**Comment by vijme** [comment]
fixed in dev

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as "Ready for Production".

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good, item complete
