### ISSUE TITLE
QA Toolkit- Tracking Systems- Enhance existing Permit Tracking System- update search filters

### ISSUE THREAD

**Issue by rwingender** [kcigeospatial/sha_oed_issues#257]
Add a new dropdown to the Permits search bar with options to show “All”, “Active”, and “Expired” permits.  

Old Layout:
![image](https://cloud.githubusercontent.com/assets/14997365/15300841/bf81e83c-1b78-11e6-8ab1-b4b6770af191.png)

New Layout:
![1b](https://cloud.githubusercontent.com/assets/14997365/15300896/083536e2-1b79-11e6-9d6e-b99d6e0aba20.jpg)

(Note: this issue was originally requested as No.1(b) and archived within GH issue #255 of this repository)

**Comment by vijme** [comment]
Implemented in dev, pls check

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by slmessier** [comment]
After double checking against my notes, **please also remove the "Show Closed" checkbox.** Thank you for pointing out the additional specification.

**Comment by vijme** [comment]
Implemented in dev, pls check

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by slmessier** [comment]
This issue has been validated in the DEVELOPMENT environment and will be marked as "Ready for Staging".

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as "Ready for Production".

**Comment by Tad-Daniel** [comment]
Working, item complete
