### ISSUE TITLE
QA Toolkit- Tracking Systems- Enhance existing Permit Tracking System- update role permissions

### ISSUE THREAD

**Issue by rwingender** [kcigeospatial/sha_oed_issues#258]
1)	Limit the ability to add new permits to the roles of “ESC Manager”, “Project Manager”, and “Inspector”.  These roles must be able to add new permits in both the Permits and Project Details (Permits subtab) sections. 
2)	Hide the “New Permit” button in both locations from all other roles. 

Permits tab location:
![1c_1](https://cloud.githubusercontent.com/assets/14997365/15301065/e43b7d5e-1b79-11e6-8945-150bc984d286.jpg)

Project Details (Permits subtab) location: 
![1c_2_2](https://cloud.githubusercontent.com/assets/14997365/15325059/1e8814b6-1c17-11e6-9b59-19ad8b940c64.jpg)

(Note: this issue was originally requested as No.1(c) and archived within GH issue #255 of this repository)

**Comment by vijme** [comment]
Under Permits tab, new permits could be created only by ESC Manager, Project Manager and Inspector, but under project details section "Inspector" cannot see the permits tab at all currently, so cannot add permits from here.

**Comment by slmessier** [comment]
This issue has been validated in the DEVELOPMENT environment and will be marked as "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good,  Push to production

**Comment by rwingender** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
working, item complete
