### ISSUE TITLE
QA Toolkit- Tracking Systems- Enhance existing Permit Tracking System- update buttons

### ISSUE THREAD

**Issue by rwingender** [kcigeospatial/sha_oed_issues#259]
Update the buttons under the permits tab to those supplied by Tad. 

(Note: this issue was originally requested as No.1(d) and archived within GH issue #255 of this repository)

**Comment by slmessier** [comment]
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Thursday, May 19, 2016 10:09 AM
To: Scott Messier
Cc: Viji Selvamani (viji.selvamani@ecointegration.com); Rachel Wingender (rachel.wingender@ecointegration.com)
Subject: RE: Text & Buttons to Support Task 8 Development

..... 

1. **I think it was the ADD button.  I have included it as an attachment.  Use this button everywhere in the system the ADD button is shown for adding attachments.**  
2. **For the CANCEL button use the cancel button we have used elsewhere in the system**

![biggrattach](https://cloud.githubusercontent.com/assets/4098544/15397395/1aa56d4c-1dae-11e6-9c7d-bdbbc0ef170e.png)

**Comment by vijme** [comment]
Implemented in dev, pls check

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by slmessier** [comment]
This issue has been validated in the DEVELOPMENT environment and will be marked as "Ready for Staging".

**Comment by Tad-Daniel** [comment]
Looks good, ready for production

**Comment by rwingender** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Looks good, item complete
