### ISSUE TITLE
QA Toolkit- Tracking Systems- Develop new Yellow Card certification tracking system- New tab

### ISSUE THREAD

**Issue by rwingender** [kcigeospatial/sha_oed_issues#260]
1)	Implement a new subtab for Yellow Card Certifications titled “YC Cert” under the Projects tab.
2)	Implement search criteria (district, company, name, Exp. date, and card number).
3)	Implement a grid list that includes “First Name”, “Last Name”, “Email”, “Profile”, “Expiration Date”, and “YC number”. 
4)	Only allow this tab to be visible to the Inspector, Project Manager, and ESC Manager roles.
5)	Users with expired yellow card certificates should be highlighted in red text, and users with revoked yellow card certificated should be highlighted in purple text. 

![2ab2](https://cloud.githubusercontent.com/assets/14997365/15326739/23c365e2-1c1d-11e6-8328-9d05987a84d7.jpg)

(Note: this issue was originally requested as No. 2(a & b) and archived within GH issue #255 of this repository)

**Comment by vijme** [comment]
Implemented in dev. Please test

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by slmessier** [comment]
**Please also enable print to PDF capabilities for the YC Cert Grid**, as was done for the Projects List Print function (shown below)

**Aside from adding print to pdf functionality, all other requirements related to this issue have been successfully validated.**

![image](https://cloud.githubusercontent.com/assets/4098544/15513430/9eae188e-21b2-11e6-88a7-8474f1e054b5.png)

**Comment by vijme** [comment]
Print functionality implemented

**Comment by slmessier** [comment]
This issue has been validated in the DEVELOPMENT environment and will be marked as "Ready for Staging".

**Comment by rwingender** [comment]
Validated in Staging.

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as "Ready for Production".

**Comment by Tad-Daniel** [comment]
working, item complete
