### ISSUE TITLE
QA Toolkit- Tracking Systems- Develop new Yellow Card certification tracking system- Update user profile

### ISSUE THREAD

**Issue by rwingender** [kcigeospatial/sha_oed_issues#261]
1)	Add Yellow Card certification number (“YC CERT”) and “Expiration Date” fields to the user profile. 
2)	Include same fields in the user settings section. 
3)	Add a “Revoke” checkbox and a “Reason for Revoke” text field to the user profile. 

![2cg2](https://cloud.githubusercontent.com/assets/14997365/15326835/6f9cb73e-1c1d-11e6-9552-2d340a0ab0cf.jpg)

(Note: this issue was originally requested as No.2(c & g) and archived within GH issue #255 of this repository)

**Comment by vijme** [comment]
Implemented in dev, please test

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by slmessier** [comment]
On the User Edit page, **please add logic to require the _"Reason for Revoke"_ value when the the user has checked the _"Revoked"_ checkbox and clicks _Save_**
![image](https://cloud.githubusercontent.com/assets/4098544/15513877/7bbaddba-21b4-11e6-860f-0daade27e32a.png)

**Comment by vijme** [comment]
Validation for revoke reason added when revoke is checked

**Comment by slmessier** [comment]
This issue has been validated in the DEVELOPMENT environment and will be marked as "Ready for Staging".

**Comment by rwingender** [comment]
Validated in Staging.

**Comment by Tad-Daniel** [comment]
Looks good,  Ready for production

**Comment by rwingender** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Item complete
