### ISSUE TITLE
QA Toolkit - Incentives/Damages Enhancements - Automatically Calculate Quarterly Reporting Period

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#265]
![image](https://cloud.githubusercontent.com/assets/4098544/15579872/80b70bf0-2334-11e6-846a-b7241c3ccdc7.png)

(Note: this issue was originally requested as No.3 and archived as No.3-1 within GH issue #255 of this repository)

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as Ready for Production.

**Comment by Tad-Daniel** [comment]
Looks good, item complete
