### ISSUE TITLE
QA Toolkit - Incentives/Damages Enhancements - Automatically Determine & Calculate Incentive & Liquidated Damages Qualification

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#266]
![image](https://cloud.githubusercontent.com/assets/4098544/15589217/e217b7f2-235f-11e6-837d-2d646a49234b.png)
![image](https://cloud.githubusercontent.com/assets/4098544/16023109/3e9792f4-3189-11e6-9a68-ffb298a716c6.png)

(Note: this issue was originally requested as No.3 and archived as No.3-2 within GH issue #255 of this repository)

**Comment by slmessier** [comment]
(Identified in On-Site Discussion with Tad 6/13/2016):
**Please note the additional logic for determining the _Final Incentive Estimate_ below in red, and implement accordingly:**
![image](https://cloud.githubusercontent.com/assets/4098544/16023061/f8953748-3188-11e6-8efb-90d9500b423e.png)

**Note: the system currently calculates average grade on the _Projects List Grid_ (below):**
![image](https://cloud.githubusercontent.com/assets/4098544/16023557/4143fe5a-318b-11e6-95a8-99ba74719428.png)

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as Ready for Production.

**Comment by Tad-Daniel** [comment]
Looks good, item complete
