### ISSUE TITLE
QA Toolkit - Incentives/Damages Enhancements - Develop Updates to QA Incentives Tab User Interface

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#267]
![image](https://cloud.githubusercontent.com/assets/4098544/15580001/fd411896-2334-11e6-8b7a-54909807ed4f.png)

(Note: this issue was originally requested as No.3 and archived as No.3-3 within GH issue #255 of this repository)

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by slmessier** [comment]
(Identified in On-Site Discussion with Tad 6/13/2016):
**Please remove the logic and pop-up window message that is associated with the _Calculate Incentives_ hyperlink function. The message is not necessary.**
![image](https://cloud.githubusercontent.com/assets/4098544/16023389/94e9840e-318a-11e6-879d-c93cf9d4444a.png)

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as Ready for Production.

**Comment by Tad-Daniel** [comment]
Looks good, item complete
