### ISSUE TITLE
MDE Toolkit - Update Existing User & User Profile - Error Message / Unable to complete workflow

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#27]
Issue exists in Test environment and Production environment. Unable to complete administration workflow to update user account information for an existing user account.

Steps to Replicate: 
1.ADMIN-->User List --> edit existing user
2.Update any attribute and click save
3. system issues error message shown below
![image](https://cloud.githubusercontent.com/assets/4098544/3350140/56c9d6b6-f991-11e3-9a96-72c0d173a607.png)

**Comment by slmessier** [comment]
note the overlap in scope with GH issue #27 . It is expected that one solution will resolve both issues.

**Comment by slmessier** [comment]
this issue was successfully validated in DEVELOPMENT, and will be updated to "Ready for Staging".

**Comment by Tad-Daniel** [comment]
ready for production

**Comment by slmessier** [comment]
This has been validated in STAGING and will be updated to "Ready for PRODUCTION".

**Comment by Tad-Daniel** [comment]
Appears to work in production.  Item complete.
