### ISSUE TITLE
QA toolkit- Add milestone

### ISSUE THREAD

**Issue by rwingender** [kcigeospatial/sha_oed_issues#270]
Develop a functioning date picker for the Add Milestone section under the Projects->Milestones subtab.  The current date picker is not functional. 

![datepicker](https://cloud.githubusercontent.com/assets/14997365/15788542/0078d15e-2996-11e6-8d41-9ff75f016080.jpg)

**Comment by vijme** [comment]
Already existing as issue #59 and hence closed
