### ISSUE TITLE
OED Toolkit Portal Home Page - Update Document Hyperlinks to New Document Versions

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#271]
# Request 
**Please update the 2 hyperlinks on the Portal landing page to hyperlink to new versions of each document.**

---
# Attached Documents
[OEDtoolkits account request.docx](https://github.com/kcigeospatial/sha_oed_issues/files/309204/OEDtoolkits.account.request.docx)
[OEDtoolkits account update.docx](https://github.com/kcigeospatial/sha_oed_issues/files/309205/OEDtoolkits.account.update.docx)

 ---
# Email
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Friday, June 10, 2016 10:05 AM
To: Scott Messier
Subject: Document update

Scott

**Can the attached documents be updated.  These are the two documents located for download on the landing page.**

**Comment by Tad-Daniel** [comment]
Item complete
