### ISSUE TITLE
QA Toolkit - Inspections-Schedule Tab - Add Permit Columns to Grid/Table

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#272]
Please add new columns to the upcoming _Inspection Deadlines_ datagrid as checkbox/binary values. 
- **check = permit record exists** for project
- **unchecked = permit record does not exist** for project
![image](https://cloud.githubusercontent.com/assets/4098544/15973821/67a8cb22-2f13-11e6-9213-aab6c01e9b85.png)

---
(Identified in On-Site Discussion with Tad 6/13/2016):
**Permit Columns Data Mapping:**
- **E&S = _‘Stormwater Management & ESC Approval’_** (Permit Description)
- **NPDES = _‘NPDES General Permit’_** (Permit Description)
- **WW = Create a new binary attribute on Project Details** for tracking “_**Wetlands and Waterways**_”. Users will maintain this attribute. **Link the checkbox within the permit column to the new attribute** on the project.
- **Inc = Total Incentive > 0**  ![image](https://cloud.githubusercontent.com/assets/4098544/16025016/ef39cb5a-3192-11e6-8ede-9bd382cb31e1.png)
- **SW = Create a new binary attribute on Project Details** for tracking “_**Severe Weather**_”. Users will maintain this attribute. **Link the checkbox within the permit column to the new attribute** on the project.

Note: this issue was originally requested as **No. 14 (Blue) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14896582/6ecb1402-0d4c-11e6-82b3-14acf7947b08.png)

**Comment by vijme** [comment]
Implemented in dev. Pls check

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by Tad-Daniel** [comment]
Looks Ok but the box's tend to clutter the interface and make it hard to see the checks at a glance, can the dox's be hidden with only the checks visible or is there another way to designate the check.

**Comment by slmessier** [comment]
The checkboxes within the UI grid have been updated as indicated below. Please confirm.
![image](https://cloud.githubusercontent.com/assets/4098544/16309517/fbd4c5e4-3936-11e6-9c9c-31f74fb0bfa2.png)

**Comment by Tad-Daniel** [comment]
Yes, Looks great

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as Ready for Production.

**Comment by Tad-Daniel** [comment]
Looks good, item complete
