### ISSUE TITLE
QA Toolkit - Inspection-Schedule Tab - Implement Search Filtering Functionality

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#273]
**Please develop Search Filtering functionality for the _Inspections_Schedules_ Tab using the following search field parameters:**

**1. District
2. County
3. Inspector**

![image](https://cloud.githubusercontent.com/assets/4098544/15977240/959be584-2f25-11e6-8892-f3acecc79ee5.png)

Note: this issue was originally requested as **No. 15 (Blue) within the _Requested Updates.docx_** and archived within GH issue #228 of this repository
![image](https://cloud.githubusercontent.com/assets/4098544/14896582/6ecb1402-0d4c-11e6-82b3-14acf7947b08.png)

**Comment by slmessier** [comment]
(Identified in On-Site Discussion with Tad 6/13/2016):
 **Please omit the _Inspector_ parameter from the Search Filter**. Otherwise develop as specified.

**Comment by vijme** [comment]
@slmessier , just to make sure the schedule page had three tables for schedule, hold and not started. Implemented the search for all three. Also, there was already a search for number of days for schedule that was included along with the new search. Dev is already implemented with this change. Please let me know if otherwise

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by rwingender** [comment]
Validated in Staging.

**Comment by rwingender** [comment]
This issue has been validated in the Staging environment and will be marked as Ready for Production.

**Comment by Tad-Daniel** [comment]
Looks good, item complete
