### ISSUE TITLE
QA Toolkit - Modifications Tab - Update Sort Order of Grid

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#275]
On the Modifications Tab, the Modification Requests Grid is sortable by the _"Request Date"_date. However, **the system currently sorts the values based on the character string value rather than the actual date value** (see the example within the graphic below).  

**Please update the system so that the sorting within the grid considers the actual date value rather than the character string.**

**Example of sorting issue:**
![image](https://cloud.githubusercontent.com/assets/4098544/17937734/1bb9917e-69f1-11e6-8d0b-1e74a6c1edda.png)

**Comment by vijme** [comment]
Fixed in dev

**Comment by slmessier** [comment]
This issue has been validated in the DEVELOPMENT environment and will be marked as Ready for Staging

**Comment by rwingender** [comment]
This issue has been validated in STAGING.

**Comment by Tad-Daniel** [comment]
Complete
