### ISSUE TITLE
QA Toolkit - System Email Notifications - PDF Attachment SizeLimitation

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#276]
**System email notifications that include a PDF attachment are not passing through SHA's email filter due to exceeding the 12MB attachment limit.**

Please explore / identify opportunities to workaround this restriction, potentially using a method similar to the feedback provided from Tad below:
Via Email 8/10:  _"When pics are included with the QA-1 PDF the file size can grow large.  The attachment limit on incoming emails to SHA is 12 megs so these attacked reports often get rejected. Can the system that creates the report optimize the PDF document to help reduce file size.  **Using the “save as”-“Reduced size PDF…” options in Acrobat massively reduces file sizes** and I was curious if the toolkit report generating system can do similar."_

**Comment by slmessier** [comment]
## Update 8/30/2016
### Technological Background:
Crystal Reports is the toolkit’s existing underlying reporting technology platform. Unfortunately this version of Crystal Reports does not support the “Save as - Reduced Size PDF” function as it exists in Acrobat. Due to this inherent technology restriction, the toolkit is not able to be updated using the method outlined in Tad's initial request.

### Recommended Solution:
As an alternative method of potentially solving the PDF file size limitation, Viji has designed & prototyped the following re-packaging routine through the development of additional customized code, and offers it as a recommended potential solution: 
1.	Convert each image of PDF to distinct file(s) in JPG format 
2.	Compress JPG file(s), as needed (noting tradeoff w/ reduced image quality)
3.	Re-package compressed jpg file(s) into PDF format

### Limitations of Solution:
1.	**_Images will not retain their original file-extension_** for Email Notification PDF attachments.
2.	**_The compressed file size comes with a tradeoff of reduced image quality._** 
  - The quality output images should be examined to ensure this tradeoff (of file size and image quality) is balanced acceptably
  - **_Stakeholder Action: please review and confirm acceptance_**

3.	**_The recommended solution would represent a divergence in the existing code-block for PDF packaging._** The existing code applies functionality identically for each of **_2 cases – (1) the Email notification w/PDF attachment, and (2) the PDF download through the system UI_**. The new routine to reduce the PDF file-size would be applied distinctly to the case of the email notifications, and not the case of downloading through the UI – representing the divergence in code for the two cases.
4.	**_To implement effectively and remain beneath the 12MB SHA email file size limit, the system must enforce a limit as to a maximum number of images that would be attached._** (Otherwise in theory, even reduced-size packages would eventually exceed 12 MB with the capability to attach images infinitely.) 
  - The example below represents system output that is representative of a 10 image limit being enforced
  - **_Stakeholder Action: please review and confirm acceptance_**

### Sample of Reduced-Size Output using 10 Image limit:

**Comment by Tad-Daniel** [comment]
Sounds like a good approach.  Will this solution work no matter what format the files are in.  JPG, PDF, BMP, PNG ( I think these are the current acceptable file formats)

**Comment by vijme** [comment]
Yes, all the image formats that we support currently would work. Basically all images are converted to jpgs and compressed if needed.

**Comment by Tad-Daniel** [comment]
Sounds like a good solution, Lets do it.

**Comment by rwingender** [comment]
This issue has been validated in STAGING.

**Comment by Tad-Daniel** [comment]
Looks good.  How soon can this be pushed to production?

**Comment by vijme** [comment]
we can push today(9/29) or tomorrow(9/30) evening after 5, please confirm.

**Comment by Tad-Daniel** [comment]
Today is great.  please do.

**Comment by Tad-Daniel** [comment]
Complete
