### ISSUE TITLE
QA Toolkit - Custom SQL Select / Data Extract in Support of MS4 Reporting

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#277]
**In support of SHA's annual reporting requirements to MDE, users have requested a customized data dump of pertinent data values from the QA Toolkit.** Users will utilize the output from the query to generate the metrics that will feed into the report.

**Please find the attached specifications document for the requirements of the query.**

**_Current Specifications Version  (3.0):_**
[QADataExtractRequirementSpecifications_V3.0_20160914.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/539968/QADataExtractRequirementSpecifications_V3.0_20160914.pdf)

Previous Version  (2.0):
[QADataExtractRequirementSpecifications_V2.0_20160912.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/467561/QADataExtractRequirementSpecifications_V2.0_20160912.pdf)

Previous Version  (1.0):
[QADataExtractRequirementSpecifications_V1.0_20160909.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/464791/QADataExtractRequirementSpecifications_V1.0_20160909.pdf)

**Comment by slmessier** [comment]
**Attached updated specifications document (version 2.0) which includes the following revisions:**

1. **_Updated # 1.2 - updated text to 10/05/2015_** as the corrected start of the reporting period (previously erroneously documented as 2016).
2. **_Added # 3.20 - Inspection Date_** to the listed attribute output requirements

**Comment by slmessier** [comment]
**Attached updated specifications document (version 3.0) which includes the following revisions:**

1. **_Added # 3.21 - Project County_** to the listed attribute output requirements
1. **_Added # 3.22 - Project Northing_** to the listed attribute output requirements
1. **_Added # 3.23 - Project Easting_** to the listed attribute output requirements
1. **_Added # 3.24 - Project Datum_** to the listed attribute output requirements

**Comment by slmessier** [comment]
request has been fulfilled and will be closed:

From: Nicholas Walls [mailto:NWalls@sha.state.md.us] 
Sent: Thursday, October 20, 2016 7:31 AM
To: Scott Messier <Scott.Messier@kci.com>; Tad Daniel <tdaniel@sha.state.md.us>
Cc: Jeff Tirschman <Jeff.Tirschman@kci.com>; Jeff Tirschman <JTirschman@sha.state.md.us>
Subject: Re: QA Toolkit discussion

Hi Scott
Yes, we were able to use the data provided to support the MDE Annual Report submittal. Thank you for all your help, and Tad as well! Please go ahead and closer that support request.
That said, we may want to sit down with you all at some point in the future to discuss ways to implement a more comprehensive process to address what will be an on-going need for the NPDES  permit. So dont be surprised if we reach out and hassle you all some more!

thanks again!
Nick 

Nick Walls, AICP, GISP
Consultant for the Maryland State Highway Administration
 
________________________________________
From: Scott Messier <Scott.Messier@kci.com>
Sent: Wednesday, October 19, 2016 3:21 PM
To: Nicholas Walls; Tad Daniel
Cc: Jeff Tirschman; Jeff Tirschman
Subject: RE: QA Toolkit discussion 
 
Hi Nick,
I just wanted to circle back around to closing this data extract request if possible.
I assume you were able to accept the latest iteration of system output from the QA toolkit. 
If that is indeed the case, could you please provide confirmation of your acceptance so that I can update and close out the corresponding support ticket on our end?
Thank you!

**Comment by slmessier** [comment]
@vijme 
This data extract process is being requested for the current reporting period (2016 - 2017) to support MS4 Reporting.

**Please reference version 3 of the specifications above to support assessing the level of effort. In particular is there an opportunity to re-use scripts or queries from last year's request to generally minimize new development effort?**

**Comment by vijme** [comment]
@slmessier , i went through this requirement,  and looks like it is still the same as last years. The task is not so complex, i expect to get the report ready in a couple of hours, However i want to make sure the date. the requirement says "Project has an associated Permit issued within the current reporting period of 10/05/2015 thru current". Does it still hold good or do we need to change query for this year?

**Comment by slmessier** [comment]
(As of 08/21/2017) - **Current reporting period is July 1, 2016 through June 30, 2017**

------------------------------------------
From: Jeff Tirschman 
Sent: Monday, August 21, 2017 11:08 AM
To: Scott Messier <Scott.Messier@kci.com>; Nicholas Walls <NWalls@sha.state.md.us>
Cc: Tad Daniel <tdaniel@sha.state.md.us>; Don Hoey <DHoey@sha.state.md.us>; Jeff Tirschman <Jeff.Tirschman@kci.com>
Subject: RE: QA Toolkit discussion

Hi Scott,
Not sure if Nick responded already, but we would want July 1, 2016 through June 30, 2017.
Thanks!

**Comment by slmessier** [comment]
@vijme - Please run script using reporting parameter stated immediately above. Email results to scott.messier@kci.com.

**Comment by vijme** [comment]
Results emailed

**Comment by slmessier** [comment]
**Data extract for reporting year 2017 has been confirmed (see email below). Issue will be closed.**

From: Nicholas Walls [mailto:NWalls@sha.state.md.us] 
Sent: Wednesday, September 6, 2017 12:12 PM
To: Scott Messier <Scott.Messier@kci.com>; Jeff Tirschman <Jeff.Tirschman@kci.com>
Cc: Tad Daniel <tdaniel@sha.state.md.us>; Don Hoey <DHoey@sha.state.md.us>
Subject: Re: QA Toolkit discussion

Hey Scott
Sorry for the delay getting back to you. I do believe that we have everything we need from you to complete this portion of the Report. 
thanks again for your help!
Nick 

Nick Walls, AICP, GISP
Consultant for the Maryland State Highway Administration
 
________________________________________
From: Scott Messier <Scott.Messier@kci.com>
Sent: Friday, September 1, 2017 2:39 PM
To: Nicholas Walls; Jeff Tirschman
Cc: Tad Daniel; Don Hoey
Subject: RE: QA Toolkit discussion 
 
Hi Nick,
Have you been able to confirm the validity of this delivery? Just wanted to follow up.
Please let me know – thanks!
From: Scott Messier 
Sent: Tuesday, August 22, 2017 11:02 AM
To: 'Nicholas Walls' <NWalls@sha.state.md.us>; Jeff Tirschman <Jeff.Tirschman@kci.com>
Cc: 'Tad Daniel' <tdaniel@sha.state.md.us>; 'Don Hoey' <DHoey@sha.state.md.us>
Subject: RE: QA Toolkit discussion
 
Hi Jeff & Nick,
Please find the attached (2) excel files which have been extracted from the OED Toolkit as representation of the requested reporting period.
•                  PROJ_PERM_2017.xls: contains Projects in construction phase, having SWM or NPDES permit issued between 07/01/2016 and 06/30/2017.
•                  PROJ_INSP_2017.xls: contains inspection records and associated information for the projects identified in number 1 above.
Could you please send confirmation that these files satisfy your request so that I can update the tracking history on our end?
Otherwise, please let me know if you have any questions or concerns – thank you!
