### ISSUE TITLE
MDE Toolkit - Add newNew Proj-Permit using MDSPGP-5 Permit Template - Error Uploading Docs

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#278]
**Users of the MDE Toolkit are encountering an application error when attempting to "Add a New Permit" to a project, specifically when the new permit references the "MDSPGP-5" permit template type.** The error obstructs the user from completing the associated worfklow.

**Please investigate the source of what is causing the error and assess the feasibility of a potential solution.** 

To replicate the Issue (reference the graphic below as needed):
1. Click the icon to Edit Project Details (_AW730A21: MD 346 Slope Stabilization & Repair LOA_ in graphic)
2. Click the Permits subtab, and then click the Add a New Permit button
3. Set the Permit to the "_MDSPGP-5_"permit type, and populate the required text input fields (Issued & Expire Dates, Permit # text)
4. Click to "Upload Permit Document"
5. Browse to select a file to upload and populate the required text input fields
6. Click the Add Attachment Button - the system error will be triggered and the system will display the error message

![mde_mdspgp5_issue_20161116](https://cloud.githubusercontent.com/assets/4098544/20358449/d07a357e-abf9-11e6-9912-f0cd5d88fd20.gif)

**Comment by vijme** [comment]
This permit has 54 conditions associated to it. Paging needs to be implemented to show conditions across different pages, with a limit of 50 conditions per page.

**Comment by slmessier** [comment]
From: Merkle, Lindsay D. [mailto:LDMerkle@mccormicktaylor.com] 
Sent: Thursday, December 01, 2016 5:56 PM
To: Ed Tinney <etinney@rkk.com>; Cheryl Jordon (SHA) <CJordon@sha.state.md.us>; Scott Messier <Scott.Messier@kci.com>
Cc: Todd Nichols <TNichols@sha.state.md.us>
Subject: RE: Toolkit upload issue

Our GP-5 upload was successful as well! Thank you!!
-Lindsay
From: Ed Tinney [mailto:etinney@rkk.com] 
Sent: Thursday, December 01, 2016 4:25 PM
To: 'Cheryl Jordon (SHA)'; Merkle, Lindsay D.; Scott Messier
Cc: Todd Nichols
Subject: RE: Toolkit upload issue

Cheryl,
I just tested out a GP-5 upload and it worked!
Thanks,
Ed

From: Cheryl Jordon (SHA) [mailto:CJordon@sha.state.md.us] 
Sent: Monday, November 28, 2016 10:47 AM
To: 'Merkle, Lindsay D.' <LDMerkle@mccormicktaylor.com>; Scott Messier <Scott.Messier@kci.com>
Cc: Ed Tinney <etinney@rkk.com>; Todd Nichols <TNichols@sha.state.md.us>
Subject: RE: Toolkit upload issue

Thanks Lindsay and Scott.

From: Merkle, Lindsay D. [mailto:LDMerkle@mccormicktaylor.com] 
Sent: Monday, November 28, 2016 10:22 AM
To: Scott Messier <Scott.Messier@kci.com>; Cheryl Jordon (SHA) <CJordon@sha.state.md.us>
Cc: 'Ed Tinney' <etinney@rkk.com>; Todd Nichols <TNichols@sha.state.md.us>
Subject: RE: Toolkit upload issue

Thank you! We will test it out and let you know!
-Lindsay
From: Scott Messier [mailto:Scott.Messier@kci.com] 
Sent: Monday, November 28, 2016 10:21 AM
To: Cheryl Jordon (SHA)
Cc: 'Ed Tinney'; Merkle, Lindsay D.; Todd Nichols
Subject: RE: Toolkit upload issue

Hi Cheryl,
After investigating the reported issue, the source was determined to originate from a limitation in the toolkit code that constrains a permit template to a maximum of 50 conditions. (There were 54 conditions originally associated with the MDSPGP-5.) 
The simplest method for working around this constraint is to update to the structure of how the MDSPGP-5 permit template is configured within the system. I have gone ahead and made this update so that the MDSPGP-5 permit instead has exactly 50 conditions. 
At this point I expect that users should experience no issue associating documents to the MDSPGP-5 permit.
Could you please coordinate with a designate user – perhaps Ed or Lindsay – to test and confirm?
After I receive confirmation from you I will close the support ticket on our end. 
Please let me know – thank you!
