### ISSUE TITLE
QA Toolkit - New SWM As-Built Workflow - Development Specifications

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#279]
### Workflow Step 1: (New) SWM As-Builts Subtab on Project Details
**Create a new “SWM” subtab on the Project Details page**. Authorized users will initiate an SWM submittal from this subtab. **The UI layout of the Modifications Tab represents a logical template starting point, with the additional UI considerations noted below:**
1. **Review Status** - populated with 4 possible values: _Pre-Submittal; Pending; Under Review; Approved_ 
2. **Facilities In Package** - populated with the corresponding value from the _"SWM As-Builts Request Form"_. (see section below)
3. **_New Submittal Button_** - authorized users will click this button to initiate a new request. When a user clicks, the system will display the _"SWM As-Builts **Request** Form"_ with empty values for all input fields. (see section below)
4. **_Respond Button_** - authorized users will click this button to respond to a pre-existing request. When a user clicks, the system will display the _"SWM As-Builts **Response** Form"_ with the existing values pre-populated. (see section below). **The system will not display the _Respond Button_ for requests with status value = _Approved_.**
5. **_AB Button_** - authorized users will click this button to view or edit the details of a pre-existing request. When a user clicks, the system will display the _"SWM As-Builts **Request** Form"_ with the existing values pre-populated. (see section below). 
![untitled_clipping_113016_114222_am](https://cloud.githubusercontent.com/assets/4098544/20761779/1a5d9dfe-b6f2-11e6-98c3-e4ad2fca5732.jpg)
### Workflow Step 2: SWM As-Builts Request Form 
**The _"SWM As-Builts Request Form"_  works similar to the existing QA-3 form (for Modifications). Please re-use the logic as a starting point.** Project Information existing in the system already is pre-populated just like on the QA-3 form.  This form will remain editable until the _Review Status_ value = _"Approved"_; at which point it cannot be modified. Otherwise, **the uniquely distinct design considerations for the _"SWM As-Builts Request Form"_ are listed below:**
1. **Form Title: _"SWM As-Built Submittal Request Form"_**
2. **2 (New) Text Input Fields: _"SWM Facilities Included"_; _"Comments"_**
3. **Add Attachments Grid**
4. **Read-Only Text Guidelines** - please recreate the text displayed in the associated graphic
5. **Signature Lines** - 
    - **_Contractor_** - validation functions identically to the QA3 Form; 
       - **When an authorized _Contractor Signature_ is saved to the request, the system will automatically update the _Review Status_ value to _“Pending”_.**
    - **_SHA P.E._** - system will validate that user is authorized as _SWM As-Built District Rep_ on admin page (see permissions section below);
       - **When an authorized _SHA P.E. Signature_ is saved to the request, the system will automatically update the _Review Status_ value to _“Under Review”_.**
    - **_HHD_** - system will validate that user is authorized as _SWM As-Built Approver_ on admin page (see permissions section below);
       - **When an authorized _HHD Signature_ is saved to the request, the system will automatically update the _Review Status_ value to _“Approved"_**
6. **_Respond Button_ is not displayed until after the request has first been saved** (just as it does in the QA-3 form). 
7. **_Save Button & Respond Button_** are not displayed at all when the Review Status value = _Approved_, leaving the form otherwise un-editable (just as it does in the QA-3 form). 
    - **When a request is saved with 0 Authorization Signatures, the system will automatically update the _Review Status_ value to _“Pre-Submittal"_**
![untitled_clipping_113016_125404_pm](https://cloud.githubusercontent.com/assets/4098544/20764411/14d6859e-b6fc-11e6-94e1-8302c1e30dc2.jpg)
### Workflow Step 3: SWM As-Builts Response Form & Approval
**The _SWM As-Builts Response Form_ is a simplified version of the modification (QA3) response form.  Please re-use the logic as a starting point.** Project Information existing in the system already is pre-populated just like on the QA-3 response form.  Otherwise, **the uniquely distinct design considerations for the _"SWM As-Builts Response Form"_ are listed below:**
1. **Form Title: _"SWM As-Built Submittal Request Form"_**
2. **_"SWM Facilities Included_" value is populated appropriately**
3. **2 Input Fields: _"Stakeholders who will be..."_ & _"Response Text"_** - functionalities identical to respective fields on QA3 Response Form
4. **_Review Status_ Dropdown - values are displayed as read-only** (since status is otherwise updated and maintained through automatic links to Authorization Signatures on the _"SWM As-Builts Request Form"_.
5. **Read-Only Text Guidelines** - please recreate the text displayed in the associated graphic.
6. **Functionality to add attachments will not exist at all** - please remove this capability using methods of developer's discretion.
![untitled_clipping_113016_030555_pm](https://cloud.githubusercontent.com/assets/4098544/20769073/7fa7fe22-b70e-11e6-9e98-3876d185366d.jpg)
---
## SWM AS-BUILTS (OVERVIEW) MENU
**Create a New _"SWM As-Builts"_ Menu/Tab (at the top, beneath the banner) nested beneath the Projects Menu/Tab for
viewing SWM submittal summary information**, similar to the function of the corresponding _Modification Overview Menu_. **Please re-use the logic as a starting point, with the following additional design considerations:**
1. **Menu Title: _"SWM As-Builts"_**
2. **_"SWM As-Builts"_  nested beneath _Projects Menu_**
3. **Include a print function** that is otherwise identical to that of the _Modification Overview Menu_.
4. **Include the search filtering paramters illustrated in the graphic below.**
5. **Include the grid, columns, & values illustrated in the graphic below.**
![untitled_clipping_113016_035031_pm](https://cloud.githubusercontent.com/assets/4098544/20770741/ba4ecdd4-b714-11e6-8625-a895181bc870.jpg)
---
### New System User Profiles & Updates to Admin UI
1. **_SWM As-Built District Rep_** - is the source of the validation check **associated with the _"SHA P.E. Signature"_ on the _"SWM As-Built Submittal Request Form"**_; if checked the associated user account is an active member of this profile
2. **_SWM As-Built Approver_** - is the source of the validation check **associated with the _"HHD Signature"_ on the _"SWM As-Built Submittal Request Form"**_; if checked the associated user account is an active member of this profile
3. **Enforce Group Membership Participation in HHD Group for Approver** through a validation check:
    - Trigger: **When a user attempts  to save **_SWM As-Built Approver_** as checked, and the _"Hydraulics Division" Group_ is NOT checked**.
    - Response: Do not save changes & instead **issue the standard application message with text, _"Error: User with SWM As-Built Approver permission must have HHD Group Membership"_**.
4. **Update the 2 Text Labels of the Modification Request Checkboxes** for clarity of interpretation
    - New Text: _"Modification Package Approver"_
    - New Text: _"Modification Request Approver"_
![image](https://cloud.githubusercontent.com/assets/4098544/20772441/6fd90a2e-b71b-11e6-9dc3-94dfcab50fdd.png)
---
## NOTIFICATIONS
**The _SWM As-Builts Notification triggers will closely mirror the existing Modification Request (QA3) Notifications.  Please re-use the logic as a starting point.** 
### Cases That Trigger Sending of SWM-Based Notifications

1. **Upon Initial Save of Request**
    -**New Recipients**: _User Saving the Request_
 2. **When a user Saves a Response**
    -**New Recipients** (add to list with previous recipients): _User Saving the Response_
3. **When _"Review Status"_ value is saved by the system as _"Pending"_**
    -**Recipients** (add to list with previous recipients): **_All active users having _SWM As-Built District Rep_ Permissions_**
4. **When _"Review Status"_ value is saved by the system as _"Under Review"_**
    -**Recipients** (add to list with previous recipients): **_All active users having _SWM As-Built Approver_ Permissions_**
### Notification Examples
1. **Sample of Initial Notification – Applies to notification case # 1 only**
![image](https://cloud.githubusercontent.com/assets/4098544/20774492/924b8718-b724-11e6-8e98-33f4f3e9da83.png)
2. **Sample of Subsequent Notifications – Applies to notification case #’s 2, 3, & 4**
![image](https://cloud.githubusercontent.com/assets/4098544/20774742/99b2ecca-b725-11e6-8d82-261095f132ad.png)

------------------------------------------------------------------------------------------------
_Tracking Note: this issue was originally requested as **No. 1.29 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
In the swm request and response page, notification box check list, who should be included? Should all the project users be shown in the notification list for the users to choose additional members for notification just like in QA Concurrance?

**Comment by Tad-Daniel** [comment]
Yes

**Comment by vijme** [comment]
Complered in dev.

**Comment by linsentp** [comment]
Tested in DEVELOPMENT did not encounter any issues--Did not test notification abilities

**Comment by slmessier** [comment]
**_Please implement the following updates noted during final review of the development release_** associated with this issue:

### 1. **_SWM AB Request Form:_** typo on Comments UI Label - **_update label text from “Commment” to “Comment”_**
![image](https://cloud.githubusercontent.com/assets/4098544/21957200/7549978c-da5f-11e6-896b-bb91ae3500f5.png)

---------------------------------------------------------------------------------------------------

### 2. **_SWM AS Builts Overview Menu_: please add a column for _Approval Time_** if that information is made available by the underlying database.
![image](https://cloud.githubusercontent.com/assets/4098544/21957223/05a6be68-da60-11e6-9197-498d7f826821.png)

--------------------------------------------------------------------------------------------------
### 3. **_SWM AS Builts Overview Menu_: update hyperlink target for the _View Button_** 
The _View Button_ may need to be redirected to the _Project Details - SWM Subtab_ pending clarification with stakeholders** (currently the SWM AB Record itself is the target)
  - [_**This text will be updated to indicate instruction requested from stakeholders**_]
![image](https://cloud.githubusercontent.com/assets/4098544/21957443/1c4aa7c0-da64-11e6-99e7-69d2027427c7.png)

**Comment by vijme** [comment]
Updated to specifications

**Comment by linsentp** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by Tad-Daniel** [comment]
Looks good except can the authentication for the contractor be limited to only account roles of "contractor" and swap out the "SHA PE" button with the "Rec By" button attached.
![gr60signrecievedby](https://cloud.githubusercontent.com/assets/7913678/22248934/e352eb96-e20e-11e6-91bf-e77b94b4979a.png)

**Comment by vijme** [comment]
Updated according to specifications in dev

**Comment by slmessier** [comment]
Tad - requested changes have been updated. Please provide confirmation.

**Comment by Tad-Daniel** [comment]
Looks good.  Appears to work correctly

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Working good
