### ISSUE TITLE
QA Toolkit - Bulk dump of inspections b/w specific dates to PDF - Output to BP/SS-Reports tab

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#282]
### Create a new Report on the BP/SS page under the Reports subtab. Authorized users will generate a report of all inspections done on a project between specified dates. 

1. _The New function will **exist as a new Report on the BP/SS-Reports tab_**
2. **_Form Report Name_ - "QA Project Inspections By Date"**
3. **_Allow users to select by 'Project'_**
          - using a type-ahead dropdown text box
          - values in the dropdown menu are formulated by: [CONTRACT#] - [PROJ DESCRIPTION]
4. **_Allow users to enter project start date and end date_**
5. _The User clicks 'Report' button and_ **_the system queries all inspections  within the time period for the selected project, and bundles them as a downloadable PDF to the user for download_**
6. **_Include only FINAL inspections_**

![image](https://cloud.githubusercontent.com/assets/4098544/21017421/43603018-bd37-11e6-96ca-97093e9645ec.png)

_Tracking Note: this issue was originally requested as **No. 1.12 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in development

**Comment by linsentp** [comment]
Tested in DEVELOPMENT functionality works great.  
Aesthetically-spacing between search menus are inconsistent 
Name-currently displayed “QA Inspections by Project” should be “QA Project Inspections By Date”

**Comment by vijme** [comment]
UI changed according to specifications

**Comment by linsentp** [comment]
UI and functionality are updated correctly

**Comment by slmessier** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Verified

**Comment by Tad-Daniel** [comment]
Looks good
