### ISSUE TITLE
QA Toolkit - Permit Tab - Listing grid changes

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#283]
**On the _Permit Tab - Permit Grid_: Add a new column titled “Project Description” with values populated using a system check with the following logic:**
1. Check to determine a count of the associated Projects for the applicable Permit.
2. When the count = 1 display the _Project Description_ value in the grid.
3. When the count >1, display the text “Multiple Projects”
![image](https://cloud.githubusercontent.com/assets/23661339/20837644/f280d4fe-b872-11e6-8df9-b4d7ad240e28.png)
Adjust the horizontal space of existing columns as needed to accommodate the new "_Project Description_" column.

_Tracking Note: this issue was originally requested as **No. 1.37 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
Tested in DEVELOPMENT column organized and developed correctly
Name-currently displayed “Project” should be “Project Description”

**Comment by vijme** [comment]
Corrected

**Comment by slmessier** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by Tad-Daniel** [comment]
Looks good.  Please make the title of the column be just "Project" and not "Project Description".  Can the project numbers be hyperlinked back to the project record.

**Comment by vijme** [comment]
Column name changed. Since a permit can have 0 to many project associations, the hyperlink may not be possible with the current design.

**Comment by Tad-Daniel** [comment]
Skip the hyperlink, it's not critical.
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Verified

**Comment by Tad-Daniel** [comment]
Looks good
