### ISSUE TITLE
QA Toolkit - Projects Tab: YC Cert Subtab - New Column in User List: "Enabled/Disabled"

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#284]
### On the _Projects Tab-YC Cert Subtab-User List Grid_: Add a New Column to the grid as described below:

1. **Column Heading Text: _"Enabled/Disabled"**_
2. Values: if the user account is **an active account = "Enabled"** ; when **user account is not active = "Disabled"**
3. Allow users to **sort the 'Grid' on the new _"Enabled/Disabled"_ column**

![image](https://cloud.githubusercontent.com/assets/4098544/21018913/bab7e91c-bd3c-11e6-921d-33febbfdacb4.png)

_Tracking Note: this issue was originally requested as **No. 1.31 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Changed UI to match other column. Let know if needs change

**Comment by linsentp** [comment]
Tested in DEVELOPMENT did not encounter any issues

**Comment by slmessier** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Verified

**Comment by Tad-Daniel** [comment]
Looks good
