### ISSUE TITLE
QA Toolkit - Update Text Label for 'Events & Alerts' tab to "Calendar"

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#285]
### Update the text label for the 'Events & Alerts' tab name to 'Calendar'

![image](https://cloud.githubusercontent.com/assets/23661339/20839873/33890990-b87c-11e6-82a5-b06fd51f306f.png)

_Tracking Note: this issue was originally requested as **No. 1.33 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Completed in dev.

**Comment by linsentp** [comment]
Tested in DEVELOPMENT did not encounter any issues

**Comment by slmessier** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Verified

**Comment by Tad-Daniel** [comment]
Looks good
