### ISSUE TITLE
QA Toolkit - Modifications - Increase character limit in the QA-3 form and the QA Concurrence system to 1000 characters

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#286]
## Expand the character limit to 1000 characters for:

**1. On each of (2) Forms:  _Mod Request / QA3 Form_ & _QA Concurrence Request Form_
2. (2) Fields on each form: _'Nature of Revision'_ and _'Reason of Revision'_
3. Update the Respective PDF Report (QA3) to accommodate 1000 characters of text accordingly**

### **Modification Request / QA-3 form:**
1. QA-3 form is **accessed via project details under the 'Mods' subtab; Click _New Request_ Button.**
2. **Increase character limit** in text boxes illustrated in the graphic below to 1,000 characters
3. **Update the associated UI labels** to reflect the updates that were made
4. **Update the associated _QA3 PDF Report_** to accommodate 1000 characters of text accordingly
![image](https://cloud.githubusercontent.com/assets/23661339/20844619/ba5043fa-b88e-11e6-8dd9-8bafe55bee83.png)

### **QA Concurrence Request form:**
1. QA Concurrence System is **accessed via the project details under the 'QA Concurrence' subtab; Click _New Request_ Button**
2. **Increase the character limit** in the text box illustrated below to 1,000 characters
3. **Update the associated UI labels** to reflect the updates that were made

![image](https://cloud.githubusercontent.com/assets/23661339/20845354/a3073880-b892-11e6-9370-9cfac3eefb2d.png)

_Tracking Note: this issue was originally requested as **No. 1.26 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by rwingender** [comment]
Implemented in Dev.

**Comment by linsentp** [comment]
Tested in DEVELOPMENT did not encounter any issues

**Comment by slmessier** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Verified

**Comment by Tad-Daniel** [comment]
Good
