### ISSUE TITLE
QA Toolkit - Modifications Menu Tab - Add New Search Filter: "Approved By"

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#287]
## **On the Modifications Menu Tab - Add new search filter parameter for  'Approval By'**
![image](https://cloud.githubusercontent.com/assets/4098544/21020317/000e41dc-bd42-11e6-9c32-c06c4af47451.png)
1. The new filter will **_filter returned records according to the division/agency values_** required for the applicable modification.
2. The **_selectable values within the  "_Approved By_"  search filter are to be dynamically populated by with the groups that have been configured to approve each modification on the _Modification Response Page_ (see below)._**
![image](https://cloud.githubusercontent.com/assets/4098544/21020547/eecab878-bd42-11e6-933d-bd1f33c76364.png)
3. Also **include a "blank" entry value as an available option that would display all approvals** regardless of who approved; **this would represent the default setting** for the new filter.

_Tracking Note: this issue was originally requested as **No. 1.18 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by slmessier** [comment]
After discussing the details of the development and implementation strategy for this enhancement internally, **please note the following amendments to the original specifications**:

1. **Update the Text Label for the new Dropdown Menu: _"Division:"_**
2. **The Source of the filtering query will be the _DIVISION_ associations that exist for the modification**, as managed on the Modification Response Page by authorized users (shown below)

![untitled_clipping_010417_111754_am](https://cloud.githubusercontent.com/assets/4098544/21649423/b036ebf8-d26f-11e6-966b-4fe4f0e7d4a1.jpg)

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
Tested in DEVELOPMENT did not encounter any issues

Potential enhancement-should we add a button to link user directly to displayed "Modification" in addition to the button linking them directly to the "Project Details" page

**Comment by slmessier** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Verified

**Comment by Tad-Daniel** [comment]
Looks good
