### ISSUE TITLE
QA Toolkit - Inspections Tab - All Inspection Grids - Hyperlink values in "Project" column to 'Project Details'

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#288]
**Hyperlink interface** – _Update the interface so that each _"Project Description"_ value shown in the associated grids hyperlink into the corresponding project details page_

**Please Apply Update to the 3 Subtabs that Exist within then 'Inspections' Menu tab:**
1. **'Reports' subtab**
 ![image](https://cloud.githubusercontent.com/assets/23661339/20848621/e48174f2-b8a0-11e6-819a-f99ae82dfbb0.png)
2. **'Schedule' subtab**
![image](https://cloud.githubusercontent.com/assets/23661339/20848701/37a09fd2-b8a1-11e6-8315-d813a0983717.png)

3. **'QA2' subtab**
![image](https://cloud.githubusercontent.com/assets/23661339/20848768/8a2bf918-b8a1-11e6-94ac-1f4f15788d33.png)

_Tracking Note: this issue was originally requested as **No. 1.35 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by linsentp** [comment]
Tested in DEVELOPMENT did not encounter any issues

**Comment by slmessier** [comment]
**_Please update the UI to display the _Projects_ (Level 1) tab selected_** after the user has clicked on the hyperlink (see below). Update the target page for each of the (3) hyperlinks: 

**_1. Inspections-Reports
2. Inspections -Schedule
3. Inspections - QA2_**

**_Otherwise, this issue has been successfully validated._**
![image](https://cloud.githubusercontent.com/assets/4098544/21899904/f7a47aae-d8bf-11e6-97d8-211ed0d1eae4.png)

**Comment by vijme** [comment]
Tab selection changed

**Comment by linsentp** [comment]
The tab changes correctly when a project is selected under the "Inspections" > "Reports" tab.  However, the "Schedule" and "QA2" tabs have not been updated.  

Please, replicate what you did with the "Reports" tab and have the "Schedule" and "QA2" tabs redirect to the "Projects" > "Project List" tab when a project is selected.

**Comment by slmessier** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Verified

**Comment by Tad-Daniel** [comment]
Working well.
