### ISSUE TITLE
QA Toolkit - Admin Menu: User Details - Add New Button to Resend Account Info Email

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#289]
### On the Admin-User Details Page: Add a new button that would allow authorized users to resend the existing system email notification for delivering user account information.
   1. When an admin user clicks the new button, the system will send out the notification that is currently sent when a new account is created.
2. The text for the button = "Email Account Info"

![image](https://cloud.githubusercontent.com/assets/4098544/21201321/91333d36-c218-11e6-885a-59b208b06688.png)

_Tracking Note: this issue was originally requested as **No. 3.5 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Is this feature only for QA toolkit or other toolkits as well?

**Comment by Tad-Daniel** [comment]
Just the QA toolkit is fine unless its easier to implement across the board.

**Comment by vijme** [comment]
Its easier to implement across the toolkit.

**Comment by Tad-Daniel** [comment]
Sounds good

**Comment by vijme** [comment]
Implemented in dev.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by slmessier** [comment]
The notification functionality associated with this enhancement request will be validated within the STAGING environment. Otherwise this issue has been validate in the DEVELOPMENT environment and will be labelled as "Ready for Staging".

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
working good
