### ISSUE TITLE
QA Toolkit - Admin User Profile - Notification Subscriptions - Create New Permit Notification Subscription

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#290]
### Create a new notification subscription system to allow users the option to subscribe to all permit email notification (for assigned projects).

**_Within the Admin - User Details Page add a new checkbox to the UI beneath the 'QA User Subscriptions' section_** (see graphic below)
1. **Text Label for checkbox: _"Receive Permit Notifications"_**
2. When a user profile is configured and saved with the new checkbox selected / active, **the user will receive all _permit expiration email notifications_ for the projects to which they are assigned** (See #256 to reference the applicable _Permit Expiration email notifications_)

![image](https://cloud.githubusercontent.com/assets/23661339/21105245/89f48b46-c057-11e6-99ee-7f237d7c77b4.png)

_Tracking Note: this issue was originally requested as **No. 3.6 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by slmessier** [comment]
Additional Specification: Please implement a programming method that restricts users to subscribing to permit notifications exclusively for the "ALL PROJECTS" case. 

If possible / feasible, **_please program the system UI to dynamically display the permit notification checkbox only when the "All Projects" selection has been selected and loaded. The notification checkbox should not appear for all cases otherwise (whenever a distinct project value has been selected.)_**

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by slmessier** [comment]
The notification functionality associated with this enhancement request will be validated within the STAGING environment. Otherwise **_this issue has been validate in the DEVELOPMENT environment and will be labelled as "Ready for Staging"._**

**Comment by slmessier** [comment]
The following 3 cases that trigger permit-based email notifications have been staged for validation. System data has been configured to fire a notification on (3/7) for each distinct case:
1. **_3 months prior to Expiration Date_**
2. **_6 Months prior to Expiration Date_**
3. **_18 months after Issuance Date_**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Seems to be functioning properly
