### ISSUE TITLE
QA Toolkit - QA2 PDF Report - Relocate the Position of Line Item Comments

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#291]
### Please adjust the QA2 PDF Report so that each _Line Item Comment_ appears beneath its associated inspection checklist question.

(currently the report format shows all 'Line Item Comments' within a single section at the bottom of the report)

![image](https://cloud.githubusercontent.com/assets/4098544/21229539/e79d56ec-c2af-11e6-9bab-70538aaa5b9c.png)
![image](https://cloud.githubusercontent.com/assets/4098544/21230045/ac64e016-c2b1-11e6-946c-276ba20d1e98.png)

_Tracking Note: this issue was originally requested as **No. 3.8 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good but now the questions and answers are difficult to distinguish between.  Can the questions on the PDF be bold to set them apart from the answers.

**Comment by vijme** [comment]
Questions are in bold text now.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
