### ISSUE TITLE
QA Toolkit - QA2 PDF Report - Remove Page Break after Page 1

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#292]
### Explore methods to reformat QA2 PDF so that page doesn't break after page 1.
   **Examine the format of the report design to remove the existing page break, potentially by omitting any dead space that appears at the end of the _Comments_ field on page 1, but before page 2**

![image](https://cloud.githubusercontent.com/assets/4098544/21233861/cca9d5b8-c2be-11e6-8f5f-2163eecf5925.png)

_Tracking Note: this issue was originally requested as **No. 3.9 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
