### ISSUE TITLE
QA Toolkit - Inspections - Schedule Tab - Inspections Not Started Grid - Add New "NTP Date" Column

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#293]
### On the _Inspections-Schedule Tab_, please add a new column for the NTP date to the _"Projects Not Started" Grid

Source of Values= Project.NTP date (Notice To Proceed) date
Shrink the horizontal space of the _"Description" Column_ as needed to accommodate

![image](https://cloud.githubusercontent.com/assets/23661339/21109120/a58e446a-c065-11e6-84c6-c0c7395e9fba.png)

_Tracking Note: this issue was originally requested as **No. 3.11 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Should the print also include this information. If so, we may need to revisit the columns as they look tighter now

**Comment by Tad-Daniel** [comment]
This isn't needed on the PDF printout.

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
