### ISSUE TITLE
QA Toolkit - Inspections - QA-1 & QA-2 UI Forms - Update Column Header Fill Color to Enhance Readability

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#294]
## Please update the (2) QA-1 and QA-2 Edit and View forms so that sub-header columns are displayed with a gray fill (as is done currently on the respective PDF outputs for each).

1. **_Update the color of the subheader columns of the QA-1 with a (gray) color_** that matches the associated output pdf (see example below)
2. **_Update the color of every other row within the QA-2 with a (gray) color_**.
3. **_Update for both the Edit screen and the View screens for each of QA1 and QA2_**

## ![image](https://cloud.githubusercontent.com/assets/23661339/21109829/bf39a406-c068-11e6-9a0e-e1c70a7cfe62.png)

![image](https://cloud.githubusercontent.com/assets/23661339/21109793/9bc8f26a-c068-11e6-828d-93da0a894c2c.png)

### QA-2: Highlight every other line for easier readability

![image](https://cloud.githubusercontent.com/assets/23661339/21109981/6b3a6e98-c069-11e6-85c7-1a60540b1b93.png)

_Tracking Note: this issue was originally requested as **No. 3.14 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Just poking around in the dev environment and have a comment.  The QA-2 looks good. The QA-1 has a bit to much grey going on.  Lets use the PDF as the example in the QA-1 so that sections 1 4 and 5 do not have so much grey.

**Comment by vijme** [comment]
QA-1 grey updated as in PDF.

**Comment by linsentp** [comment]
Checked and validated in DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
