### ISSUE TITLE
QA Toolkit - Inspection QA1 Inspection Form - Add Button that Opens A New QA-2 Form

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#296]
## On the _QA-1 Inspection Form_, add a new button that opens the _QA-2 Inspection Form_
   **1.  New 'QA-2' button hyperlinks to a New (Blank) QA-2 Inspection form with a pre-existing association to the corresponding project.**
   **2.  Place the _QA2_ button in two places, next to the existing buttons at the top and bottom**
![image](https://cloud.githubusercontent.com/assets/23661339/21111623/5ab89ec6-c070-11e6-89b1-49595d52c8ba.png)
![image](https://cloud.githubusercontent.com/assets/23661339/21111660/882ae5c6-c070-11e6-9de4-cad256978085.png)

_Tracking Note: this issue was originally requested as **No. 3.16 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
