### ISSUE TITLE
QA Toolkit - QA2 UI Form - Add Ability to Attach Items

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#297]
### Add the capability to add attachments to the QA-2 Form
   1.  **Create the capability to allow attachments of documents to QA-2 inspections using the exact same UI and DB logic as exists currently for QA-1**
2. **Update the QA2 PDF Report functionality to incorporate packaging** associated attachments to the PDF output (re-use existing logic as-needed to control file size, document types, etc.)
![image](https://cloud.githubusercontent.com/assets/4098544/21233584/ae97b33e-c2bd-11e6-9b9b-13684d48b172.png)

_Tracking Note: this issue was originally requested as **No. 3.17 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
The UI does not support the 'EDIT' functionality that is in place for QA1 inspection reports.

![image](https://cloud.githubusercontent.com/assets/23661339/22560812/e9dbd356-e943-11e6-80fe-6dd83e548308.png)

This is allows the user to edit and update specifics to the attachment like 'Type', 'Description', 'Date', and 'Label'.

**Comment by vijme** [comment]
To implement edit functionality, the report has to be created already. If you see in QA-1, we will not be able to attach any documents when the report is created. Only when its saved, we can add documents to the report. Should we do the same in QA-2 as well?

**Comment by slmessier** [comment]
Please replicate the corresponding functionality from the QA-1 directly as-is.

**Comment by vijme** [comment]
Please confirm if print document name needs to be changed for the current inspection date and if attachments needed to be appended to the report as well

**Comment by vijme** [comment]
Added attachments to reports and print document name changed to reflect inspection date as opposed to current date.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks  good
