### ISSUE TITLE
QA Toolkit - New Email Notification System on QA-2 Form - Allow users to optionally send QA2 Form Notifications

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#298]
## Please develop a new notification system attached to the QA-2 Inspection form /workflow
**Create a new notification checkbox on the UI that allows the user to select recipient**s for the notification.
The notification checkbox is to i**nclude all the stakeholders associated to the project as available recipients**.
**All checkboxes are unchecked initially by default.** Authorized **users may optionally check to select the recipients that will receive the system email notification.**

When the user has configured a notification, **the system will**:
1.	_**Package the QA2 Form to PDF and add it as an attachment**_ to the notification.
2.	_**Automatically send the notification to the configured recipients**_.
3.	Please reference the following for configuring the text of the notification:
        **_- Subject: "QA2 Inspection for Project <Proj Number> - <Proj Description>"
        - Text: " A new QA2 Inspection has been added to Project <Proj Number> - <Proj Description>" by <UserName>_**

The email notification is **_triggered when all (3) of the conditions below are met simultaneously_**:
1.	The active user has **_selected one or more recipients for the QA2 notification_**
2.	The QA2 Inspection form has been **_populated with a valid signature_** 
3.	The **_user clicks the Save button_** and saves the QA2 Inspection

### Sample of Revised QA2 UI Page:
![image](https://cloud.githubusercontent.com/assets/4098544/21198967/7a28ad82-c20f-11e6-9252-9e895c8e7038.png)

_Tracking Note: this issue was originally requested as **No. 3.7 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
The notification functionality associated with this enhancement request will be validated within the STAGING environment. Otherwise **_this issue has been validate in the DEVELOPMENT environment and will be labelled as "Ready for Staging"._**

**Comment by slmessier** [comment]
**_Please note the following issue encountered during testing of this enhancement. The notification functionality remains to be validated:_**

### Steps to Replicate
1.	**Navigate to _Inspections_-->_QA2_ --> _edit existing_** _QA2 Inspection Report_
2.	**_Select notification recipients_** from the list of project members 
3.	**_Click Save_**
4.	Erroneous System _**Response**_ after clicking Save:
       a. The recipient **_selected checkbox(es) does not persist after clicking save_**; the system appears to automatically un-check all selections
       b. The red **_“notification sent” message does not appear_** (at the top of the page)
       c. **_Notifications are not received_**

### Screen Cap
![qa2 notification](https://cloud.githubusercontent.com/assets/4098544/23626538/41202cd4-027b-11e7-8da7-78e0f03f25cf.gif)

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in STAGING environment, However it will not be tested by the testing team on PRODUCTION data to avoid erroneously impacting production users and data records._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
looks good
