### ISSUE TITLE
QA Toolkit - Project Details: Mods Subtab - Add "Original Drawing Sheet Number" Value to the Grid

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#300]
## Add the sheet/plan number value to grid listing existing modifications on the _Project Details - Mods Subtab._

1.  On the Modifications Subtab GRID - **add a value that indicates the “Original Drawing Sheet Number” value**
2. **Display the new value using the font currently used to display the modification date** (italics)
3. **Display the new value below the date value** for each row in the grid

![image](https://cloud.githubusercontent.com/assets/23661339/21114429/0d2a64f4-c07b-11e6-8234-29b6aa514d5e.png)

_Tracking Note: this issue was originally requested as **No. 3.27 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good for production but can the word "Sheet: " be added before the actual content to indicate what the information is.

**Comment by vijme** [comment]
Implemented in dev, please check. Since this is a UI change, we can have this implemented in production

**Comment by Tad-Daniel** [comment]
Looks good,  Can this be moved to the current staging environment in time for this weekends update?
Thanks

**Comment by vijme** [comment]
Yes. Implemented in staging as well. Can be included for this release.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
