### ISSUE TITLE
QA Toolkit - Create System for Logging and Viewing Automatic Email Notifications Sent by the Toolkit

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#301]
## Develop new functionality to allow an Administrator to view a running list of system-generated email notifications and their recipients.

1.  Admin-LoginAnalysis Tab - **_Create 2 new subtabs nested beneath “Login Analysis" tab_** (see graphic below)
     - **_"Login Analysis" Subtab_** - (displaying existing content as it does currently)
     - **_"Notification Analysis" Subtab_  “Notification Analysis” displaying a new grid** as described in detail below.
2.  **Create a new UI grid to display the list of system email notifications**:
     -  The **height of each row in the grid should dynamically re-size** to accommodate a variable number of recipients.
     -  **including the following columns & values** of info:
     **a. Subject
     b. Date & Time
     c. Recipient(s)**

![image](https://cloud.githubusercontent.com/assets/4098544/21271407/e898a40a-c388-11e6-8a96-21b833626b46.png)

_Tracking Note: this issue was originally requested as **No. 3.28 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev. Added a column for email status, that will help us to check all email notifications in dev(since it always fails in dev). Also added a search filter. Please let know if they need to be removed or any other changes needed.

**Comment by slmessier** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
