### ISSUE TITLE
QA Toolkit - Project Details: Mods Subtab - Update Mods Grid: Download Attachments

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#302]
**On the _Mods Sub-tab_ of the Project Details Page: Please develop the ability to download attachments from directly within the grid**, according to the details specified below:
1. **Display the Download button for each comment line item; as well as for the Overall Request.**
2. **Bundle all PDFs and prompt for download** appropriately:
     - **Entire Request Bundle for Request**
     - **Comment Line Item Bundle for Comments within Request**
3. **Reuse the Green download button graphic** that is currently used elsewhere in the Toolkit
4.  **Reuse the existing “file not supported” text message** for any file formats that are not compatible with bundling as described

![untitled_clipping_121316_114116_am](https://cloud.githubusercontent.com/assets/4098544/21149298/0f8ba2b8-c129-11e6-8726-a5575242d0df.jpg)

_Tracking Note: this issue was originally requested as **No. 1.21 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by slmessier** [comment]
### UPDATE to SPECIFICATIONS:
**Instead of implementing a new button to download the entire request bundled with all attachments, the existing PDF packaging function will be updated to also include attachments. Users will be able to click the PDF icon to produce this as output, (and thus a new button will not be necessary) **

**Comment by vijme** [comment]
Done

**Comment by linsentp** [comment]
Tested in DEVELOPMENT did not encounter any issue.

**Comment by slmessier** [comment]
**_Please update the functionality associated with the PDF Report Button (highlighted in yellow) to bundle all responses together with the original request PDF. The original request should appear first followed by each response, ordered by date._** 

The system will supply the user with a single report that has packaged all communication associated with the specific modification number.

(Otherwise, the functionality to download a PDF for each response individually -highlighted in pink - has been successfully validated)

![image](https://cloud.githubusercontent.com/assets/4098544/21699608/871558f8-d36a-11e6-9143-f6aca2873ece.png)

**Comment by vijme** [comment]
please check

**Comment by slmessier** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by Tad-Daniel** [comment]
Looks good.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Verified

**Comment by Tad-Daniel** [comment]
Implementation looks good and functions as intended but there is still the issue I emailed about earlier.  When you download the attachment directly the plan markups or notes on the document are there as intended.  When you download the PDF from one of the new download arrows or from the "PDF" package button then the markups do not appear on the PDF that is generated.

**Comment by slmessier** [comment]
**_The issue associated with PDF markup in downloaded bundles has been opened as GH #315_** so that its resolution may be tracked independently of the original enhancement.

**_Since the original enhancement has been otherwise validated above, this issue will be closed at this time._**
