### ISSUE TITLE
QA Toolkit - Mods & QA Concurrence - Add Button Hyperlink to Instructions Standard Form

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#303]
**### Add button to download a PDF form that contains user instruction for the _Modification_ and _QA Concurrence_ workflows.**

**Link the source of the Hyperlink to (2) new records/forms managed from within the _Admin-Standard Forms Menu_.** Administrators may manage future updates to the source document using the Standard Forms functionalities. **All User Profile Roles will have access to the Forms by default.**

_**1. "Modifications Instruction" Standard Form
2. "QA Concurrence Instruction" Standard Form**_

![image](https://cloud.githubusercontent.com/assets/4098544/21151172/80ca889e-c12f-11e6-8f6a-310367f52060.png)

**_Place download button in each of the following pages:_**
**_1. Modification Request (QA3) Form
2. Modification Response Form
3. QA Concurrence Request Form
4. QA Concurrence Response Form
5. Support page as 2 New Tabs for "Mods" & "QA Concurrence"_** (or a suitable abbreviation)

![image](https://cloud.githubusercontent.com/assets/4098544/21149846/dc51d9f6-c12a-11e6-87a9-3e7f83730aaa.png)

_Tracking Note: this issue was originally requested as **No. 1.20 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by slmessier** [comment]
### UPDATE to SPECIFICATIONS:
**In order to manage the forms that support the new hyperlinks using the Standard Forms functionality, the name of the form must be hard-coded as a character string explicitly.** 

Because of this inherent requirement, **note the following additional considerations:**

1. (Admin) **Users must not change the _Name_ string for either of the (2) applicable records within the Standard Forms Grid. If the Name string is changed the hyperlinks will break.** (To account for the scenario of  updating the form, a new file may still be uploaded without changing the name)
2. The Names that will be utilized for each form have been defined below:
   - **(Sample Modification Name)**
   - **(Sample QA Concurrence Name)**

**Comment by vijme** [comment]
The names used are "Modification Instructions" and "QA Concurrence Instructions". The link will appear on the page only if forms are available. For testing, please upload through the admin -> Standard Forms page
Point 5 not implemented because the page will show error screen when document is not available. Can be implemented with a minimal effort. Please confirm if needed.

**Comment by linsentp** [comment]
Tested in DEVELOPMENT.  “Help” button appears and downloads correct document on ‘Modification Request (QA3) Form’ & ‘Modification Response Form’.  “Help” button is NOT displayed on ‘QA Concurrence Request Form’ or ‘QA Concurrence Response Form’

**Comment by vijme** [comment]
the button is displayed only when the document named "QA Concurrence Instructions" is available in the admin -> standard forms page. Since the "Modification Instruction" form was available, we could see the button in those pages.

**Comment by linsentp** [comment]
Tested in DEVELOPMENT column organized and developed correctly

**Comment by slmessier** [comment]
**_This issue has been validated by the project team in the Development Environment_** and is being assigned to stakeholders for confirmation.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by Tad-Daniel** [comment]
Looks good.  Could the button be moved an inch or two to the left just to get it away from the right border some.

**Comment by slmessier** [comment]
**_Please update the layout of the UI to shift the display location of the Help button location to the left, so that it is offset from the right edge of the page._**

**Comment by vijme** [comment]
Added some spacing to the right, please check

**Comment by slmessier** [comment]
Confirmed in DEVELOPMENT. 

Tad - please validate and confirm.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the **STAGING** environment

**Comment by Tad-Daniel** [comment]
Verified

**Comment by Tad-Daniel** [comment]
Looks good
