### ISSUE TITLE
QA Toolkit - QA 1 Inspection PDF - Update Syntax to Produce Filename

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#304]
### Please update the syntax utilized to produce the filename for the QA1 Inspection PDF Report to incorporate the _Inspection Date_ value.

**_Please update the logic used to formulate the file name text string to reference the Inspection Date instead of the current System Date._**

**Ex: _"QAInsp_HA3485370_20161214.pdf"_**
![image](https://cloud.githubusercontent.com/assets/4098544/21228849/5dc42a38-c2ad-11e6-900d-295b28438c5a.png)

_Tracking Note: this issue was originally requested as **No. 3.10 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
_The QA1 PDF report is still displaying the System Date instead of the Date of Inspection when generated by the toolkit._  Please, update syntax to **replace the System Date with the Date of Inspection in the filename text string.**

![image](https://cloud.githubusercontent.com/assets/23661339/22651065/a87414d2-ec4f-11e6-97cc-df116d4c098c.png)

**Comment by vijme** [comment]
Fixed now.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
