### ISSUE TITLE
QA Toolkit - QA Toolkit Home Page - Add Hyperlinks to Reference Docs From Standard Forms

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#305]
### Please update the QA Toolkit Home Page UI to include a section that lists Hyperlinks to Reference Documents.
1. The **_source of the hyperlink list is the Admin-Standard Forms Menu_**
   - **_All Standard Forms where "Reviewer" and "Power Reviewer" are checked / selected_** are to be displayed as Hyperlinks on the Home Page
2. The **_syntax of the Hyperlink should be "[Name] - [File]"_**   (**Ex - _"QA-2 - QA-2 Final.pdf"_**)
3. The User Interface layout from **_the IEM & MDE Toolkits may be a logical starting point_** to leverage for building out the required capability.

![image](https://cloud.githubusercontent.com/assets/4098544/21274187/db7c07ba-c394-11e6-859d-1303ea3dfc3f.png)

_Tracking Note: this issue was originally requested as **No. 3.1 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev. PDFs will be opened in new browser tab, other formats are saved.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
See mockup below for reference or page layout.  The reference docs section of the page does not have to exactly as shown but I would like to have a table layout.  Also ensure the documents that show are the ones assigned to the contractor role.

This mockup includes the buttons for the accounts request page currently under development.

![new login page](https://cloud.githubusercontent.com/assets/7913678/23554987/2e7a1776-fff5-11e6-8fd8-f510a8ced15b.png)

**Comment by vijme** [comment]
Dev updated with changes. Please check

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
this looks good but can the documents be sorted alphabetically,  the ordering seems random to me.

**Comment by slmessier** [comment]
Sure we can accomplish re-ordering the list alphabetically. That enhancement has been logged as a new issue in GitHub (as #313 ) and queued for development.

Since this issue (305) has been otherwise confirmed, it can be considered complete and will be closed at this time.
