### ISSUE TITLE
MDE Toolkit – Permit Reviews – Add “Awaiting emergency JPA Submittal” option to "Permit Review" SHA Action Items

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#306]
### Enhance the tracking capabilities of the system to allow users to track _"Emergency JPA Submittal"_ as an _Action Item_ for _Permit Reviews_

**_Update UI and Database to implement the following (2) enhancements_**
1. (For Permit Reviewer and Permit Manager Roles) **_Permit Reviews Menu_: Create a new Search Filter value for  _Action Item_ . New Value =  _"SHA - Awaiting Emergency JPA Submittal"_**
![image](https://cloud.githubusercontent.com/assets/23661339/22260297/ba73dc3a-e236-11e6-9fcf-d0980210c88d.png)

2. (For Permit Reviewer and Permit Manager Roles) **_Project Review Details Page: Update SHA Action Items Table to include a new row to represent the "Awaiting Emergency JPA Submittal" scenario_**
    - **_Update the Read-Only Region the system displays directly beneath the page title_**:
![image](https://cloud.githubusercontent.com/assets/23661339/22260746/5199ad46-e238-11e6-96e6-efe4ba07546b.png)
    - **_Update the Editable Region the system displays within the "Comment Log" nested lower on the page_**:
![image](https://cloud.githubusercontent.com/assets/23661339/22261053/79d92e5c-e239-11e6-8bc8-a1c635b09e2c.png)

**Comment by slmessier** [comment]
This issue has been validated by stakeholders in the STAGING environment (via email on 2/9 from Cheryl Jordon).

**This issue will be labelled as _"Ready for Production"_. Please deploy in production environment at a suitable time**

**Comment by slmessier** [comment]
**_This issue has been validated and confirmed by stakeholders via email (see below) and will be closed_**

From: Cheryl Jordon (SHA) [mailto:CJordon@sha.state.md.us] 
Sent: Tuesday, February 21, 2017 3:29 PM
To: Scott Messier <Scott.Messier@kci.com>
Subject: FW: [kcigeospatial/sha_oed_issues] MDE Toolkit – Permit Reviews – Add “Awaiting emergency JPA Submittal” option to Permit Review Action Items (#306)

Thank you Scott!

From: Scott Messier [mailto:Scott.Messier@kci.com] 
Sent: Saturday, February 18, 2017 1:21 PM
To: Cheryl Jordon (SHA) <CJordon@sha.state.md.us>
Subject: RE: [kcigeospatial/sha_oed_issues] MDE Toolkit – Permit Reviews – Add “Awaiting emergency JPA Submittal” option to Permit Review Action Items (#306)

Hi Cheryl,
The updates to the MDE Toolkit to accommodate the “Awaiting JPA Submittal” are now available in production. 
Please notify users of the update as necessary.
Thanks and have a good weekend!
