### ISSUE TITLE
QA Toolkit - SWM as-built Menu - Make SWM as-built menu available to ALL user profiles

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#307]
### Make the "SWM as-built" Level Two Menu **beneath the "Projects" tab** visible for every user profile.

![image](https://cloud.githubusercontent.com/assets/23661339/23076633/416ccc16-f50f-11e6-907c-813cfb025261.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
