### ISSUE TITLE
QA Toolkit - Admin Menu - User Edit - Allow 'Plan Review' group membership capability to be an SWM approver

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#308]
### On the _User Edit_ page under the "Admin" Menu allow members of 'Plan Review' group to have full SWM approval permissions.

![image](https://cloud.githubusercontent.com/assets/23661339/23077044/e724d170-f510-11e6-8969-c918654a5168.png)

**Comment by slmessier** [comment]
**Please update the system logic associated with validating the _"SWM Approver Checkbox"_:**
**When the _"SWM Approver Checkbox"_ is selected, the user must also be configured as a member of:
-_Plan Review_ (must also be selected)
OR
-_Hydraulics Division_ (must also be selected)**

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
