### ISSUE TITLE
QA Toolkit - SWM As-Built Submittal Request Form - Update the UI to reflect modified 'Approved' button and new form text 

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#309]
## On the _SWM As-Built Submittal Request Form_ add a new 'Approved' button and update form text

1. **Update the text in the box referenced in the graphic below** to the following text:
![image](https://cloud.githubusercontent.com/assets/23661339/23079263/2c8ae2fa-f51a-11e6-82fb-1f3058ddf4b1.png)

2. Change the existing **'HHD'** button currently on the form to the new **'Approved'** button indicated in the graphic below.
   - Use the attached .png button graphic below in your update.
![approved](https://cloud.githubusercontent.com/assets/23661339/23137726/97892ab8-f771-11e6-912b-4221bdfb945a.png)

![image](https://cloud.githubusercontent.com/assets/23661339/23079443/f0662658-f51a-11e6-8401-1ea40f59862b.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
