### ISSUE TITLE
QA Toolkit - Add multiple buttons across QA Toolkit UI

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#310]
### _Update (7) buttons_ across entire QA Toolkit UI using the new graphic icons on corresponding screen grabs below as a source
- Use the attached .png button files below. 

1.  **Email Active Users** – User List
![emailusers](https://cloud.githubusercontent.com/assets/23661339/23137593/c9d61d38-f770-11e6-84ee-7bfbbddf3829.png)
2.  **Print List** – User List
![printlist](https://cloud.githubusercontent.com/assets/23661339/23137595/c9d720ca-f770-11e6-9aeb-afee05fef20e.png)
3.  **New User** – User List
![newuser](https://cloud.githubusercontent.com/assets/23661339/23137590/c9d30fda-f770-11e6-9bb3-61cf10ddf215.png)

![image](https://cloud.githubusercontent.com/assets/23661339/23127840/8677f4a6-f74a-11e6-8330-71eb8720d68f.png)

4.  **Update** – User Details; Replace Both (2) 'Save' Buttons
![update](https://cloud.githubusercontent.com/assets/23661339/23137594/c9d693e4-f770-11e6-9a21-a7aa337978a5.png)
5.  **Load** – User Details
![load](https://cloud.githubusercontent.com/assets/23661339/23137591/c9d32754-f770-11e6-894f-0467ffce1a10.png)
6.  **Email Account Info** – User Details
![accountinfo](https://cloud.githubusercontent.com/assets/23661339/23137589/c9cda5d6-f770-11e6-94d0-7779857282d1.png)
7.  **Filter** – User Details
![filter](https://cloud.githubusercontent.com/assets/23661339/23137592/c9d437ca-f770-11e6-86a5-ffa11b5749e3.png)

![image](https://cloud.githubusercontent.com/assets/23661339/23128464/028f166c-f74d-11e6-8127-e1cf8fbd07d9.png)
![image](https://cloud.githubusercontent.com/assets/23661339/23128716/ef6e1e10-f74d-11e6-9fad-8ae0399df24d.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**'CLEAR'** & **'CLOSE'** buttons were updated to match graphics found elsewhere in the QA Toolkit, as well.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by slmessier** [comment]
_Enhancement has been validated by testing team in PRODUCTION environment._

**_Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
