### ISSUE TITLE
QA Toolkit - Project Details: SWM SubMenu - Comment Sort Order

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#311]
**_Please update the system to display the order of in the SWM response comments in descending order from top (most recent comment) to bottom (first comment)._** This is consistent with the respective sorting of Mods & QA Concurrence tracking workflows.  

![image](https://cloud.githubusercontent.com/assets/4098544/23464986/e104c4a0-fe64-11e6-9793-b3b9305d3ef6.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by slmessier** [comment]
**_Enhancement has been validated by testing team in PRODUCTION environment.

Tad - please test / confirm and close where applicable._**

**Comment by Tad-Daniel** [comment]
Looks good
