### ISSUE TITLE
QA Toolkit - Home Page - Order List of Doc Hyperlinks Alphabetically

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#313]
**_Please update the list of document hyperlinks on the home page to be listed in alphabetical order._** (See graphics below)

**_ScreenCap:_**
![image](https://cloud.githubusercontent.com/assets/4098544/23999572/35dc3a0a-0a2f-11e7-9437-59eaca75e507.png)

**_Mockup / Intended Design:_**
![image](https://cloud.githubusercontent.com/assets/4098544/23999641/61066048-0a2f-11e7-8c4a-7f2bad1e0a76.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
**_This issue has been successfully validated by the project team and confirmed by stakeholders in the Development Environment_**.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good for production

**Comment by Tad-Daniel** [comment]
Looks good. Item complete
