### ISSUE TITLE
QA Toolkit - Develop New Functionality: New Account Request Workflow

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#314]
### Objective
_Develop new system functionality that allows users to request system access from authorized QA Toolkit Administrators, and stores basic identity information submitted with the request to support the approval review process._

### Fundamental stages of workflow:
1.	**_Outside (public) users submit request and supporting information_**
2.	**_QA Toolkit system stores the request and supporting information within the system._**
3.	**_Administrative / authorized users review the submitted information and approve or reject the request as an Admin function._**
4.	**_The system automatically executes on of two processes based on the Admin / Approval outcome:_**
        - **_(Approved) Create the New User Account and then delete all intermediately stored data_**
             **OR**
        - **_(Rejected) Delete all intermediately stored data (when Rejected)_**

### Workflow Mockup PDF
[NewAccountRequest_Workflow_V1.0_20170314.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/858852/NewAccountRequest_Workflow_V1.0_20170314.pdf)

### UI / System Business Logic
**Request Page:**
![image](https://cloud.githubusercontent.com/assets/4098544/24158021/80b40318-0e31-11e7-9e49-99e618ca84fb.png)

**Approval Page:**
![image](https://cloud.githubusercontent.com/assets/4098544/24158059/98ecdf40-0e31-11e7-82af-28fc551e10bb.png)

**Data Mapping:**
![image](https://cloud.githubusercontent.com/assets/4098544/24158082/ab8b8bb0-0e31-11e7-864e-d6791a2612d5.png)

_Tracking Note: this issue was originally requested as **No's. 2.2 & 2.3 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by slmessier** [comment]
The base workflow looks good with one additional update if feasible (below):

**_An approved subscription configuration is to applied to the "ALL PROJECTS" case exclusively from the Admin-User Details Subscriptions._**

Currently the system saves the configuration with an association to the (1) selected project. However, the intended design is that the configuration applies to the ALL PROJECTS (base) case. Please update accordingly if possible.

![image](https://cloud.githubusercontent.com/assets/4098544/24409472/4beb4e62-139e-11e7-8fae-53b08abfee4b.png)

**Comment by vijme** [comment]
Updated in dev

**Comment by slmessier** [comment]
**_The enhancement request to update subscription configuration to  "ALL PROJECTS" has been successully tested and validated._**

**Comment by slmessier** [comment]
As a result of completing full regression testing on the new account request workflow, **_(3) additional modifications are requested for inclusion into this release. Please assess each, and if feasible begin development & implementation._** The details for enhancement are described in the material that follows. 

**_1. Admin-Analysis-Approve Accounts: Add Submit Date Column
2. Update system handling for case of a duplicated email address
3. Admin-Analysis-Approve Account: Update UI Logic for Company Dropdown_**

---------------------------

# 1 - Admin-Analysis-Approve Accounts: Add Submit Date Column
### Case: 
On the Approve Accounts page, examining & sorting the grid of pending requests.
### Instruction: 
If the supporting date information can be retrieve from the database with minimal reconfiguration, **_please add a new column to the grid to represent the request’s “submit date”. Sort the grid by this value (descending) by default, oldest (top) to newest (bottom)._**


------------------------------------------------
# 2 - Update system handling for case of a duplicated email address
### Case: 
When a request is submitted with an email address value that has already been submitted within an existing, pending request. 
### To replicate:
Complete two iterations of the workflow to submit a request using an identical email address value in each request.
### Current System Response:
Currently the system returns an error message that indicates a “Duplicate Request”
### Instruction: 
please update the text of the error message to “Error: Email associated with pending request”
### Graphic Support:
![image](https://cloud.githubusercontent.com/assets/4098544/24509063/58e56986-1533-11e7-9e98-fbd76a66796a.png)

-------------------------------------------------------------------------------------------------

# 3 - Admin-Analysis-Approve Account: Update UI Logic for Company Dropdown
### Case: 
For the case when the requestor has entered a new company value, the workflow has a gap in which the approver may de-select the “New” checkbox to supersede the request and select from the existing list of available company values. 
### Current System Response:
In the current release the company input field remains as a free text field, and ideally should dynamically change to a dropdown picklist to optimally support the most efficient selection process.
### Instruction: 
Please update the system to dynamically change the Company input field to a dropdown value when the “New” checkbox is not selected. Please implement enforcement to ensure the approver user has selected a valid company value when the “New” checkbox is not selected.
### Graphic Support:
![image](https://cloud.githubusercontent.com/assets/4098544/24509185/b92cf93a-1533-11e7-9790-b9b1870f1f40.png)

**Comment by vijme** [comment]
Implemented in dev, please check

**Comment by Tad-Daniel** [comment]
Appears to be working correctly.  Should the "New user" hyperlink be more clearly shown on the login page.  What are your thoughts of using the current account button with a short blub of text.  see below.

![new login page](https://cloud.githubusercontent.com/assets/7913678/25009496/d47fe916-2034-11e7-9403-0c183c60c4e0.png)

**Comment by slmessier** [comment]
This could require a more complex level of updating to the layout for the QA Toolkit Homepage. Currently the "Request Account" button exists on the OED Toolkit Home Page which references its own distinct layout.

Also, we'd need additional consideration for:
1. Is the "Links" section that exists currently on QA Homepage to be removed completely? (Theyre not shown in your mockup)
2. How would the existing "Request Button" functionality on the OED Home Page be impacted? (Should a new form be created that excludes the option for QA Toolkit request?)

**_Could we move forward in the near term to get the functionality into PROD, and perhaps make a simpler change that promote awareness to the new functionality? ....perhaps update the text and font size of the hyperlink?_** We could cycle back with a future enhancement to re-work the aesthetic layout details and update any forms as an exclusive work assignment. **_Please advise._**

**Comment by Tad-Daniel** [comment]
Good points.  Yes I agree with your approach.

**Comment by slmessier** [comment]
**_This issue has been successfully validated by the project team and confirmed by stakeholders in the Development Environment_**.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good for production

**Comment by Tad-Daniel** [comment]
Looks good. Item complete
