### ISSUE TITLE
QA Toolkit - Patch PDF Bundling Functionality to Allow for Persisting PDF Markup

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#315]
An existing limitation in the toolkit's underlying PDF bundling technology has restricted users of the toolkit from saving PDF Markup within bundled packages that the system issues as downloadable output (as has been reported in Issue #302).

The development team will research and develop a potential method to address this restriction by replacing the underlying PDF technology with an alternative platform. 

**_The objective of this task will be to replicate all existing PDF bundling and download technology offered by the system using the updated software platform. Additionally, PDF markup will persist in PDF's bundles that the system outputs._**

**_Previously closed GH issue #251 should be tested in its entirety during the testing phase to fully validate the functionality on the updated platform._**

**Comment by vijme** [comment]
Updated in development.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Appears to be working properly

**Comment by slmessier** [comment]
**_This issue has been successfully validated by the project team and confirmed by stakeholders in the Development Environment_**.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good for production

**Comment by Tad-Daniel** [comment]
Working correctly. Item complete
