### ISSUE TITLE
QA Toolkit - Develop New Functionality: Project Assignment Request Workflow

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#316]
### Objective
_Develop new system functionality that allows existing users to request a new project assignment from authorized QA Toolkit Administrators. The workflow stores information associated with the request and then displays it - with project and user information as context -  to support the approval review process._

### Fundamental stages of workflow:
1.	**_Existing users use the 'Settings' menu to select the applicable project and then submit the assignment request_**
2.	**_QA Toolkit system stores the request and supporting information within the system._**
3.	**_Administrative / authorized users review the submitted information and approve or reject the request as an Admin function._**
4.	**_The system automatically executes one of two processes based on the Admin / Approval outcome:_**
        - **_(Approved) Associate the user account to the applicable project as a 'Stakeholder'_**
             **OR**
        - **_(Rejected) Discard all intermediately stored data (when Rejected)_**

### Workflow Mockup PDF
[NewProjAssignmentRequest_V1.0_20170331.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/886740/NewProjAssignmentRequest_V1.0_20170331.pdf)

### UI Logic
**Updated 'Settings' Menu:**
![image](https://cloud.githubusercontent.com/assets/4098544/24566957/a0c7e822-1629-11e7-8798-10c34a10eb38.png)

**Approval List Page:**
![image](https://cloud.githubusercontent.com/assets/4098544/24566986/c10aa6b0-1629-11e7-8c3a-ac41e5ca88d3.png)

**Approval Page:**
![image](https://cloud.githubusercontent.com/assets/4098544/24567000/ca19f71a-1629-11e7-97b0-f94d6e0220e6.png)
![image](https://cloud.githubusercontent.com/assets/4098544/24567022/df932c10-1629-11e7-814d-8607895ed7c7.png)

_Tracking Note: this issue was originally requested as **No's. 2.2 & 2.3 within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
**_Please add logic to the Project Assignment "Update Button" to add an additional validation check against existing user/project association in the system._**

**_When the user selects a project value to which a pre-existing association exists, the system will deny the request and instead display a message as indication._**

![image](https://cloud.githubusercontent.com/assets/4098544/24720455/315cea88-1a0b-11e7-9e2c-21cd5712fa8e.png)


![image](https://cloud.githubusercontent.com/assets/4098544/24720401/0f256d50-1a0b-11e7-9af1-4a5d4ad174d8.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by Tad-Daniel** [comment]
Appears to be working correctly. Just want to verify that the list of projects to choose from is only open projects and does not include closed projects

**Comment by vijme** [comment]
Fixed to list only open projects

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
**_This issue has been successfully validated by the project team and confirmed by stakeholders in the Development Environment_**.

**_This issue has been updated to status =  "Ready for Staging"_**

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the STAGING environment

**Comment by Tad-Daniel** [comment]
Looks good for production

**Comment by Tad-Daniel** [comment]
Looks good. Item complete
