### ISSUE TITLE
QA Toolkit - Develop New PDF Report - Modifications Summary Report

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#317]
## Please develop a new PDF report - "Modifications Summary" using the specification outlined below
Reference PDF wireframe as needed:
[4.23 - NewCharts&ReportsPDF.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/965383/4.23.-.NewCharts.ReportsPDF.pdf)

### Report Launch

1. The new report will be **_launched from a new, dedicated region on the _BP/SS - Reports_ Menu that is labelled _"Modifications Summary"_ (2A in the graphic below)_**
2. **_User will be required to enter a Start date and End Date value_**
3. The system will pass the **_date range as a parameter into the report query & output_**

![image](https://cloud.githubusercontent.com/assets/4098544/25534217/20c48fde-2c01-11e7-9a29-e1af98dca79b.png)

### Report Mockup Example
1. **Additional Specification Details in graphic below**

![image](https://cloud.githubusercontent.com/assets/4098544/25544658/6c92da4c-2c29-11e7-9b06-a1e92ae1a8bc.png)

_Tracking Note: this issue was originally requested as **No. 4.23 - A thru E within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev. Minor layout changed, please advise if needed changes.

**Comment by linsentp** [comment]
- Charts are oriented in a different fashion – **_This is ok_**

- Create error message prompting user to select end date (now it generates report with the current date as the end date if the text box is left blank)

- Modifications Approval Time Summary chart – Data that is reported is correct but the way it is being displayed does not match the sample report 
          1. Not displaying percentage symbol
          2. Not being rounded to 2 decimal places

- Modification Approval Time charts separated by year – Each quarter is not displayed in every chart and graph 
          1. Time To Approve Modification Request (Days) – Chart does not display percentages in parenthesis underneath the permit count
          2. Average Approval Time (Days) – Data is not being rounded to two decimal points like it shows in sample report

**Comment by slmessier** [comment]
**_Please re-test using the following additional specification established during  an on-site meeting (5/16):_**

As Per Tad's guidance decided during meeting at SHA HQ 5/16 10 AM:
1. (The modification from the original layout has been approved)

2. Enforcement of End date as **required user input is not necessary, only Start Date will be required.** The system will default to include all inspections to-date when user input is not provided**

3. (no additional specification)

4. Charts will be represented distinctly for the quarters associated with the data results rwturned by the reporting period query. **_When no data exists for a quarter, it may be excluded_** from display in the output set of charts entirely.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
If there is no data for a given year system currently displays a blank page with no graphs or data.  If there is no data for a given year **_do not display anything_** but instead start displaying charts at the first instance of data recorded.

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by Tad-Daniel** [comment]
I completed a detailed review of the information and found the calculation and naming issues shown in the graphic.

![graphs](https://user-images.githubusercontent.com/7913678/28218858-db46e3d0-6887-11e7-81ef-b1a8fdb63724.png)

**Comment by vijme** [comment]
Implemented the following changes:
1. Have included the modifications that have status as "Approved" only.
**(Need confirmation from Tad:  
a. Currently days difference calculated as approval_date - request_date, i have changed it to approval_date - rec_qa_date, please let me know if otherwise.
b. when i run the updated query in pdn database, i get the percentage as  1 day or less - 54%, 2-14 days -33%, >14 days - 13% , that is slightly different from your provided values.  Please let  know how those percentages were derived. )**

2. Text changed from "1-14 days" to "2-14 days".

3. Due to crystal reports limitation, its not possible to line up bar graphs from highest to lowest dynamically based on values. However, I have ordered statically to show <=1 day, 2-14 days and >14 days in order . **Please let me know if that works.**

4. Same changes were made to the other two graphs.

**Comment by Tad-Daniel** [comment]
My percentages were calculated based on current info in production and they were rough numbers. If something has been approved since I ran the numbers that may change the percentages.  What you have done above is correct.   It all sounds good with the graphic changes.

**Comment by HollySchuelerKCI** [comment]
The issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
appears to function correctly but our data is so odd in the staging environment that checking for accuracy is difficult.  I can do a final check in production.

**Comment by Tad-Daniel** [comment]
Appears correct. Issue closed
