### ISSUE TITLE
QA Toolkit - Develop New PDF Report - ESC / SWM Grade Summary Report

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#318]
## Please develop a new PDF report - "ESC / SWM Grade Summary" using the specification outlined below
Reference PDF wireframe as needed:
[4.23 - NewCharts&ReportsPDF.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/965383/4.23.-.NewCharts.ReportsPDF.pdf)
### Report Launch

1. The new report will be **_launched from a new, dedicated region on the _BP/SS - Reports_ Menu that is labelled _"ESC / SWM Grade Summary"_ (2B in the graphic below)_**
2. **_User will be required to enter a Start date and End Date value_**
3. The system will pass the **_date range as a parameter into the report query & output_**

![image](https://cloud.githubusercontent.com/assets/4098544/25534217/20c48fde-2c01-11e7-9a29-e1af98dca79b.png)

### Report Mockup Example
1. **_Final Inspections Only_** / Exclude Skipped Inspections

![image](https://cloud.githubusercontent.com/assets/4098544/25534306/5d1bcd30-2c01-11e7-87da-2c91526a6a65.png)

_Tracking Note: this issue was originally requested as **No. 4.23 - F within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
The percentage compliance is calculated as (rating A + rating B + rating C)/Total Ratings, please correct if wrong. Implemented in dev.

**Comment by linsentp** [comment]
- Create error message to prompt user to select start & end dates

- See sample report for details on chart layout:
        1. Graph “title row” should be shaded for easier readability
        2. Create empty and shaded row between the district data and the statewide data (sum of all columns)

**Comment by vijme** [comment]
Start date and end date not needed. System defaults all inspections till date when not provided.
Layout changed per spec.

**Comment by slmessier** [comment]
As Per Tad's guidance decided during meeting at SHA HQ 5/16 10 AM:
1. Enforcement of Start date and end date as **required user input is not necessary. The system will default to include all inspections to-date when user input is not provided**
2. **3 Updates to Layout:**
    - address existing cutoff of right margin
    - Graph “title row” should be shaded for easier readability
     - Create empty and shaded row between the district data and the statewide data (sum of all columns)

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
I looked at the numbers and noticed a discrepancy of some sort.  In comparing the PDF output to the inspections grid it appears that the items outlined in green below are correct but the numbers in the red outline are off to varying degrees.

![untitled](https://user-images.githubusercontent.com/7913678/28330357-47563ea0-6bbb-11e7-9ff5-f22dae889c8b.png)

**Comment by vijme** [comment]
I Apologize, the total inspections had included skipped inspections along with graded and ungraded final inspections. I have fixed that in dev.

**Comment by slmessier** [comment]
Because this report has already been deployed in production, I am closing this issue and logging a new issue for revising the report logic to exclude the skipped inspections as Viji has stated above.
