### ISSUE TITLE
QA Toolkit - Project Details Accessibility - Update Access for Specified User Profiles

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#319]
### Scope & Anticipated Outcome
Please update the accessibility of the Project Details Page (and Project List Grid) according to the specifications described below. The specifications associated with this request were derived from GH #200 , and then updated for currency.

**As at outcome of the enhancement, any user - regardless of profile type - will:**
**1.  Click the "Edit" icon exclusively for accessing Project Details information. 
2. The "View" icon will be rendered obsolete and is to be removed from the associated grid** 
![image](https://cloud.githubusercontent.com/assets/4098544/25639203/f6004be8-2f58-11e7-8ef5-123a5115935b.png)

### Summary of Access Capabilities - Before & After
The graphics below represent a current, and enhanced version of summarized accessibility to the Project Details page for each system user profile.
![image](https://cloud.githubusercontent.com/assets/4098544/25639500/1a9fffd8-2f5a-11e7-8418-2226a16f1e79.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25639525/2e8090e4-2f5a-11e7-87e1-0fa4032103d6.png)

### Detailed Specification (Per SubMenu)
The material below lists the specific updates that are required to enhance each SubMenu that comprises the Project Details Page, and does so for each applicable User Profile role.
![image](https://cloud.githubusercontent.com/assets/4098544/25639875/91a8e904-2f5b-11e7-95df-0a1a4ad6bc30.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25640224/c80d0e7a-2f5c-11e7-915d-a3ec0dab802c.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25639966/dc0d2320-2f5b-11e7-9585-27c5855e7bc6.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25639996/f133f4f4-2f5b-11e7-8efd-0143be0d67b6.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25640014/00ad0d62-2f5c-11e7-99cf-5df87cc3fe6f.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25640044/170fdd64-2f5c-11e7-87f6-9556eaf1c2f6.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25640062/225f4eac-2f5c-11e7-8979-d9ba5b0b1288.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25640071/3148030a-2f5c-11e7-8a74-94134f6b04c6.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25640084/3c96f36a-2f5c-11e7-9c57-411d68dfd3e8.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25640092/462d43ca-2f5c-11e7-8447-e0d6dca805ad.png)
![image](https://cloud.githubusercontent.com/assets/4098544/25640103/504c65fc-2f5c-11e7-93e6-ad4351a934ba.png)

_Tracking Note: this issue was originally requested as **No. 5.4 (a & b) within the Task 11 Scope of Work Agreement**, and as referenced within GH issue #280 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
‘View Project’ button is still present in _Project List_ grid

**Comment by vijme** [comment]
Removed the view project button

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Does the "SAVE" button have to be present for all of the different roles?

**Comment by vijme** [comment]
Some subtabs like "Resources", "Incentives" depend on this SAVE button. In case later we need to show these subtabs for specific roles, it will just be a database configuration without any code change.  Please advise if they need to be removed.

**Comment by Tad-Daniel** [comment]
OK,, lets leave the "SAVE" button as I don't see the harm if they click it; appears to not effect the data.

**Observations from testing the current dev. environment.**

- The roles of inspector, reviewer and project engineer can see projects they are not assigned to in the SWM grid and the QA2 grid. They should only see assigned projects
- The role of contractor can see projects they are not assigned to in the SWM grid. Same as above.
- Limit the ability of the inspector and project engineer so they can only edit or delete file they added themselves,  if this requires extensive work then simply remove they editing and deleting ability.

**Comment by vijme** [comment]
lets leave the "SAVE" button as I don't see the harm if they click it; appears to not effect the data 
       **_SAVE button left as is._**

Ensure all users can see the communications button communicate, looks like it got removed or hidden.
       _**Project List page -> Communication button visible to all users**_

Limit the ability of the inspector and project engineer so they can only edit or delete file they added themselves, if this requires extensive work then simply remove they editing and deleting ability.
_**Project Edit -> Documents sub tab -> Currently, We do not store the user information for the uploaded documents. For project engineer and inspector roles, edit and delete removed, but "Add document link" is still available.**_ 

The roles of inspector, reviewer and project engineer can see projects they are not assigned to in the SWM grid and the QA2 grid. They should only see assigned projects
Projects->SWM As-Built  & Inspections->QA2:
 **_I'm slightly off track in this requirement.  Referring to Modifications listing tab, that shows only assigned projects mods, was for all user roles. I wanted to double check if you meant the same or you wanted inspector, reviewer and project engineer roles to be able to see only assigned projects swms and other roles to be able to see all projects swm._** 

The role of contractor can see projects they are not assigned to in the SWM grid. Same as above.
_**Same as above**_

**Comment by Tad-Daniel** [comment]
Yes to All

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
This issue (twith updated specification) has been (re)tested and validated by the project team in the DEVELOPMENT environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
I checked all profiles and everything looks good.  The only outstanding issue I saw was the Project Engineer profile is not showing the communication button 
![comm](https://user-images.githubusercontent.com/7913678/26932982-3b62140e-4c33-11e7-89cd-5e4485dfe106.png)
If this can be addressed before the push that would be great but if not then do not let it impact tohe rollout,  this can be corrected at a later date.

**Comment by vijme** [comment]
Nice catch. The user should be a non-admin project engineer to see the issue.  This issue has been fixed in dev and staging, please check.

**Comment by Tad-Daniel** [comment]
Looks good,  thanks

**Comment by Tad-Daniel** [comment]
I believe we have all of this correct now.  Looks good
