### ISSUE TITLE
(13.A.1) - QA Toolkit - Update Modification Email Notification

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#320]
**Update Modification Email Notification**
_(Launch Point = automatically triggered based on modification status)_

**Enhancement Specification(s):**
1. Add a value to body of email to represent the division designation 
2. Label the region on notification as “Under Review by:” 
3. List all values in cases w. more than one; Values may be listed as comma separated values
4. Source of Division Values = Approval Permissions - Group Membership
       - Abbreviations / acronym values (EPD, QA, etc) can be displayed as the text values
![image](https://cloud.githubusercontent.com/assets/4098544/26421098/ccbe7430-4092-11e7-9db1-7b95baebbf62.png)

**Enhancement Mockup:**
![image](https://cloud.githubusercontent.com/assets/4098544/26457843/858fa4d2-413f-11e7-8305-607a2f308841.png)

_Tracking Note: this issue was originally requested as **No. 13.A.1 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by vijme** [comment]
Placed as a fourth line after review status since Project Description can grow. See sample below

![image](https://cloud.githubusercontent.com/assets/6668314/26504546/0091e9c8-4213-11e7-999a-30cd05ff537d.png)

**Comment by slmessier** [comment]
**The output for this issue has been validated by the project team in DEVELOPMENT**, and will be assigned to Stakeholders to confirm.

**Notification itself will be tested in full within the STAGING release**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
The output for this issue has been validated by the project team in STAGING environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good
