### ISSUE TITLE
(13.A.2) - QA Toolkit - Update visual layout and design of each (3) Toolkit Login page

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#322]
**Update visual layout and design of each (3) Toolkit Login page**
_(Launch Point = Each Toolkit Login Page)_

**Enhancement Specification(s):**
1. Apply a consistent base layout reflected by the provided mockup to all toolkits 
2. Distinction: QA toolkit will feature:
     - ‘Request Account’ button launches “New Account Request” system workflow
3. Distinction: IEM & MDE Toolkit Login screens will feature:
     - ‘Request Account’ button (hyperlink to form as is in existing system)
     - ‘Update Account’ button (hyperlink to form as is in existing system)

**Sample Workflow PDF:**
[2_UpdateLayoutof3LogInPages_V0.1.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1029717/2_UpdateLayoutof3LogInPages_V0.1.pdf)

**(3) Enhancement Mockups:**
1. _QA Toolkit_
![image](https://cloud.githubusercontent.com/assets/4098544/26457994/0f2c7026-4140-11e7-9463-51d1932a1442.png)
2. _MDE Toolkit_
![image](https://cloud.githubusercontent.com/assets/4098544/26458338/ebe69d66-4140-11e7-865b-8279def56c24.png)
3. _IEM Toolkit_
![image](https://cloud.githubusercontent.com/assets/4098544/26458283/c3e14f46-4140-11e7-85b5-3485c93986b7.png)

_Tracking Note: this issue was originally requested as **No. 13.A.2 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good to move to stagging.  Viji warned me the MDE and Yellow Card pictures might be distorted and they are.  Not a major issue but replacing the files with these may look better.  They are 120 px wide with the same filename as used on the page.
![yellowcard](https://cloud.githubusercontent.com/assets/7913678/26803690/1b9b4022-4a13-11e7-8c6b-e4d09a654b2a.png)
![certification](https://cloud.githubusercontent.com/assets/7913678/26803696/21da816e-4a13-11e7-8193-f4d544ab0ec2.png)

**Comment by vijme** [comment]
Images replaced with the ones provided.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
On the IEM & MDE toolkit login pages the text below, next to the 'Request Account' button should read "Request a new user account"

![image](https://user-images.githubusercontent.com/23661339/26891579-83ffcedc-4b83-11e7-8161-d61ef0eb3066.png)

**Comment by vijme** [comment]
Have updated to "Download document to request a new account" , because they are not direct links like QA toolkit. Let me know if not okay.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good
