### ISSUE TITLE
(13.A.3) - QA Toolkit - Replace all instances of the text “submitted for approval” 

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#323]
**Replace all instances of the text “submitted for approval” with “submitted for review”**

**Enhancement Specification(s):**
1. Including basic text string used within Status dropdown, UI Labels, & automatic email notifications see examples below.
2. (4) UI Screens requiring update
    - _Modification Email Notification_
![image](https://cloud.githubusercontent.com/assets/4098544/26463310/dafc109c-4151-11e7-9583-f77c3854171c.png)
    - _Modification Response Page_
![image](https://cloud.githubusercontent.com/assets/4098544/26463327/e9bd1acc-4151-11e7-9597-bf8e40c61393.png)
    - _Modifications Menu: Search Filter & Grid_
![image](https://cloud.githubusercontent.com/assets/4098544/26463342/f604ca46-4151-11e7-8d79-381b14ebb4b8.png)
    - _Project Details: Mods SubMenu_
![image](https://cloud.githubusercontent.com/assets/4098544/26463362/03e90c76-4152-11e7-9442-e776a074aa3a.png)

_Tracking Note: this issue was originally requested as **No. 13.A.3 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
implemented in dev

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
The output for this issue has been validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good
