### ISSUE TITLE
(13.A.4) - QA Toolkit - Replace / Update Buttons

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#324]
**Replace / Update Buttons (may be applied across all toolkits as-needed)**

**Enhancement Specification(s):**

1. Replace w/ new “Merge Projects” button for ‘Merge Projects’ page ![biggr160merge](https://cloud.githubusercontent.com/assets/4098544/26453814/0b0c2f70-4133-11e7-9a9f-7dccfa3b2dde.png)
2. Update “Close” button on ’Permit View’ and ’User Account’ page
     - Permit
![image](https://cloud.githubusercontent.com/assets/4098544/26462668/b4dd5d28-414f-11e7-98ef-66e26dd6514c.png)
     - User Account
![image](https://cloud.githubusercontent.com/assets/4098544/26462705/cd5afe1e-414f-11e7-914b-e1a6bd453ba6.png)
3. Update “Search” button in ‘Admin-Data Cleanup-Hold Adjustments’
![image](https://cloud.githubusercontent.com/assets/4098544/26462733/e6a59fb4-414f-11e7-95c8-1b1b332f4dc9.png)
4. Update (3) buttons in ‘Admin-Data Cleanup-Inspection Dups’
     - Search
     - Reset
     - Print
![image](https://cloud.githubusercontent.com/assets/4098544/26462751/fd750108-414f-11e7-8e39-035becd22261.png)
5. Update (2) buttons in ‘Admin-Standard Forms’:
     - Search
     - Reset
![image](https://cloud.githubusercontent.com/assets/4098544/26462777/15522468-4150-11e7-93ad-2f998b967569.png)

_Tracking Note: this issue was originally requested as **No. 13.A.4 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
Implemented in dev. Replaced all buttons throughout the app.

**Comment by slmessier** [comment]
this issue has been validated by the project team in **DEVELOPMENT**, and will be assigned to Stakeholders to confirm.

**Comment by linsentp** [comment]
The output for this issue has been validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good
