### ISSUE TITLE
(13.A.5) - QA Toolkit - Update core error handling & messaging functionality 

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#325]
**Update core error handling & messaging functionality for QA Toolkit (may be applied across all toolkits as-needed)** 
_(Current Issue: Spacing at the top of the pages covers the flashing red system alerts)_ 

**Enhancement Specification(s):**

1. Eliminate the “flashing” capability of the red text within the banner
2. Replace with a method to display persistent text at the top of the screen (no change to the message text and triggers that exist now)
3. Any exceptions to base error handling case will be documented and handled accordingly

**Enhancement Mockup:**
![image](https://cloud.githubusercontent.com/assets/4098544/26465399/0076354e-4159-11e7-8a72-e2d4605b1610.png)

_Tracking Note: this issue was originally requested as **No. 13.A.5 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by vijme** [comment]
@Tad-Daniel , i just tried to add a processing cursor when a button is clicked. Could you please test in dev to see if this matches your expectation. Otherwise, please advise and i will remove it, and we could address it as a whole new task item in our next release. Thanks.

**Comment by Tad-Daniel** [comment]
I see the processing cursor and like it but I believe we will have to do something that's gets peoples attention more.

**Comment by vijme** [comment]
Thanks for the quick response. I will remove it from this release and we can discuss about other options before finalizing. Thanks again.

**Comment by linsentp** [comment]
The output for this issue has been validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
Good

**Comment by Tad-Daniel** [comment]
Good
