### ISSUE TITLE
(13.A.6) - QA Toolkit - Remove code snippet from login analysis page

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#326]
**Remove code snippet from login analysis page** 

**Enhancement Specification(s):**
1. QA Login Analysis (GH #39)
2. IEM Login Analysis (GH #40)
3. MDE Login Analysis (GH #41)

_Tracking Note: this issue was originally requested as **No. 13.A.6 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
This item is working now. Please comment if should be removed

**Comment by slmessier** [comment]
this issue has been validated by the project team in **DEVELOPMENT**, and will be assigned to Stakeholders to confirm.

**Comment by Tad-Daniel** [comment]
Looks good.  Lets leave it since it is working

**Comment by linsentp** [comment]
The output for this issue has been validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
It all looks good

**Comment by Tad-Daniel** [comment]
Good
