### ISSUE TITLE
(13.A.7) - QA Toolkit - Update UI components within Permit section

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#327]
**Update UI components within Permit section**
_(Launch Point = Permits-Permits)_

**Enhancement Specification(s):**
1. Move the print button to the search field (to be consistent with elsewhere in the toolkit)
![image](https://cloud.githubusercontent.com/assets/4098544/26466542/11c75fae-415d-11e7-994e-d567e535fc92.png)
2. Update Search Filter:  Source of Project search should be project # (currently searching on project description erroneously)
![image](https://cloud.githubusercontent.com/assets/4098544/26466635/6e9bdcd2-415d-11e7-8cc0-c9c3daf2b5b4.png)
3. Highlight expired permits (entire row) in red text (as is done for projects-YC Cert menu)
![image](https://cloud.githubusercontent.com/assets/4098544/26466691/a6eb9636-415d-11e7-863a-cf499330f6af.png)

_Tracking Note: this issue was originally requested as **No. 13.A.7 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
Enhancement # 2 is not complete.  Please, replace label for searching projects from 'Project' to 'Project #', see below:

![newmockup1_projectnumber](https://user-images.githubusercontent.com/23661339/26894396-51990392-4b8c-11e7-84f4-644aee3f70a7.png)

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good
