### ISSUE TITLE
(13.A.9) - QA Toolkit - Update: Search Panel Regions to appear collapsed by default

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#329]
**Update system so that Search Panel Regions appear collapsed by default** (each time a user logs in to begin a session)

**Instances:**
1.	Inspections  // Reports 
2.	Inspections  // Schedule
3.	Inspections  // QA2
4.	Projects  // Project List
5.	Projects  // YC Cert
6.	Projects  // SWM As-Built
7.	Permits  // Permits
8.	Permits  // Permit Templates
9.	Reference Docs
10.	Calendar
11.	BP/SS  // Skipped Inspections
12.	BP/SS  // Non-Compliance
13.	BP/SS  // ESC Certifications
14.	Modifications
15.	Admin  // User List
16.	Admin  // Standard Forms
17.	Admin  // Analysis  //Notification Log
18.	Admin  // Analysis  //Approve Accounts
19.	Admin  // Analysis  //Approve Assignments
20.	Admin  // Data Cleanup   //Project Dups
21.	Admin  // Data Cleanup   //Inspection Dups
22.	Admin  // Data Cleanup   //Hold Adjustments
23.	Admin  // Templates

_Tracking Note: this issue was originally requested as **No. 13.A.9 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Seems to be working correctly

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
working correctly

**Comment by Tad-Daniel** [comment]
Looks good
