### ISSUE TITLE
(13.A.11) - QA Toolkit - Update base UI graphics representation

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#331]
**Update base UI graphic to support Mockup below**

**Enhancement Specification(s):**

1. Center table header labels on all tables 
2. Round corners (border radius of 6 pix) on tabs and have colors of selected tabs match page background 
3. Buffer edge of information grid on all pages and the reference docs shown on the login page.  
4. Update color of Menus / SubMenus to be displayed consistently regardless of parent-child relationship
![image](https://cloud.githubusercontent.com/assets/4098544/26423963/905b791a-409d-11e7-80c0-fabc26e89a06.png)
![image](https://cloud.githubusercontent.com/assets/4098544/26468465/8cbe3c1c-4164-11e7-92e6-68916c2dd9c3.png)

_Tracking Note: this issue was originally requested as **No. 13.A.11 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
Implemented in dev. Tested in IE and Chrome. Please let me know if any changes needed.

**Comment by slmessier** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good
