### ISSUE TITLE
(13.A.12) - QA Toolkit - Reconcile erroneous user workflow: Inspection Dups List Report

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#332]
**Reconcile erroneous user workflow for generate Inspection Dups List Report.** 
_(Launch Point = Admin-Data Cleanup – Inspection dups)_

**Enhancement Specification(s):**

1. Eliminate the pop-up menu that exists currently to launch reports; Immediately generate the ‘Search Results’ Report
2. (The 2 Existing Inspection Log reports will not be launched from this Menu after enhancement is implemented.)

![image](https://cloud.githubusercontent.com/assets/4098544/26424050/defe543e-409d-11e7-9bb9-10c86539dd61.png)

_Tracking Note: this issue was originally requested as **No. 13.A.12 within the Task 13 Scope of Work Agreement**, and as referenced within GH issue #321 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Good
