### ISSUE TITLE
QA Toolkit - Replace (2) Files Directly Supporting Application Graphics

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#333]
Please Replace the following (2) files that directly support the graphics within the application:

**QA Toolkit Banner - _QABanner.gif_ :**
![qabanner](https://cloud.githubusercontent.com/assets/4098544/26457343/cdf3afea-413d-11e7-9800-c4820a2da2a3.gif)

**User Icon - _user.gif_:**
![user](https://cloud.githubusercontent.com/assets/4098544/26457386/ea0d67d4-413d-11e7-8c12-1a3f8e436fe5.gif)

**Comment by vijme** [comment]
Updated in dev. User might have to clear browsing data to see the change

**Comment by slmessier** [comment]
this issue has been validated by the project team in DEVELOPMENT, and will be assigned to Stakeholders to confirm.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in **STAGING** environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good
