### ISSUE TITLE
(13.B.1) - QA Toolkit - QA2 Inspections List PDF - Update Title & Add Total Inspection Count to Bottom of Report

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#334]
**QA2 Inspection List PDF Enhancements**
_(Launch Point = Inspections-QA2-Search Panel 'Print')_

**Enhancement Specification(s):**

1. Update the title of report to “QA2 Inspection” _(currently “QA Inspection)_
2. Add new output to the bottom report to represent the total number of inspections

![qa2inspectionpdfenhancements1](https://user-images.githubusercontent.com/23661339/26929676-84bbd136-4c28-11e7-9816-62f3448e06ca.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Item complete
