### ISSUE TITLE
(13.B.2) - QA Toolkit - Project List PDF - Add Total Project Count to Bottom of Report

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#335]
**Project List PDF Enhancements**
_(Launch Point = Projects-Project List-Search Panel 'Print'-Search Results)_

**Enhancement Specification(s):**

1. Add new output to the bottom of the report to represent the total number of projects

![projectdetailsreports1](https://user-images.githubusercontent.com/23661339/26928826-879ebf74-4c25-11e7-8bc9-7b45187920bd.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Item complete
