### ISSUE TITLE
(13.B.3) - QA Toolkit - Modification List PDF - Update Report Sorting & Fix Column Overlaps

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#336]
**Modification List PDF Enhancements**
_(Launch Point = Modification-Search Panel 'Print')_

**Enhancement Specification(s):**

1. Update the sort order of projects via the contract number on the PDF output to match the sorting of the screen fields 

![project contract number sort update](https://user-images.githubusercontent.com/23661339/26928784-5ff5aabe-4c25-11e7-9825-edc609e79f1b.png)

2. Fix overlaps in the columns

![eliminate column overlaps](https://user-images.githubusercontent.com/23661339/26928794-68a87812-4c25-11e7-8df9-62336fe60168.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
Address column overlaps for **all columns** in the report.

![image](https://user-images.githubusercontent.com/23661339/27184581-948a0e38-51b0-11e7-886f-cb85f2737c3a.png)

**Comment by vijme** [comment]
Have increased spacing for contract and if its still longer will go the second line. Ideally, contract numbers aren't that long.

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Item complete
