### ISSUE TITLE
(13.B.5) - QA Toolkit - Project Details Report PDF - Multiple Layout Enhancements

### ISSUE THREAD

**Issue by linsentp** [kcigeospatial/sha_oed_issues#338]
**Project Details Report PDF Enhancements**
_(Launch Point = Projects-Project List-'Print')_

**Enhancement Specification(s):**

A. Left justify 'Modifications' & 'QA Concurrence' text
B. Add 'SWM Requests' to the Project Details Report ordered (oldest-newest)
C. Update request numbering for 'QA Concurrence' (smallest-largest)
D. Remove the time stamp under 'MOD DATE' and left justify

![projectdetailsreportenhancement](https://user-images.githubusercontent.com/23661339/26931686-565eed30-4c2f-11e7-81ed-c4ad773456dd.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by linsentp** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by vijme** [comment]
QA Concurrance was listing only Approved/Denied requests. Fixed to show all requests in dev and staging.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Item complete
