### ISSUE TITLE
QA Toolkit - Update Report Logic - ESC / SWM Grade Summary Report

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#339]
**This issue has been created as a spin-off task from #318 to track the development and testing of revising the underlying report query logic to exclude skipped inspections.** 

See the details of prior correspondence below:
![image](https://user-images.githubusercontent.com/4098544/28349489-264941ac-6c11-11e7-9bb0-dbbefdab6c64.png)

**Comment by slmessier** [comment]
Tad - **please use the DEVELOPMENT application URL to validate** the updated report logic at your earliest convenience. Thank you!

**[http://oed.kci.com/SHAPORTAL/](url)**

**Comment by Tad-Daniel** [comment]
Looks like the numbers are coming up correctly now

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
appears to function correctly but our data is so odd in the staging environment that checking for accuracy is difficult.  I can do a final check in production.

**Comment by Tad-Daniel** [comment]
Appears correct. issue closed.
