### ISSUE TITLE
QA Toolkit - Application Error on Merge Projects Function

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#340]
**The Merge Projects function is producing an application error message when executing the function on certain projects. Please investigate the source of the issue and identify potential method(s) for resolving.** 

1. The failure appears to occur for distinct project combinations, while the function works as expected for others.
2. **The error can be replicated using the DEV URL for the following projects**. Please reference the animated graphic as needed.
     - contract number: **_98765432 - testing incentives 3_**
       **MERGE INTO**
     - contract number: **_AA1515188 - LU TEST_**

![mergeprojectserror](https://user-images.githubusercontent.com/4098544/29280306-b7b8a916-80e8-11e7-9b5b-aa37ce3f541c.gif)

**Comment by vijme** [comment]
Issue fixed in dev

**Comment by slmessier** [comment]
Hi Tad - Please text using the DEV URL at your earliest convenience. Thank you!

[http://oed.kci.com/SHAPORTAL/](url)

**Comment by Tad-Daniel** [comment]
Appears to working correctly

**Comment by slmessier** [comment]
This issue has been tested and validated by the project team in the DEVELOPMENT environment

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Working correctly

**Comment by slmessier** [comment]
@Tad-Daniel - Can this be closed? Thank you!

**Comment by Tad-Daniel** [comment]
Appears to be working. Closed
