### ISSUE TITLE
QA Toolkit - Modification Request Form - Authentication Error SHA PE

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#341]
On the Modification Request Form, **the logic that determines authentication for the SHAPE Signature box is not enforcing authentication requirements as expected. Users with Contractor role are currently and erroneously able to authenticate the SHAPE signature box.** 

**Please investigate the source of the issue and identify potential method(s) for resolving.** See the screencap below for details replicating the issue.

**Screencap executed as "Scott_contractor" who has profile = Contractor:**
![modificationauthenticationerror](https://user-images.githubusercontent.com/4098544/29281793-5bdf513e-80ee-11e7-9cb9-9130fa907576.gif)

**Comment by vijme** [comment]
Fixed in dev

**Comment by Tad-Daniel** [comment]
Appears to be working correctly

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by stakeholders in the Development Environment.

This issue has been updated to status = "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Works correctly

**Comment by Tad-Daniel** [comment]
works correctly
