### ISSUE TITLE
QA Toolkit - Project QA Concurrence SubMenu - Paging Error

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#342]
**The paging function within the QA Concurrence Menu Grid is not functioning - when it is clicked the application does not navigate to the second page as expected. Please investigate the source of the issue and identify potential method(s) for resolving.** 

**Screencap:**
![qaconcurrencescrollerror](https://user-images.githubusercontent.com/4098544/29282824-3e16f1e4-80f2-11e7-92a7-b74cc96a7729.gif)

**Comment by vijme** [comment]
Fixed in dev

**Comment by Tad-Daniel** [comment]
Working correcctly

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by stakeholders in the Development Environment.

This issue has been updated to status = "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Working correctly

**Comment by Tad-Daniel** [comment]
working correctly, issue closed
