### ISSUE TITLE
QA Toolkit - Add ability for “ESC Manager” to Delete SWM submittals

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#345]
**Create a new button and function to delete the SWM record.** 

1. Capability is **enabled for the _ESC Manager_ profile exclusively**
2. Capability is **disabled for all other profiles**. 
3. Button/Function may be **launched from 2 locations in the UI**:
       - (Projects) **SWM SubMenu _"Existing SWM Requests"_ Grid**
       - **_"SWM As-Built Submittal Request Form"_**

### Enhanced SWM SubMenu - Existing SWM Requests Grid
![image](https://user-images.githubusercontent.com/4098544/29290411-fbe71896-810d-11e7-9a23-4f641787c026.png)

### Enhanced SWM As-Built Submittal Request Form
![image](https://user-images.githubusercontent.com/4098544/29290637-d7dcc350-810e-11e7-876c-fe872f12fde2.png)

_Tracking Note: this issue was originally requested as **No. 14.B within the Task 14 Scope of Work Agreement**, and as referenced within GH issue #343  of this repository._

**Comment by vijme** [comment]
Can you provide the big "delete" button? We do not have this delete button in the whole toolkit and our GUI designer is on vacation.

**Comment by Tad-Daniel** [comment]
![biggr80delete](https://user-images.githubusercontent.com/7913678/29467477-b5df3c3a-840e-11e7-8ec8-06c71fca8a50.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
The issue has been successfully verified by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good except the delete button on the SWM submittal form appears for other roles beyond administrator.  This function should only be for those with administrator rights.

**Comment by vijme** [comment]
Fixed in dev

**Comment by slmessier** [comment]
@HollySchuelerKCI - please validate accessibility of delete button (described above) is limited to users with admin permissions exclusively. Please validate for all user role profiles.

![image](https://user-images.githubusercontent.com/4098544/30486714-5e37d440-99ff-11e7-805a-b1bb59d7e6de.png)

**Comment by vijme** [comment]
@slmessier , Shouldn't it be ESC Manager role ?

**Comment by slmessier** [comment]
@vijme @HollySchuelerKCI 
Yes! my mistake- please adjust accordingly.

**Comment by HollySchuelerKCI** [comment]
This issue has been verified by the project team in the Development Environment.  Tested and verified that the delete functionality is exclusively for the ESC manager.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Works correctly

**Comment by Tad-Daniel** [comment]
works correctly. issue closed
