### ISSUE TITLE
Toolkit Landing Page - Update SHA Logo Graphic w/ New Logo

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#346]
Please **replace the logo on the landing page with the new logo** that has been updated by SHA.  

New logo is attached with the file-naming syntax that should allow for simple replacement of the old file.

### Target Logo Graphic to Update:
![untitled_clipping_081517_091628_am](https://user-images.githubusercontent.com/4098544/29317547-6ca6c50e-819a-11e7-92fa-8eadea9b286a.jpg)

### Updated Logo Source File:
![logo](https://user-images.githubusercontent.com/4098544/29317492-2378feb0-819a-11e7-804b-9ecb535f660f.png)

**Comment by vijme** [comment]
Implemented in dev. May need to clear the browser cache

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
This issue has been confirmed by the testing team in the DEVELOPMENT environment. Issue will be labelled as "Ready for Staging".

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Good

**Comment by Tad-Daniel** [comment]
Looks good in production. Issue closed.
