### ISSUE TITLE
QA Toolkit - Update System Logic for setting Inspection Due Date 

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#347]
### Required Enhancement Specification(s):
Currently, the system automatically determines the inspection due date based on the applicable Project’s active “QA Inspection Priority” value. Three (3) values exist currently.

**1. Update the system to display six (6) total values:**
  - **1 week ; replacing the existing “High” priority**
  - **2 weeks ; replacing the existing “Medium” priority**
  - **3 weeks ; replacing the existing “High” priority**
  - **4 weeks (new)**
  - **5 weeks (new)**
  - **6 weeks (new)**

**2. Extrapolate system logic to automatically calculate Inspection Due Date onto the three (3) new values (4, 5, & 6 weeks)** 

![image](https://user-images.githubusercontent.com/4098544/29332631-b190f642-81ce-11e7-8be9-2bea4dc9a200.png)

### PDF Mockup Example:
[14C_3_AutomatedQAInspectionDueDate_V0.3_20170711.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1226134/14C_3_AutomatedQAInspectionDueDate_V0.3_20170711.pdf)

_Tracking Note: this issue was originally requested as **No. 14.C within the Task 14 Scope of Work Agreement**, and as referenced within GH issue #343 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Appears correct

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by stakeholders in the Development Environment.

This issue is ready for staging.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Appears correct

**Comment by Tad-Daniel** [comment]
Issue complete.
