### ISSUE TITLE
QA Toolkit - Inspection Schedule PDF Report - Update Design for New Inspection Schedule Info

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#351]
### Required Specifications
**Update Design of Existing PDF Report: Inspection Schedule** - add new schedule information to report output, resulting from development of Task 14-E #349. 

**Changes to Design:**
1. **_District_ Column**
2. **_Permits and SPI Info_ Column**

### Report Mockup Design (includes launch):
 [14G_9_InspectionSchedulePDFReportEnhancement_V0.3_20170711.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1232297/14G_9_InspectionSchedulePDFReportEnhancement_V0.3_20170711.pdf)
![image](https://user-images.githubusercontent.com/4098544/29429416-a061b924-835e-11e7-93ad-a87997be494d.png)

_Tracking Note: this issue was originally requested as **No. 14.G within the Task 14 Scope of Work Agreement**, and as referenced within GH issue #343  of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been tested successfully in the development environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been tested successfully by the project team and confirmed by stakeholders in the Development Environment.

This issue has been updated to status = "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been tested successfully by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
It all looks good but I have noticed (because I currently have 3 different devices in front of me)  That the column for the permit and SPI icons varies depending on zoon level.   Lets go with what we have now as it is functional and re-evaluate if it may need some tweaking later.

**Comment by Tad-Daniel** [comment]
Looks good in production. Issue closed.
