### ISSUE TITLE
QA Toolkit - Develop New PDF Report - User Email Subscription Summary Report

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#352]
### Required Enhancement Specification(s): 
Design (Mockup) & develop a new report that indicates the notification subscription configuration for all user accounts
**Launch Point: Admin - Users - (New Button ; see mockup below)**

### PDF Report Mockup:
[14G_10_NewUserNotificationSubscriptionPDFReport_V0.4_20170817.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1232771/14G_10_NewUserNotificationSubscriptionPDFReport_V0.4_20170817.pdf)
![image](https://user-images.githubusercontent.com/4098544/29436215-8bb3ffe0-8378-11e7-9f51-2e83852ef73a.png)
![image](https://user-images.githubusercontent.com/4098544/29436150-4819f1f4-8378-11e7-91b4-298d1891b336.png)
_Tracking Note: this issue was originally requested as **No. 14.G within the Task 14 Scope of Work Agreement**, and as referenced within GH issue #343 of this repository._

**Comment by vijme** [comment]
With reference to issue #350, the site condition notifications will be merged into one.

**Comment by vijme** [comment]
Implemented in dev, I have included different site condition notifications but can be merged into one later when necessary.

**Comment by Tad-Daniel** [comment]
With the removal of the old separated template options for subscriptions shouldn't the say be done on this report to only reflect the new simplified options?   Also, it is a bit bust so can the checks boxes be just check marks.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.  Awaiting ready for staging tag when Tad's comment is addressed.

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by stakeholders in the Development Environment.

This issue has been updated to status = "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in production. Issue closed
