### ISSUE TITLE
QA Toolkit - Modification Package Approver Value - Reconcile Persistence

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#353]
The current system logic is overwriting the "Package Approver" association for modification requests falling into the distinct case described hereafter:
1. A user with Package Approver capabilities initially approves the package
THEN
2. Another user with both Package Approve AND Request Approver capabilities approves the request.

**Please investigate to identify and confirm the underlying cause of the issue, and then update the system logic as needed to satisfy the requirement that the initial "Package Approver" value must persist after the 2nd user subsequently approves the request.**

### Description of Issue Case:
In the scenario below:
1. Brian McGrath user account is set up as a package approver.
2. Tad Daniel user account is set up as both a package approver and a request approver.
3. The Mod request has been sent to the QA program by Brian which the system displays below ![image](https://user-images.githubusercontent.com/4098544/29828135-df0cb274-8ca9-11e7-9215-4491d5bcef36.png)
4. When Tad logs in to comment, approve or deny, the system currently overwrites the value with Tad's account instead of Brian’s (see below).  ![image](https://user-images.githubusercontent.com/4098544/29828308-59ec8546-8caa-11e7-97d6-8f08d6e5350e.png)
5. This appears to be related to the fact that Tad's account has both package and request approver capabilities simultaneously.  The issue does not occur for user accounts with request approver permissions without have package approver permissions.

**Comment by vijme** [comment]
Issue fixed in dev

**Comment by Tad-Daniel** [comment]
Appears to be working correctly

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by stakeholders in the Development Environment.

This issue has been updated to status = "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Good

**Comment by Tad-Daniel** [comment]
Working correctly, issue closed
