### ISSUE TITLE
QA Toolkit - User Profile Permission Modification: Permit Templates Menu & Delete Permits Function

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#354]
Please update the user profile system permissions as follows:
1. **_Delete Permit_ Function is not executable** on the _Permits Menu_
2.  **Access to the _Permit Templates Menu_ is restricted** entirely

Restrict access as described above for the following profiles:
1. Power Reviewers
2. Reviewers
3. Inspectors
4. Contractors
5. Project Engineers 

![image](https://user-images.githubusercontent.com/4098544/31562445-7b207f86-b029-11e7-8c8d-2524b867758a.png)

**Comment by vijme** [comment]
Permit Templates Menu hidden from above usergroups. This is database change only, we can implement in STGNG and PRDN right away.

PERMITS page is configured to show or hide the three buttons, (viz. edit, delete and NEW PERMIT buttons) from database. This will only be Database change and can be deployed asap.  But according to the above requirement, if we need to hide only the delete button, there will be associated code changes and then redeployed. Please advise as necessary.

**Comment by slmessier** [comment]
@Tad-Daniel **Please provide feedback for the 2 items below**. Your feedback is requested in order to continue moving forward toward implementation of the intended solution. Thank you!

1. **_Permit Templates Menu_ is accessible/restricted according to expectation for each user group**.
2. **Provide technical guidance**:
       A. **Can accessibility of _Permits Menu_ buttons (_Edit, Delete, New Permit_) be managed collectively**, which is the preferred development solution?
       OR
       B. **Must each button be maintained distinctly - such as disabling the _Delete_ button** exclusively as stated within the initial request?

**Comment by slmessier** [comment]
### updated specification for Permit Menu:
From: Tad Daniel [mailto:tdaniel@sha.state.md.us] 
Sent: Wednesday, October 18, 2017 12:28 PM
To: 'Viji Selvamani' <viji.selvamani@ecointegration.com>; Scott Messier <Scott.Messier@kci.com>
Subject: RE: [kcigeospatial/sha_oed_issues] QA Toolkit - User Profile Permission Modification: Permit Templates Menu & Delete Permits Function (#354)

**YES**

From: Viji Selvamani [mailto:viji.selvamani@ecointegration.com] 
Sent: Wednesday, October 18, 2017 11:16 AM
To: Tad Daniel <tdaniel@sha.state.md.us>; Scott Messier <Scott.Messier@kci.com>
Subject: RE: [kcigeospatial/sha_oed_issues] QA Toolkit - User Profile Permission Modification: Permit Templates Menu & Delete Permits Function (#354)

Tad,

Please find the below screenshots for the PERMITS page that is currently in DEV. Does this meet your requirement?

**VIEW FOR (2) PROJECT MANAGER & ESC MANAGER** 
- View
- Edit
- Delete
- New Permit
 ![image](https://user-images.githubusercontent.com/4098544/31786337-270d86bc-b4d6-11e7-85f1-57a9ca3c104d.png)

**VIEW FOR (5) Power Reviewer; Reviewer; Inspector; Contractor; Project Engineers**
- View
- (edit/ delete and new permit button removed)
![image](https://user-images.githubusercontent.com/4098544/31786421-6d1c31d0-b4d6-11e7-97f5-d2ce30f414bb.png)

**Comment by slmessier** [comment]
@Tad-Daniel 
Please test DEV URL and confirm each menu: http://oed.kci.com/SHAPORTAL/
1. **_Permit Templates Menu_**
2. **_Permits Menu_**

**Comment by Tad-Daniel** [comment]
It is now correct in the DEV environment

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in Production
