### ISSUE TITLE
QA Toolkit - Adjust Aesthetic Contrast of “View-Only” Pages to Improve Legibility

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#355]
**Required Enhancement Specification(s):**
1.  Adjust aesthetic contrast of “View-Only” (grayed-out) pages to improve legibility for the following:

     - 	QA-3 page
     - 	Project Details page 

![image](https://user-images.githubusercontent.com/25441512/31899110-cd6032c0-b7e8-11e7-89a6-c62ab3bebfed.png)

**Comment by vijme** [comment]
Does it require more greying?

**Comment by slmessier** [comment]
The contrast must be increased between the font and the color that is utilized to display a field as "grayed out". 

The font should become more clearly discernable to the eye when a field is disabled.

**Comment by vijme** [comment]
Only the background could be changed in a disabled panel. Changed the background to F5F5DC (Beige) to show contrast. Please let me know if that works.

**Comment by Tad-Daniel** [comment]
Yes, that looks good. easier to read.

**Comment by HollySchuelerKCI** [comment]
@vijme I was unable to validate this issue as it appears that the background color (F5F5DC) does not appear in the staging environment.

_Staging_ Example (Logged in as an Inspector):
![image](https://user-images.githubusercontent.com/25441512/32449473-a7e54a38-c2df-11e7-8557-32779fb9be13.png)


_Development_ Example (Logged in as an Inspector):
![image](https://user-images.githubusercontent.com/25441512/32449523-c69b6db8-c2df-11e7-88db-e3d4ae4a75a8.png)

**Comment by vijme** [comment]
Strange. Please specify the browser you are using. I see this in STGNG when logged as Inspector

![image](https://user-images.githubusercontent.com/6668314/32451402-ae0079d8-c2e4-11e7-9949-d2cbf597bd2f.png)

**Comment by vijme** [comment]
Above ones from IE and this is from chrome

![image](https://user-images.githubusercontent.com/6668314/32451474-ddfcf0a8-c2e4-11e7-97e9-3b73d6b6c901.png)

**Comment by HollySchuelerKCI** [comment]
@vijme My apologies, I cleared my browsing history and that corrected the issue I reported.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks OK for production but are there any other options.  Does the non-editable fields have to look different or can they just be a white background. It is not important to visualize as to what is editable or not, It is important that they cannot edit.

**Comment by vijme** [comment]
With regard to the disabled panel view:

-The background color change is effective in IE and chrome.
-The font color is effective only in chrome, doesnot have any effect in IE (always gray)
 
Please see the background color change to white and let me know if that works. 
![image](https://user-images.githubusercontent.com/6668314/32609718-95e0cbae-c52e-11e7-97ad-6262fb1e6571.png)

**Comment by Tad-Daniel** [comment]
Yes,  That works well..

**Comment by vijme** [comment]
Implemented in dev and Staging

**Comment by Tad-Daniel** [comment]
Looks good,  Thanks

**Comment by Tad-Daniel** [comment]
Looks good in Production
