### ISSUE TITLE
QA Toolkit - Update Permit Expiration Notifications to Incorporate a Check for One (1) or More Active Project Associations

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#356]
**Required Enhancement Specification(s):**

1. Update the permit expiration notifications to incorporate a check for one (1) or more active project associations.

     - 	Does 1 (or more) active project association exist? 
     - 	If so send notification; When 0 associations exist do not send notification.

**Comment by vijme** [comment]
Please clarify whether active project means projects that are not closed

**Comment by slmessier** [comment]
@vijme - you are correct. The query should indeed include a check for those projects that are OPEN distinctly.

**Comment by vijme** [comment]
Implemented in dev. Cannot be tested in dev and testing since permit notifications are only available as automated notifications. This is a separate code and can be  deployed to production anytime.

**Comment by Tad-Daniel** [comment]
Sounds good,  Lets deploy it when possible and then we can follow up.  Thanks

**Comment by vijme** [comment]
Deployed to production yesterday (10/31/17), please check.

**Comment by slmessier** [comment]
@Tad-Daniel Please test and log results at your earliest convenience using PROD instance:
http://www.oedtoolkits.net/

**Comment by Tad-Daniel** [comment]
This item is working properly in production
