### ISSUE TITLE
QA Toolkit - Add Text Notes Directly to Various Pages as User Instruction 

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#357]
**Required Enhancement Specification(s):**

Add text notes directly to various pages as user instruction (Text to be provided)

A.	Modifications summary page
![image](https://user-images.githubusercontent.com/25441512/31902958-a35d440c-b7f4-11e7-8fb9-3823342b4dbd.png)

B.	SWM summary page
![image](https://user-images.githubusercontent.com/25441512/31902984-ba131bc2-b7f4-11e7-8351-0827dc3c8d64.png)

C.	Project Comment / Communication page clarifying response vs new comment
![image](https://user-images.githubusercontent.com/25441512/31902897-73146e6a-b7f4-11e7-8350-f620c2cb6e79.png)

D.	Mods, Concurrence and SWM subtabs a line clarifying new request vs response
![image](https://user-images.githubusercontent.com/25441512/31903092-15f323e2-b7f5-11e7-8308-7c7af100ad49.png)

E.	A note on each applicable page concerning opening the search fields
![image](https://user-images.githubusercontent.com/25441512/31903176-5ba3476e-b7f5-11e7-92c5-facac8ae1727.png)

F.  Modification Request (QA3) Form
![image](https://user-images.githubusercontent.com/4098544/32065380-9fcccb16-ba4a-11e7-8bb1-c3beea95f371.png)

**Comment by slmessier** [comment]
@Tad-Daniel - **Please produce and attach a word .doc file to represent text for each of the following sets of instructions:**
1. Modifications Summary Page
2. SWM Summary page
3. Communication page clarifying response vs new comment
4. Mods, Concurrence and SWM subtabs a line clarifying new request vs response
5. A note on each page concerning opening the search fields

**Comment by vijme** [comment]
For 5, Please find the text inside the search panel. Just one added advantage, instead of clicking on "+", the user can now click on the text. Let me know if any change in text is needed. 

Due to 5, I removed the recurring lines from 1 and 2.

**Comment by slmessier** [comment]
@vijme - thanks for logging the additional specification. In my assessment your discretion is ideal for each case you have noted. 

Please consider requirements for development of this request satisfied pending any feedback Tad provides after he has the opportunity to test / confirm.

**Comment by Tad-Daniel** [comment]
Everything looks good with the exception of a few tweaks.

- Please remove the outline from around the test on the User Settings page and the Modification request form page, Also remove the "-" from the beginning of the line and place spaces between each line.

- I really like the text located within the search panel but it also appears in the panel related to adding a new attachment. The text also does not fit every situation that it appears.  Change the word "submittal" to "item" to better fit all instances.  Remove the text from the add new document sections.  

- If removing the text from the add new documents panel is a challenge another option is to shorten the test to read "open the panel by clicking the "+" symbol". This would fit all instances it appears.

- In the SWM suntan of the project record change the text to read" "To submit a new SWM AS-Built, click the "New Submittal" button at the lower right of the page. To comment on an existing active submittal, click the "Respond" button to the right of the specific submittal from within the grid."

**Comment by vijme** [comment]
Thanks for the details. Have changed the text only in search panel and removed from other collapsible panels like documents, sheets etc. 

Implemented in dev

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in Production although it did move around the checkbox's under Activity Location on the QA-3 modification form. Reference the screen shot above to see how they were all lined up prior and now they a spaced differently.

**Comment by slmessier** [comment]
@Tad-Daniel  If fixing this is an issue we can handle it as an enhancement to bundle within the next update.  I can log as a new issue in Github if necessary, however I'd like to close this issue to keep tracking organized.

Please advise - thank you!

**Comment by Tad-Daniel** [comment]
Closing this is fine as long as we keep track of it and resolve in a future update.

**Comment by slmessier** [comment]
@Tad-Daniel  The issue you are encountering looks to be resulting from the size of your specific browser window. (compare the variance of the 2 screenshots below)
Could you please test from another machine to confirm? Please advise as to next steps.

### Small Window:
![image](https://user-images.githubusercontent.com/4098544/32741716-30e55270-c875-11e7-900f-da9cb03303a4.png)

### Full-Size Window:
![image](https://user-images.githubusercontent.com/4098544/32741744-4a929ff2-c875-11e7-8bd8-b037fa54cb11.png)

**Comment by Tad-Daniel** [comment]
Yep, That's it.  My current laptop is limited to 1024x768 so it is not that great.    This is a non-issue as it will not effect the majority of regular users.
