### ISSUE TITLE
QA Toolkit - Change the Default View of the Permit Listing Grid to Sort by Expire Date, Descending

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#358]
**Required Enhancement Specification(s):**

1. Change the default view of the permit listing grid to sort by Expire date, descending.

![image](https://user-images.githubusercontent.com/25441512/31903844-7a8c8800-b7f7-11e7-9940-ef38d0d92b0c.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in Production
