### ISSUE TITLE
Download Project Documents - Error Message Displayed

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#359]
On several project recently it seem that **uploaded documents cannot be reliably downloaded as expected. An error message is instead returned when attempting to download a document**.  

**The screenshot below is from Mod # 7 on MO9125130.** I have heard from Polly that sometimes she can download the doc and other times she cannot, like it comes and goes.
 
 
![image](https://user-images.githubusercontent.com/4098544/31918509-0afdbb60-b82b-11e7-8c9f-bc55abf237eb.png)

**The issue was able to be replicated in each of the 4 instances below**
1.	PROD instance - Contract #: MO9125130
   a.	Document Tab - GPS/Waypoint 8/23/2017 & Page 2 - Second GPS/Waypoint 10/5/2017
   b.	Mods Tab – Mod # 7 Click PDF button - rror: An unrecoverable error has occurred in the application
2.	STAGING instance - Contract #: AA1375133
3.	STAGING instance - Contract #: AA4915130
4.	STAGING instance - Contract #: AA5805670

**Comment by HollySchuelerKCI** [comment]
The issue was replicated in the browser Google Chrome Version 62.0.3202.62

**Comment by vijme** [comment]
This issue seems to be due to double clicking the MODS/QA/SWM page when creating a new request. To replicate in STAGING, create a new MOD/QA/SWM request and double click the SUBMIT button. The request will be created twice.  If documents are added to the request, the second request will not have the document. This propagates to the documents tab with no document specified error. And any mod bundling with this MOD will turn an error. 

Have disabled double clicking with the SUBMIT buttons in DEV. This should work now.

**Comment by Tad-Daniel** [comment]
Wow....   If this resolves the issue for us you will have fixed not only the error message problem but also the duplicate modifications issue.   Thanks

**Comment by vijme** [comment]
@Tad-Daniel, yes,  when i found that was the cause,  I realized that you had been saying this issue for a while.

**Comment by HollySchuelerKCI** [comment]
The project team was able to successfully replicate the issue in the staging environment as instructed by Viji.

This issue has been successfully validated by the project team in the Development Environment.

**Comment by slmessier** [comment]
@Tad-Daniel  please test/confirm at your earliest convenience using the DEV instance:
http://oed.kci.com/SHAPORTAL/

**Comment by Tad-Daniel** [comment]
Appears to be working correctly in DEV as double clicks no longer happens on my Windows machine with IE.  The following is not a concern to address but I wanted to let you know that I can still double click on my Mac in Safari.  Again, No need to correct that particular thing but thought you would like to know.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
So far no reports of this issue occurring so I will update in the near future

**Comment by Tad-Daniel** [comment]
This issues has not repeated since the fix was placed in production.  This issue is complete
