### ISSUE TITLE
QA Toolkit - Add Ability to Sort Documents in the Project Record Sub-Tab by Header

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#360]
**Required Enhancement Specification(s):**

1. Add ability to sort documents in the project record sub-tab by header (Type, Description, Date)

![image](https://user-images.githubusercontent.com/25441512/31943236-1926ebe2-b896-11e7-9327-824b7e2d36dd.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in Production
