### ISSUE TITLE
QA Toolkit - Change Text Label from "Reports" to "QA1"

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#363]
**Required Enhancement Specification(s):**
1.  Under the Inspections Menu tab, please change the text label from "_Reports_" to "**_QA1_**" in the QA Toolkit.

![image](https://user-images.githubusercontent.com/25441512/32171741-9109317a-bd4f-11e7-853a-0fad44425567.png)

![image](https://user-images.githubusercontent.com/25441512/32171763-a2e57412-bd4f-11e7-83d8-0837e4ef6c26.png)

**Comment by vijme** [comment]
Changed text label and order to display as in the graphics above

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in Production
