### ISSUE TITLE
QA Toolkit - Relocate Calendar Menu (Level 1) to Appear as a Level 2 Menu

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#364]
**Required Enhancement Specification(s):**

1.  Relocate the Calendar Menu currently found in Level 1, to appear as a Level 2 Menu nested beneath the Inspections Menu (Level 1).

![image](https://user-images.githubusercontent.com/25441512/32172245-53f902a4-bd51-11e7-8106-82dfffcc6cc3.png)

**Comment by vijme** [comment]
Moved to under inspections after QA2 subtab

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in Production
