### ISSUE TITLE
QA Toolkit - Change Text Label "Inspections" to "QA Inspections"

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#365]
**Required Enhancement Specification(s):**

1.  Located on the Project Details page, change the text label of the "_Inspections_" Tab (Level 3) to "**_QA Inspections_**" Tab. 

![image](https://user-images.githubusercontent.com/25441512/32172592-8598a8a4-bd52-11e7-814b-be5562cae55e.png)

![image](https://user-images.githubusercontent.com/25441512/32172463-0d3cc93a-bd52-11e7-9480-8c0415d72f45.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
@vijme Upon validating this issue, I discovered that the text for the Inspections tab found in level 3 has remained and has not been updated to "QA Inspections". 

Using:
Chrome browser, version 62.0.3202.75
IE browser, version11.15.16299.0

Dev Environment:
![image](https://user-images.githubusercontent.com/25441512/32455023-ff2c3d6a-c2ee-11e7-9631-50344aa4a913.png)

Staging Environment:
![image](https://user-images.githubusercontent.com/25441512/32455038-0a7669d4-c2ef-11e7-898e-08b218912cc4.png)

**Comment by HollySchuelerKCI** [comment]
Per email received from Viji:

For effectiveness, The subtabs are checked from Database only if it has not been accessed in past one hour. Within an hour, they are loaded from the cache variable. So to see the “QA Inspections” subtab, you may need to simply logout and then login back after an hour.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in Production
