### ISSUE TITLE
QA Toolkit - Relocate Modifications Menu (Level 1) to Appear as a Level 2 Menu

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#366]
**Required Enhancement Specification(s):**

1.  Relocate Modifications Menu (Level 1) to appear as a Level 2 menu nested beneath Projects Menu (Level 1)

![image](https://user-images.githubusercontent.com/25441512/32172718-f0680850-bd52-11e7-8e8a-eb95ceb6d718.png)

![image](https://user-images.githubusercontent.com/25441512/32172733-04dabee0-bd53-11e7-9ac5-9c86e2a17593.png)

**Comment by vijme** [comment]
Moved to Projects tab to show before SWM subtab.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in Production
