### ISSUE TITLE
QA Toolkit - Change Text Label from "ESC Certification" to "ESC Training #'s"

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#367]
**Required Enhancement Specification(s):**

1.  Within the BP/SS Menu Level 1, change the text label from "_ESC Certification_" to "**_ESC Training #'s_**" in Level 2.

**_Current UI_**:
![image](https://user-images.githubusercontent.com/25441512/32173121-5267c7e2-bd54-11e7-88b5-dfc96bf1790e.png)

_**Future UI**_:
![image](https://user-images.githubusercontent.com/25441512/32172828-5c5954f6-bd53-11e7-942a-ab5822a99e73.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by Tad-Daniel** [comment]
Looks good in Production
