### ISSUE TITLE
QA Toolkit - 3 Minor UI Updates

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#368]
1. Please r**eplace the _QABanner.gif_ file** with the attached graphic below
![qabanner](https://user-images.githubusercontent.com/4098544/32347997-da6f12e4-bfe8-11e7-9fc1-2a457608ba9d.gif)
2. Please **replace the _bg.jpg_ file** with the attached graphic below
![bg](https://user-images.githubusercontent.com/4098544/32348051-0142b4b6-bfe9-11e7-94b1-119fd2fab2a4.jpg)
3. **Remove the border that frames the instructional text on the New account Page** 
![image](https://user-images.githubusercontent.com/4098544/32348371-eb88a6f2-bfe9-11e7-84ec-35facbfb3ee2.png)

**Comment by vijme** [comment]
Graphics replaced, and help text matched to other text in system. Let me know if needed changes.

**Comment by vijme** [comment]
May need to clear browser cache for viewing graphic updates

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by slmessier** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Loks good

**Comment by Tad-Daniel** [comment]
Looks good in Production
