### ISSUE TITLE
QA Toolkit - Unrecoverable Error when Clicking New User Button

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#369]
Currently, the system does not allow the user to add a new user account when select the _New User_ button found on the Admin tab.

Ideally, when the user clicks the _New User_ button, the system will display the New User page.

**Original Request via Email on 12/1/2017**: _When clicking the new user button in the user list of the admin section I get the unrecoverable error.   Creating an account through the online submittal system works fine._

**Steps to Replicate:**
1. Login to the QA toolkit
2. Click the Admin Tab
3. Click the New user button 

![image](https://user-images.githubusercontent.com/25441512/33490043-c6d43f8c-d683-11e7-932c-b2cac5bc6448.png)

**Comment by vijme** [comment]
Fixed in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
appears to be working

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder in the Development Environment.

This issue has been updated to status = "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Working Correctly

**Comment by HollySchuelerKCI** [comment]
This issue has been upgraded to status = "Ready for Production"

**Comment by Tad-Daniel** [comment]
Issue resolved. Can be closed
