### ISSUE TITLE
QA Toolkit - Mods Sub Tab Download does not occur

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#371]
Currently, when the user clicks the download button found to the right of a mod response, the system does not download the response to the user's machine.

Ideally, when the user clicks the download button for the response, the system will download the response selected by the user to the user's machine.

**Original Request via Email on 11/15/2017**: _Under the Mods sub-tab, when clicking on a download arrow for a response the download does not happen as expected._

**Steps to Replicate:**
1. Select Edit Details for project 20160301_scott_test
2. Click the Mods tab in Level 3
3. Click the red link to expand and view the responses for a Mod
4. Click the download button for one of the responses
5. Note that the system begins to process the request, but fails to download

**Comment by vijme** [comment]
Fixed in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Appears to be working

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder in the Development Environment.

This issue has been updated to status = "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Working correctly

**Comment by HollySchuelerKCI** [comment]
This issue has been upgraded to status = "Ready for Production"

**Comment by Tad-Daniel** [comment]
This issue has been corrected but appears to have caused another issue, now the PDF button to download the entire mod package does not seem to be working

**Comment by vijme** [comment]
Issue fixed in dev.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Working correctly in dev.

**Comment by slmessier** [comment]
Removing "Ready for Production" label and Milestone: RC_2018_01 tag to reflect the subsequent need to develop a patch for the issue downloading the entire package.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by project stakeholders in the Staging Environment.

This issue has been updated to status = "Ready for Production"

**Comment by Tad-Daniel** [comment]
Item complete, issue corrected.

**Comment by HollySchuelerKCI** [comment]
The status of this issue = Closed
