### ISSUE TITLE
QA Toolkit - Search Panel Checkboxes do not Appear for Inspector Role

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#372]
Currently, the search box checkboxes found within the Inspection Tab, QA Calendar Level 2.

Ideally, when logged in as an Inspector, the user will expand the search panel which will display Event Type checkboxes that will be selected by default.

**Original Request via Email on 11/15/2017**: _On the QA Calendar for the ESM Managers Role the search panel checkbox’s are misaligned and for the Inspector role they do not appear.  Also the calendar items do not appear for the Inspectors.  The default should be all box's checked._

**Steps to Replicate:**
1. Login as an Inspector
2. Click the Inspection Tab found in Level 1
3. Click the QA Calendar Tab found in Level 2
4. Expand the search Panel
5. Current UI:
![image](https://user-images.githubusercontent.com/25441512/33495745-9ea3cd04-d695-11e7-9889-1c5bfdebe155.png)
6. Update to include checkboxes where all are checked
7. Future UI:
![image](https://user-images.githubusercontent.com/25441512/33495801-cf6e193a-d695-11e7-92cf-60cbcc7f19b2.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Appears to work correctly.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
appears correct

**Comment by HollySchuelerKCI** [comment]
This issue has been upgraded to status = "Ready for Production"

**Comment by Tad-Daniel** [comment]
Looks good.  issue can be closed
