### ISSUE TITLE
QA Toolkit - Liquidated Damages text cut off in Project Summery PDF

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#373]
Currently, when the user clicks the PDF button to generate the Project Summary, the liquidated damages text is cut off.

**Original Request via Email on 12/1/2017**:  _Liquidated damages in the project summary PDF are not showing up, the test extends beyond the far right page edge_.

Please update the report so that the text is no longer cut off.

![image](https://user-images.githubusercontent.com/25441512/33495910-3763b81a-d696-11e7-831f-cd98c01cb8a4.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
_This issue has been confirmed by the project stakeholder in the Development Environment.

This issue has been updated to status = "Ready for Staging"_

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been upgraded to status = "Ready for Production"

**Comment by Tad-Daniel** [comment]
Looks good, issue can be closed
