### ISSUE TITLE
QA Toolkit - Deleting SWM Submittal Produces an Unrecoverable Error Message

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#374]
**Tad has reported the system displays an "unrecoverable error" message when deleting an existing SWM submittal from Project #AT0445182.** 

**Please investigate this error further when attempting to delete a SWM Submittal in the Production Environment.**

The STAGING environment allows successful delete of SWM Submittals (no error msg), so it is not immediately clear whether the underlying issue may pertain to the specific Project # that has been noted. 

**Original Request via Email on 11/15/2017**:  _When attempting to delete a SWM submittal an unrecoverable error message occurs.  The SWM submittals on AT0445182 can be deleted in the production environment but the error prevent me from doing it._

![image](https://user-images.githubusercontent.com/25441512/33559897-3da6da70-d8dc-11e7-9549-5ae1f5269d18.png)

**Comment by vijme** [comment]
@Tad-Daniel, IS this issue specific to this submittal or for all SWM deletions in PRDN?

**Comment by Tad-Daniel** [comment]
appears to be working.

**Comment by Tad-Daniel** [comment]
I only tried to delete a specific SWM package as I did not want to effect something in an official review.  I believe it is for all SWM packages.

**Comment by vijme** [comment]
Issue fixed in production. While fixing, I had to delete one submittal from the above project.

**Comment by Tad-Daniel** [comment]
Issue fixed.  Seems to be working correctly now.

**Comment by Tad-Daniel** [comment]
working

**Comment by HollySchuelerKCI** [comment]
This issue has been upgraded to status = "Ready for Production"

**Comment by Tad-Daniel** [comment]
Working correctly.  Item can be closed
