### ISSUE TITLE
QA Toolkit - Search Panel Checkboxes are Misaligned in Small Window 

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#375]
Currently when the ESM Manager role is accessing the QA Toolkit in a small browser window, the Event Type Checkboxes are misaligned in the QA Calendar Search Panel.

Please note that this issue can only be replicated in IE 11.64.16299.0. Attempts to replicate this issue in Google Chrome and Mozilla Firefox were unsuccessful.

**Original Request via Email on 11/15/2017**:  _On the QA Calendar for the ESM Managers Role the search panel checkbox’s are misaligned and for the Inspector role they do not appear.  Also the calendar items do not appear for the Inspectors.  The default should be all box's checked._

**Steps to Replicate:**
1. Login as an ESM Manager
2. Reduce the browser window size
3. Click the QA Calendar tab in Level 2
4. Click the "+" to expand the Search Panel
5. Notice the checkboxes are misaligned

![image](https://user-images.githubusercontent.com/25441512/33560381-90cc549a-d8dd-11e7-9aff-e98468d59d57.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good, but my original issue with not vertical alignment but rather a horizontal alignment.  This is how they looked in my account at on time in the past.
![untitled](https://user-images.githubusercontent.com/7913678/33731689-f6cd6e98-db51-11e7-9c41-92823368080a.png)
If this type of alignment is excessive work then I can accept what you have now.

**Comment by vijme** [comment]
No problem. Implemented horizontal alignment in dev.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
appears correct

**Comment by HollySchuelerKCI** [comment]
This issue has been upgraded to status = "Ready for Production"

**Comment by Tad-Daniel** [comment]
Looks good and can be closed
