### ISSUE TITLE
QA Toolkit - Emails for Projects On Hold for More than 30 days are Not Working

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#376]
Tad has reported that emails for projects placed on hold for more than 30 days seems to not work.  This issue was created in GitHub Issue #226, and now seems to stop working entirely.

**Original Request via Email on 12/1/2017:** _New:  The emails for projects placed on hold for greater than 30 days seems to not work, we created this in with GiyHub issue 226 but now it seems to have stopped working all together._

Please investigate this error further as to why the system is not generating emails for projects placed on hold, referencing Issue #226 for further background.

**Comment by vijme** [comment]
@Tad-Daniel , the log messages for automatic emails in production shows the email has been sent. Please find the log for December 1, 2017.

2017/12/01 06:00:03
-------------------------------------------------------------- 
**********         Mod Notifications             ************* 
-------------------------------------------------------------- 
Notification sent for ModId 28041
-------------------------------------------------------------- 
**********    Project On Hold Notifications     ************* 
-------------------------------------------------------------- 
Notification sent for XY1345185:Modify/Installation/Reconstruction of Signing Districts 6 and 7 (GAP-OOTS)
Notification sent for AL4275130:Geometric Improvements US 220 at Louise Drive
Notification sent for AT0885182:TMDL Improvements, MD 32 and MD 100 Howard County, US 15 and MD 144 Frederick County District 7
Notification sent for HO2205129:Septic System Upgrades, Including Pump Station, Sewer and Force Main at the Administrations Shop in Howard County
Notification sent for FR3275184:MD-144 From West Royal Oak Drive to Bye Alley Community Safety Enhancement
Notification sent for FR6705175:US-15 at MD-77 Emergency Stream Repair
Notification sent for AT0905280:Invert Paving and Restoration of Various Structures (Statewide- Baltimore, Cecil, Frederick, Garrett, Harford, Prince Georges's, Queen Anne's, Talbot, and Washington Counties)
Notification sent for AW8965270:MD 404 Dualization West of 309 to Cemetry Road phase 1B
Notification sent for AT0905280:Invert Paving and Restoration of Various Structures (Statewide- Baltimore, Cecil, Frederick, Garrett, Harford, Prince Georges's, Queen Anne's, Talbot, and Washington Counties)
Notification sent for XX5275233:Sidewalk Project  Side Walk-ADA Project - Dist. 2 Area Wide
Notification sent for KE2955177:Md. 213, Md. 290 & Md. 313A at Corp. Limits of Galena-Proposed Resurfacing and Safety Improvements
Notification sent for XY1315185:Modification/ Installation/ Reconstruction of Traffic Signals in Districts 1 & 2 (GAP- OOTS)
Notification sent for MO1175177:MD RT 355 From Bradley Lane to MD RT 187
Notification sent for MO1175177:MD RT 355 from Bradley Lane to Montgomery Ave. - Safety & Resurface
Notification sent for MO5825180:Superstructure Replacement with Substructure Rehabilitation for Bridge # 1513600 on Maryland RT. 193 over I-495
Notification sent for MO6735174:US 29-RETROFIT OF SWM FACILITY 150173 AND SLOPE STABILIZATION
Notification sent for MO5335177:MD 355 from DC line to MD 191 (Bradley Lane) Safety and Resurface
Notification sent for AX9955178:Placement and replacement of concrete sidewalks, curbs and gutters throughout Montgomery and Prince George's counties
Notification sent for CL3695130:Geometric Improvements at MD-32 and MD-97
Notification sent for FR3275184:MD-144 From West Royal Oak Drive to Bye Alley Community Safety Enhancement
Notification sent for AT8725786:CCTV Deployment Phase 5C (GAP-OOTS)
Notification sent for XX5305176:Tree Trimming and Removal in Support of Capital Projects - Areawide
Notification sent for XY1315185:Modification/ Installation/ Reconstruction of Traffic Signals in Districts 1 & 2 (GAP- OOTS)
Notification sent for KE2955177:Md. 213, Md. 290 & Md. 313A at Corp. Limits of Galena-Proposed Resurfacing and Safety Improvements
Notification sent for XY1485176:Areawide  Safety and Operational Improvements In District 4 at Various Locations in Baltimore and Harford Counties Area Wide
Notification sent for HA4995177:US 40 East Bound from Long Bar Harbor Road. to Spesutia Rd.; Safety & Resurface
Notification sent for HA4265177:Md 924: From St. Claire Drive to Holly Wreath Court - Safety, Resurfacing and Minor Drainage Improvements
Notification sent for HA3485570:MD 22 @ Old Post Road Capacity Improvements
Notification sent for CE3265177:US 40 from structure 701 over Big Elk Creek to Delaware Line-Resurfacing and safety improvements
Notification sent for HA2425180:Prestressed Concrete Slab Bridge No.12009 on MD 7 over James Run in Harford County
Notification sent for HA3515176:Widening and Resurfacing I-95 Northbound Off Ramp at MD 543
Notification sent for HA4075182:Stream Restoration on Plumtree Run along MD 24 from SHA structure #12088 to structure #1208700 in Harford County
Notification sent for HA1075176:Safety & Spot Improvements WB US 40 Parking / Service Road; Between MD 132 & Robinson Ave.
Notification sent for CE4465180:Replacement of Bridge No. 07036 on MD 272 over AMTRAK
Notification sent for BA0595177:US 40 (Pulaski Highway) from Todds Lane to Md 700 (Martin Boulevard)  Safety and Resurfacing
Notification sent for AT0905280:Invert Paving and Restoration of Various Structures (Statewide- Baltimore, Cecil, Frederick, Garrett, Harford, Prince Georges's, Queen Anne's, Talbot, and Washington Counties)
Notification sent for XX2255480:Preservation and Minor Rehab of moveable bridges, fixed bridges, soundwalls, culverts, retaining walls statewide (GAP-SIRE)
Notification sent for MO6735174:US 29-RETROFIT OF SWM FACILITY 150173 AND SLOPE STABILIZATION
Notification sent for CE2895177:From Md 273-A to the Pennsylvania Line
Notification sent for WI3285674:US 13 Business- Drainage Improvements from N. of South Boulevard to N. of Calvert Street (Phase 6), City of Salisbury
Notification sent for MO4575280:Cleaning and Painting of Existing Bridge Nos. 1508100, 1508500, 1508600, 1508700, 1509203, 1509204, 1512200 and 1512300 on Various Routes in Montgomery County
-------------------------------------------------------------- 
**********    3 and 6 Month Permit Notifications ************* 
-------------------------------------------------------------- 
Notification sent for 15-PR-0004
Notification sent for 12-SF-0154
-------------------------------------------------------------- 
**********    YCERT Notifications **************************** 
-------------------------------------------------------------- 


-------------------------------------------------------------- 
**********   18 Month Permit Issual Notifications ************ 
-------------------------------------------------------------- 
Notification sent for 15-PR-0004




I have also received the following email on 12/1/17.
![image](https://user-images.githubusercontent.com/6668314/33806196-43f6b552-dd92-11e7-9b89-304dc35ff490.png)




Can you please confirm if you haven't received any emails at all, or was there any specific project that was expected that was received. That would help me further investigate this issue. Thank you

**Comment by Tad-Daniel** [comment]
I'll get you more info.   Most of my team said they did not get any emails, but a few said they did.

**Comment by slmessier** [comment]
## Update after 1/3/2018 meeting including all team members:
@vijme @HollySchuelerKCI @Tad-Daniel
### Additional Background Detail:

- Tad indicated he is unable to verify when the user places the job on-hold, whether the user receives notifications at 30 days then again the following months.  
- Tad confirmed that all users are configured properly and he will look into the possibility of email filtering.
- Tad noted that the Inspector places a job on-hold, and is the only user who receives notifications. 
- Once the job is placed on hold, an initial notification is sent, then the system should send future notifications at regular intervals to the Inspector. 
- The Notification Log currently does not track the on-hold notifications

### Development Action:
**Please update source code to log all email notifications sent via the system within the Notification Log.
This will provide the ability to examine the Notification Log for confirmation of all notifications, including the applicable On-Hold 30+ days alert.**

This work is to be performed against under Task 17.

**Comment by vijme** [comment]
Automatic emails are now logged in notifications. This issue cannot be verified in dev, but can be viewed in the notifications tab in dev. Can be implemented in production whenever instructed.

**Comment by Tad-Daniel** [comment]
Sounds good.  Lets push it out before the end of the month.  If we can include the other bug fix in the same rollout that will be good

**Comment by vijme** [comment]
This enhancement is a different standalone code and has been implemented in production.

**Comment by Tad-Daniel** [comment]
Thanks

**Comment by slmessier** [comment]
Hi @Tad-Daniel I have assigned this item to you as the system has been updated to document the notification deliveries to support your additional analysis. 

Our team will wait to hear from you next on the matter. I'll leave it open to support, but otherwise we will assume the issue needs no additional action until further instructed.

**Comment by Tad-Daniel** [comment]
SHA QA is updating the information in the toolkit as discussed in the most recent meeting.  I will provide additional updates on the first of March.

**Comment by Tad-Daniel** [comment]
It appears that everything is working as designed.  This issue can be closed out.
