### ISSUE TITLE
QA Toolkit Task 18 - Progressive Scheduling System - Automation Logic - 3 Cases of Intervals 

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#378]
### Enhancement Specification Overview
**The dates represented for all QA1 Inspection Deadlines within the system will be automatically determined by the system using one of the 3 following logical cases described below:**

**Note:** this issue describes the intended state of the system after enhancement, to support quality assurance testing during and after the development stage. **Specifications listed within this issue do not apply directly as updates to elements of the User Interface.**

### (3) Cases of Intervals
1. **Manually Determined Interval (2 weeks, 3 weeks, etc)** - user defined; exists currently; **no additional enhancement needed at this time**
![image](https://user-images.githubusercontent.com/4098544/34788530-daf10f00-f608-11e7-9cf6-4061242f4eb5.png)

2. **Progressive Scheduling - Default Interval** - inspection interval is based on the _existence of project incentives_
![image](https://user-images.githubusercontent.com/4098544/34788568-ef867554-f608-11e7-9d79-55aceafabd35.png)

3. **Progressive Scheduling - Failed Inspection Interval** - inspection interval is based on the _analysis of recent inspection grades_
![image](https://user-images.githubusercontent.com/4098544/34788584-028d083e-f609-11e7-8142-dc0ea2224dc8.png)

_Tracking Note: this issue was developed through discussion regarding specification originally requested as **Nos. 1 thru 4 within the Task 18 Scope of Work Agreement**, and as referenced within GH issue #377 of this repository._

**Comment by vijme** [comment]
Implemented in dev

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team and confirmed by the stakeholder. This issue is ready for staging.

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the stakeholder and is ready for Production.

**Comment by Tad-Daniel** [comment]
Currently testing in production on Project MD8675309

**Comment by Tad-Daniel** [comment]
Appears to be working well in production  Issue can be closed

**Comment by Tad-Daniel** [comment]
Item completed
