### ISSUE TITLE
QA Toolkit Task 18 - Progressive Scheduling System - Automation Logic - Chronology of System Checks

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#379]
### Enhancement Specification Overview
**The full chronology of system checks below represents the system logic that will be automated to provide the specified Progressive Scheduling functionality. For each of the (2) applicable cases:** 

1. "_Default Interval"_ 
AND
2. _"Failed Inspection Interval"_.

**Note:** this issue describes the logical routine that will be automated by the system after enhancement to support quality assurance testing during and after the development stage. **Specifications listed within this issue do not apply directly as updates to elements of the User Interface.**

### Chronology of System Checks
**Logical Diagram:**
![image](https://user-images.githubusercontent.com/4098544/34792730-f9b62e12-f616-11e7-831b-c05b4c6ccc9d.png)

**Logical Description (Text):**
![image](https://user-images.githubusercontent.com/4098544/34792901-8efae792-f617-11e7-8a10-f731ab2c4a88.png)

_Tracking Note: this issue was developed through discussion regarding specification originally requested as **Nos. 1 thru 4 within the Task 18 Scope of Work Agreement**, and as referenced within GH issue #377 of this repository._

**Comment by vijme** [comment]
@Tad-Daniel, Is it possible that a draft inspection with Grade "C" be saved again as Final or Draft again, with Grade "B" or "A". In that case, the first save with a grade "C" would have caused a schedule change, while the second or subsequent save for the same inspection might not be able to change the schedule back again die to the grade. I'm afraid that we may need to restrict the schedule update only for final inspections. Please suggest. Thanks

**Comment by Tad-Daniel** [comment]
That is a possibility.  In the current system the schedule seems to handle this scenario as I have seen it move the dates as the inspections adjust grades.  **If the restriction is necessary then it is acceptable.**

Thinking about it this may benefit us in the respect that if an inspector fails to finalize a report it will stay in the top of their schedule and be brought to their attention..

**Comment by vijme** [comment]
@Tad-Daniel, thanks for clarification. The system will include drafts also. I just need one last clarification. The test for reverting back to the normal schedule is "A" in the last inspection, proceeded by 3 inspections with "A", which makes the total "A" to be 4. Shouldn't 3 A grades revert to a normal schedule instead of 4?

**Comment by vijme** [comment]
It will be 3 "A", instead of 4. Implemented in dev

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team and confirmed by the stakeholder. This issue is ready for staging.

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Working correctly

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the stakeholder and is ready for Production.

**Comment by Tad-Daniel** [comment]
Currently testing in production on Project MD8675309

**Comment by Tad-Daniel** [comment]
Appears to be working well in production  Issue can be closed

**Comment by Tad-Daniel** [comment]
Item completed
