### ISSUE TITLE
MDE Toolkit - Unable to Upload PDF to Permit

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#381]
Lindsay Forrester reported that users are unable to upload PDFs under a permit in the MDE Toolkit.

**Original Request via Email on 1/22/2018:**
_We are having issues uploading pdfs under a permit in toolkit. The error message in the picture below pops up whenever we try to upload the modification PDFs under the MD 404 permit. Is there a way this can be fixed? Please let me know if you need any additional information. Thank you!!_

A couple questions to follow up that will help us to investigate….
1. Are you able to upload PDF’s for other projects? **Yes, we uploaded permit pdfs under two other projects and it worked fine. We tried again to add a modification under the MD 404 project and it did not work.** 
2. Do you encounter the same issue for multiple PDF files? Or are you having trouble with a particular file exclusively? **We tried to upload several pdf files under MD 404 and none of them worked.**
a. How large is file size of the PDF(s)? **The file sizes of modifications we are trying to upload range from 65KB to 3,300KB.** 
b. Could you send over example(s)? **Three examples of pdfs we have tried to upload are attached.** 

![image](https://user-images.githubusercontent.com/25441512/35236182-5eb747e0-ff74-11e7-99db-502614372031.png)

[Permit Modification_MD 404 Dualization_signed.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1653048/Permit.Modification_MD.404.Dualization_signed.pdf)
[MD 404_Signed Permit Mod 6 Package.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1653051/MD.404_Signed.Permit.Mod.6.Package.pdf)
[Modification4_Signed_MD 404.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1653052/Modification4_Signed_MD.404.pdf)

**Comment by slmessier** [comment]
@vijme could you please investigate at your earliest convenience? thank you!

**Comment by vijme** [comment]
@slmessier, i tried to upload one of the above file (Modification4_Signed_MD 404.pdf) and was hoping to see an error. But the file uploaded without any issues.. I uploaded through the document subtab and through permit subtab under the 2007-08723/2008 permit, and the document uploaded without any issues. I also tried using to "Permit Reviewer" and "Project Manager" permissions.  If problem persist, I would like to get more information on exactly which sequence gave an error. 

On a separate note, clicking the "Permits" 2nd level tab gave an error as a "project manager", which was fixed.

**Comment by slmessier** [comment]
**From: Scott Messier 
Sent: Monday, January 29, 2018 2:39 PM
To: 'Forrester, Lindsay D.' <ldforrester@mccormicktaylor.com>**
Cc: 'Dolbin, Emily B.' <EBDolbin@mccormicktaylor.com>; 'Cheryl Jordon (SHA)' <CJordon@sha.state.md.us>
Subject: RE: Toolkit issue - MD 404 permit mod error

Hi Lindsay,

**I have manually uploaded each of the PDF’s as documents on the Documents Subtab for the project. I was able to succesfuly upload each document, however the attribute information for each still requires updating (see below).**

Please review and update as needed. Does this provide you with the system information you were looking for? **Please advise / confirm – thank you!**

 ![image](https://user-images.githubusercontent.com/4098544/35530528-53df80e2-0502-11e8-848f-b3ef8ac284c3.png)

**Comment by slmessier** [comment]
### Reported Steps to Replicate from User below:
From: Forrester, Lindsay D. [mailto:ldforrester@mccormicktaylor.com] 
Sent: Friday, February 2, 2018 10:30 AM
To: Scott Messier <Scott.Messier@kci.com>
Cc: Dolbin, Emily B. <EBDolbin@mccormicktaylor.com>; Cheryl Jordon (SHA) <CJordon@sha.state.md.us>
Subject: RE: Toolkit issue - MD 404 permit mod error

Hi Scott, 

See below!

-click on “Reviews” tab
-Use “Reviewer” and “Project” to find the project
-click on the pencil icon to edit
- click the project name
- click “Permits” tab
- click pencil icon for 15-NT-2086/201561418, MDE Water Management Administration, Nontidal Wetland and Waterways Permit
- click “upload permit document” underneath the original permit
- Fill out as follows:
               -Document Type- Other
               -Description- Modification 1_MD 404_AW896
               -Label- Modification 1
               - Choose the file (65 KB)
               -Insert today’s date
-click “Add Attachment” bottom
-Get error screen

**Comment by vijme** [comment]
@HollySchuelerKCI  @slmessier I still don't get the error following the above steps.  Please find the snapshot of one of files uploaded in production without any issues. Are you getting the error from your end following the above steps? (You may please delete the file if needed)


![image](https://user-images.githubusercontent.com/6668314/36040477-88aee5c6-0d93-11e8-8cae-1deadd7fc0e8.png)

**Comment by vijme** [comment]
Ok, please disregard the last one. Here is the issue. This specific permit has 51 conditions associated to it, which is more than the limit for paging implementation. Please refer the earlier issue in GitHub which details about it.

https://github.com/kcigeospatial/sha_oed_issues/issues/278

**Comment by HollySchuelerKCI** [comment]
**Email from Cheryl Jordan on 4/5:**

From: Cheryl Jordon (SHA) [mailto:CJordon@sha.state.md.us] 
Sent: Thursday, April 5, 2018 2:11 PM
To: Scott Messier <Scott.Messier@kci.com>
Cc: Tad Daniel <tdaniel@sha.state.md.us>; 'Emily Dolbin -MDE-' <emily.dolbin@maryland.gov>; Forrester, Lindsay D. <ldforrester@mccormicktaylor.com>
Subject: RE: Toolkit issue - MD 404 permit mod error

_Sorry for the late response.  I think the work around solution of keeping to 50 or fewer conditions makes the most sense at this time. We want to concentrate our limited funding on completing more critical tasks prior to the deadline for migrating the application to SHA’s servers.  I asked our consultants to just combine conditions when necessary and that seemed to work.  Thanks for checking.  Cheryl_

The status of this issue = **Closed**
