### ISSUE TITLE
QA Toolkit - Deleted Project due to Duplication

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#384]
**Original Request from Tad via Email on 2/7/2018:**
Can you guys look into a deleted project for me

The Project number is XY1655185.  I just deleted it and here is what happened.

We found a duplicate record in the system for this project and as I went through each one it appeared they were identical in every respect even down to the QA reports.  I chose not to merge them and have duplicate reports in the record and decided I would delete one of the project records.  Turns out when I deleted one of them the other went away also.  

Let me know what you guys find and can you recover it for us.  Attached is the project summary from the system prior to deletion.

**Comment by HollySchuelerKCI** [comment]
**Original Request to Viji from Scott Messier:**
Hi Viji – do you have a method to restore the project Tad is referencing below? If not a restore, is there another method by which we could retrieve the project information?

Let me know your thoughts on what is feasible – thank you!


**Response from Viji regarding the deleted project:**
The project cannot be restored, since it is deleted from database. However due to current deletion method, only the project record is deleted. Other information is still in the system. So we can recreate this entry in the database using the available information from the pdf. 

The project will be back in the list and then on, the user can validate and save with updates if any.

**Comment by HollySchuelerKCI** [comment]
**Request to recreate the entry in the database on 2/14/2018:**
Thanks Viji – are you able to recreate the entry in the database so that the Inspection records will once again link? 

Is this something that you can do on the development end, or do you require assistance prior to testing from Holly?

**Response from Viji:**
Hi Scott,

Can you open a task for this item? I have all the details for inserting the project record from the pdf that was sent, except the Stage. I will default to “Construction”, and will be the only one to be changed by Tad if necessary. 

Thanks,
Viji

**Comment by HollySchuelerKCI** [comment]
@Tad-Daniel  Viji was able to restore the project back into Production however the following values were not available to her from the PDF and need to be updated.

1. Stage
2. Team Index
3. Centroid N
4. Centroid E
5. Centroid dropdown

If you would prefer us to make the update, please advise and we would be happy to do so.

**Comment by vijme** [comment]
@Tad-Daniel, below are the findings for the duplicate entry of this project in the project grid

This project has a record for an inspection with grade "A", and also a record for skipped inspection with the reason "Inspection Resumed" both at the same time, to the precision of second on 01/25/2018 at 14:46:00.  I have tested all parts of the code where the skipped justification record is created,  but unable to replicate the same time to the seconds precision for both a valid inspection record and skipped justification record, even with multiple browser session running in parallel.  

May I request you to detail the steps that was followed during saving this inspection, if you remember.

**Comment by Tad-Daniel** [comment]
The project is back, Thanks

I can not elaborate on the steps in saving the inspection.  Currently the system again show duplicate projects. They are identical and a change in one causes a change in the other Would deleting the skipped inspection resolve this issue?
![image](https://user-images.githubusercontent.com/7913678/36592067-36b7d938-1862-11e8-9a98-4157b741f815.png)

**Comment by vijme** [comment]
Yes, deleting can resolve the issue, but I believe simply re-saving the skipped inspection record itself might also work. (BP/SS->SkippedInspections->edit record->save)

![image](https://user-images.githubusercontent.com/6668314/36599462-726d076c-187d-11e8-8093-9f8813925035.png)

Please let me know if the issue is resolved. Thanks.

**Comment by Tad-Daniel** [comment]
Yes re-saving the justification resolved it.    Now that's one for the books.

Thanks

**Comment by Tad-Daniel** [comment]
This issue is resolved and can be closed
