### ISSUE TITLE
QA Toolkit - Update Modification Response Character Length

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#386]
### Please increase character limit for the Modification Response text field on the Modification Response Page:
1. Increase text limit in DB and UI
2. Update Text Label to reflect the new limit

### Example
![image](https://user-images.githubusercontent.com/4098544/36922581-57495c7e-1e36-11e8-897b-b67ce34c9451.png)

### Original Request
Email from T. Daniel 3/2/2018
![image](https://user-images.githubusercontent.com/4098544/36922453-d9bbba7c-1e35-11e8-8c39-6324032bef1a.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by the stakeholders.  This issue is ready for Staging.

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
The interface looks good but I did put in the max number of characters and it appears that the text on the summary sub-tab is not wrapping, the text goes way off screen to the right. It is also happening in the associated email.  I do not recall this from the development env but its happening there also now.

Test in both IE and Edge on win 10

See project AA1545180 in Staging

**Comment by slmessier** [comment]
The previously noted wrapping issue was due to the long word without space. A space between word successfully wraps according to specs. (passed testing in STAGING)

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the stakeholder and is ready for Production.

**Comment by Tad-Daniel** [comment]
Everything looks good in production, Issue closed
