### ISSUE TITLE
QA Toolkit - Adjust QA Concurrence Request & Response Character Length

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#387]
### Please adjust character limits for the QA Concurrence Text:
1. Adjust text limit in DB and UI
2. Update Text Label to reflect the new limit
3. Update for each applicable QA Concurrence page (Request & Response):
    - QA Request Page (currently 1000 characters)
    - QA Response Page (currently 500 characters) 

### Example
Request Page:
![image](https://user-images.githubusercontent.com/4098544/36922827-449186fa-1e37-11e8-8c6a-4ca31dbf2826.png)
Response Page:
![image](https://user-images.githubusercontent.com/4098544/36922939-9bdd1082-1e37-11e8-9602-387dce0bb3ae.png)
### Original Request
Email from T. Daniel 3/2/2018
![image](https://user-images.githubusercontent.com/4098544/36922962-b0dfa3b4-1e37-11e8-8d2c-f5505099a0c5.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by the stakeholder. This issue is ready for staging.

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
The interface looks good but I did put in the max number of characters and it appears that the text on the summary sub-tab is not wrapping, the text goes way off screen to the right. It is also happening in the associated email.  I do not recall this from the development env but its happening there also now.

Test in both IE and Edge on win 10

See project AA1545180 in Staging

**Comment by vijme** [comment]
The problem is due to the long word without space, a space between word would wrap it.

**Comment by Tad-Daniel** [comment]
AH,  My bad.

I re-checked and looks good.  Thanks

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the stakeholder and is ready for Production.

**Comment by Tad-Daniel** [comment]
Everything looks good in productions.  Issue Closed
