### ISSUE TITLE
QA Toolkit - Update SWM As-Built Section

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#388]
# Enhancement Specification Overview
The following material represents the SWM As-Built Section updates as outlined in Task 19 SOW.

## SWM As-Built Section Updates
The stakeholder would like to make the following two (2) updates to the SWM As-Built Section:

1. Include functionality for a 2-week email reminder for idle submittal in SWM system like with a modification
2. Add “Help” button in the SWM AB page that links to a reference document just like the Mods and QA concurrence pages.

![image](https://user-images.githubusercontent.com/25441512/38096191-45a2c5c2-3340-11e8-9c65-f047be8a30b2.png)

**Comment by vijme** [comment]
Please provide Additional information for point 1 above:
1. How is an Idle submittal determined? 
- Is it > 14 days from a previous response just as in MODS?
- Is the submittal request in any of the approval status except Approved (Contractor-Presubmittal, District-Pending, and HHD-Under Review) need to be considered?

**Comment by Tad-Daniel** [comment]
Yes and Yes

Any state except Approved, >14 days from a previous response.

**Comment by vijme** [comment]
SUBJECT: AUTOMATIC REMINDER: SWM As-Built 1 for Project 000000001 - Test- mod requests
![image](https://user-images.githubusercontent.com/6668314/38274145-d8bef2b2-375b-11e8-8b45-b07836660f16.png)

**Comment by vijme** [comment]
Implemented in dev. Cannot be tested in dev. Please find the sample email above for any changes.

**Comment by vijme** [comment]
For item 2, the corresponding pdf has to be added through Admin-> Standard Forms, under the specific name "SWM Instructions". I have added some random file for now. That entry can be edited to upload the correct document. But as in MODS, the name "SWM Instructions" must not be changed. In other words, "HELP" button will be displayed only if there is an entry named "SWM Instructions" under Standard Forms.

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
For the above 2 week automatic email notification, this functionality can not be thoroughly tested in the Staging Environment. However, please note that the admin user may click Admin->Notifications to view that 2 emails did successfully send to recipients. 

@Tad-Daniel please validate this functionality at your earliest convenience in the Staging Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by the stakeholder in the Staging Environment.

The updated status of this issue = _Ready for Production_

**Comment by vijme** [comment]
For SWM instructions, please send the document for us to upload or you can edit the existing ones with the actual document. The document was not uploaded properly the first time.

**Comment by Tad-Daniel** [comment]
here is the document

[SWM_Instruction.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1964944/SWM_Instruction.pdf)

**Comment by Tad-Daniel** [comment]
The help button appears when you guys upload it but as soon as I upload a new version with the exact same name the button goes away and nothing I do will bring it back.

**Comment by vijme** [comment]
I find the name in production to be "SWM_Instruction". I guess the system is looking for the name "SWM Instructions"

**Comment by vijme** [comment]
I guess the system is looking for the name "SWM Instructions"

**Comment by vijme** [comment]
The actual document name can be anything. But the name of the entry in the system must be changed. Please see the image where the name needs to be changed (highlighted in yellow). Thanks,

![image](https://user-images.githubusercontent.com/6668314/39764141-f7886496-52ac-11e8-8406-0588a86c924d.png)

**Comment by HollySchuelerKCI** [comment]
## Per Stakeholder Request # 1- Include Functionality for 2-week Email Reminder for Idle Submittal

An issue arose once deployed into production, where the system notified all active users with SWM As-Built Rep Permissions. This relates to the permissions set in _Task 11, GitHub Issue #279_ 

![image](https://user-images.githubusercontent.com/25441512/39828806-5ac9d5c0-538a-11e8-875c-0a4ded2f4b41.png)

Under new requirement, SWM As-Built Reps and Approvers will be emailed only if they are users to the project.  This will impact both the normal system flow (during SWM request and response save) and automatic notifications flow. Please confirm from the stakeholder if we are good to implement the change.

**Comment by HollySchuelerKCI** [comment]
The project team verified the following in the **_Notification Log of the Production Environment_**:

### Project:
AUTOMATIC REMINDER: SWM As-Built 1 for Project AX7665582 - TMDL, SWM Retrofit Group 1 Wash County

### Sent: 
5/9/2018

### Recipients: 
Bittinger, Chunca <CBittinger@sha.state.md.us>
Finney, Ricky <RFinney@cwilliamhetzer.com>
Bucy, Stephen <sbucy@sha.state.md.us>
Daniel, Tad <TDaniel@mdot.state.md.us>

![image](https://user-images.githubusercontent.com/25441512/39829007-0f476436-538b-11e8-9da9-05a290c4f7f8.png)

**Comment by slmessier** [comment]
@Tad-Daniel please use the above information to research the validity of the intended functionality. Please comment and close accordingly, should you feel it is appropriate at this time. Thank you!

**Comment by Tad-Daniel** [comment]
So here is what I see now.

Tested in production on project MD8675309

The 2 week notification issue appears to be working correctly but not the initial notification.  When I create a new submittal the notification goes to all those with District approver status but it should only go to the one assigned to the project.

No notifications should go to anyone that is not assigned to the project.

**Comment by vijme** [comment]
Yes, the above fix was implemented for automatic email notifications only. The initial notifications have been fixed in dev.  Will be available in production during the next release.

**Comment by Tad-Daniel** [comment]
I just tried it in development and it appears to be working as expected.  Will continue testing over the weekend.

**Comment by Tad-Daniel** [comment]
This item should be resolved with the next update.

**Comment by Tad-Daniel** [comment]
So far all seems to be working correctly.  HHD has requested a change in the timeframe from 2 weeks to 4 weeks.  Please make adjustment to timeframe and to the email text.

**Comment by Tad-Daniel** [comment]
All appears to be working expect please verify that all the correct names appear in the stakeholder field of SWM response page.
![image](https://user-images.githubusercontent.com/7913678/41237443-7c143180-6d61-11e8-889d-145978805a60.png)

Also, HHD has requested that the timeframe for the automatic email be 4 weeks instead of 2.  Please adjust timeframe and email accordingly.

**Comment by slmessier** [comment]
@Tad-Daniel - can this issue be closed with the existence of #414 which will address adjusting the interval to 4 weeks ?

**Comment by Tad-Daniel** [comment]
Item completed
