### ISSUE TITLE
QA Toolkit - Update Modification Section

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#389]
# Enhancement Specification Overview
The following material represents the Modification Section updates as outlined in Task 19 SOW.

## Modification Section Updates
The stakeholder would like to make the following five (5) updates to the Modification Section:

1. Remove “In Development” and “Additional Information Required” options in Modification dropdown menu and associated areas of the system
![image](https://user-images.githubusercontent.com/25441512/38101875-973ef7b6-334f-11e8-9642-1148021ed37e.png)

2. Move “MDO #” to far left of information Box over the top of the user’s name and increase font size.
![image](https://user-images.githubusercontent.com/25441512/38102450-41cb6560-3351-11e8-8d32-c8026c415c9d.png)

3. In Mods response screen make the approver list 2 columns
![image](https://user-images.githubusercontent.com/25441512/38102503-74feb234-3351-11e8-967e-4636a597e679.png)

4. Have plans sheet numbers wrap in the sub-tab grid
5. Add division designation to web page like it is shown in the e-mails (submitted for review by….)
 - The stakeholder would like to show the division designation in the grid under the subtab. See Screen shot below explicitly stating that the Request Status: "**_Submitted for Review by QA_**". If it is multiple divisions, then they would be separated by a comma, "**_Submitted for Review by HHD, EPD_**"

![image](https://user-images.githubusercontent.com/25441512/38442198-8d63f234-39b5-11e8-9cbd-2b1b8b39dd8a.png)

**Comment by vijme** [comment]
For item 4 above (Plan sheet numbers wrap up in grid), please let me know your preference.

- The plan sheet number will wrap up normally when the letters are spaced out. 

When there is no space between the plan sheet letters, we have two options

1. Specify a maximum width so that the next column of the grid will appear after the width irrespective of the text.
![image](https://user-images.githubusercontent.com/6668314/38384204-8aca17d0-38dc-11e8-8456-e3a8e20901dc.png)

2. Not specify any width and allow it to run full (50 characters max) so the next column will appear after all its length.
![image](https://user-images.githubusercontent.com/6668314/38384522-61ffa47c-38dd-11e8-865d-b86955d9f979.png)

**Comment by Tad-Daniel** [comment]
neither option is good so leave it as is

**Comment by HollySchuelerKCI** [comment]
@vijme  For Sub-Item #5 - Confirmation from stakeholder received via email on 4/6. Please refer to the above updated specifications for clarification.

**Comment by vijme** [comment]
@HollySchuelerKCI , The above comment is for subitem 4. Can you please provide additional details on Subitem 5?

**Comment by vijme** [comment]
Implemented in dev.

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team and confirmed by the stakeholder in the Staging Environment.

The updated status of this issue = _Ready for Production_

**Comment by Tad-Daniel** [comment]
Help button issue that has appeared with most recent issue is same as SWM section.
The help button appears when you guys upload it but as soon as I upload a new version with the exact same name the button goes away and nothing I do will bring it back.

**Comment by Tad-Daniel** [comment]
This issue has been resolved. I just verified tht everything is working correctly
