### ISSUE TITLE
QA Toolkit - Login Analysis Menu - Erroneous Code Snippet Displayed

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#39]
The system currently displays a code snippet (that appears to be a system error message) when the "Login Analysis" screen is displayed.

![image](https://cloud.githubusercontent.com/assets/4098544/3446011/abffa162-013c-11e4-943d-38222e56d757.png)

Steps to replicate:
1. click on Admin --> Login Analysis Menu

**Comment by Tad-Daniel** [comment]
This issue has been corrected.  Issue closed.
