### ISSUE TITLE
QA Toolkit - Adjust Email Text for the Email Notification System

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#393]
# Enhancement Specification Overview
The following material represents the enhancement to the email text as outlined in Task 20 SOW.

## Adjust Email Text for the Email Notification System
Original request by the stakeholder:
-  On the email for a new modification request, change the “By package approver:” to just say “by:”

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
The screenshot below represents the updated text as requested by the project stakeholder:

![image](https://user-images.githubusercontent.com/25441512/40078903-0bfc89e6-5854-11e8-8e2a-b7d0b3a7eb93.png)


This issue will be fully tested in the **_Staging Environment_** where email functionality is implemented.

@Tad-Daniel please confirm the above text is acceptable.

**Comment by Tad-Daniel** [comment]
Yes, Looks good

**Comment by HollySchuelerKCI** [comment]
This _text_ of this issue has been validated by the project team and confirmed by the stakeholder. The email notification will be fully tested in the Staging Environment.

The status of this issue is "Ready for Staging"

**Comment by Tad-Daniel** [comment]
Appears to be working in staging

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Issue complete
