### ISSUE TITLE
QA Toolkit - Project Record Changes - Restrict Editing Ability on Fields

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#394]
# Enhancement Specification Overview
The following material represents the Project Record Changes as outlined in Task 20 SOW.

## Project Record Changes
The stakeholder would like to restrict the ability to edit the following fields only from the project record, exclusively for the “_inspector_” system role. 

The following project record fields will be editable by an Inspector; all other fields will not be editable.

1. Project Rep.
2. ESC Manager
3. Superintendent
4. FMIS
5. Comments

**Comment by vijme** [comment]
Implemented in dev

**Comment by Tad-Daniel** [comment]
Disable the checkbox as it does not prompt them to put in a justification.

I have another question,  in my manager account I can add an inspection from within the sub-tub for QA Inspections.
![image](https://user-images.githubusercontent.com/7913678/40076382-bd7b62d0-584c-11e8-98e7-fab1c62341f9.png)
Can we make this button available for the inspectors also?

**Comment by Tad-Daniel** [comment]
Lets go with the implimentation now and adjust later if needed.

Allow add, edit and delete

**Comment by vijme** [comment]
Inspector Role allowed for full access on QA Inspections Tab

**Comment by Tad-Daniel** [comment]
Looks good.  We will adjust later.

**Comment by HollySchuelerKCI** [comment]
The project team validated the following and confirmed by the stakeholder:

- The following project record fields will be editable by an Inspector; all other fields will not be editable.

1. Project Rep.
2. ESC Manager
3. Superintendent
4. FMIS
5. Comments

- The Inspections on Hold Checkbox has been disabled
- The Inspector Role has full access to the QA Inspections SubTab

The status of this issue is "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team.

**Comment by Tad-Daniel** [comment]
looks good in staging

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Issue complete
