### ISSUE TITLE
QA Toolkit - Project Record Changes - Extend Width of Comments Input Field

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#395]
# Enhancement Specification Overview
The following material represents the enhancement to the width of the Comments input field as stated in the Task 20 SOW.

## Extend Width of Comments Input Field
The stakeholder would like to extend the width of “Comments” text input field so that the right side is aligned with the right side of the Yellow Card Exp Date field(s).

![image](https://user-images.githubusercontent.com/25441512/38137820-0d7a4dd6-33f5-11e8-95dc-160db4b12b68.png)

**Comment by vijme** [comment]
Implemented in dev.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team.

**Comment by Tad-Daniel** [comment]
Looks good in staging

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Item completed
