### ISSUE TITLE
QA Toolkit - QA-1 / QA-2 Updates

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#396]
# Enhancement Specification Overview
The following material represents the common updates to QA-1 and QA-2 as outlined in Task 20 SOW.

## QA-1 and QA-2 Updates

1. The stakeholder would like to update data targets within QA1 Inspection PDF report to retrieve data values defined by the user, rather than those that are pre-populated by the system from the project record. (Currently the report appears to retrieve values from the related project record exclusively, and does not account for the case when each may have been overwritten manually by an authorized user.)

     - Contractors ESCM
     - SHA Project Representative

![image](https://user-images.githubusercontent.com/25441512/38138468-219ec0ae-33f9-11e8-970c-b83b383903dc.png)

![image](https://user-images.githubusercontent.com/25441512/38138799-ad758e86-33fa-11e8-939c-9b1611d59301.png)

2. Adjust QA-1 PDF so that section 6 does not break over onto page 5

**Comment by vijme** [comment]
SHA project representative did not need any change. Contractor ESCM was fixed to show updated name from QA-1.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good in DEV

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder.

The status of this issue is "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Staging Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Item complete
