### ISSUE TITLE
QA Toolkit - Update QA Project Inspection by Date Report (QA-2 Bulk report)

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#398]
# Enhancement Specifications
The following material represents the enhancement to the QA Project Inspection by Date report as stated in the Task 20 SOW.

## Updates to the QA Project Inspection by Date report(QA-2 Bulk report)

1. **Develop functionality to perform a bulk dump of QA-2 reports** as is available currently for QA-1 inspections. Leverage the existing UI controls and enhance.  
2. **Develop a new dropdown menu that will allow users to select “Inspection Type” (QA1 or QA2) as a report parameter**. The system will generate a bulk inspection report for QA1 or QA2 inspections according to the user-defined parameter.

![image](https://user-images.githubusercontent.com/25441512/38141281-5937e4c6-3405-11e8-9400-9e9487bc5471.png)

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Development Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the stakeholder.

The status of this issue is "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Working correctly in staging

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Item completed
