### ISSUE TITLE
QA Toolkit - Add Capability to Search Query for Projects Not Started

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#399]
# Enhancement Specification
The following material represents the enhancement to add the capability for the user to search query for projects not started as stated in the Task 20 SOW.

## Add Capability to Search Query for Projects Not Started

1. For the Projects List search filters, **_add the capability to search query for projects not started_** in the project grid (have not had a first inspection)

     - Add new search filter parameter as a check box for “Projects not Started” which would return filtered results.

![image](https://user-images.githubusercontent.com/25441512/38141371-c41b7690-3405-11e8-824e-530485f97f32.png)

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder.

The status of this issue is "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Working well in staging

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Item completed
