### ISSUE TITLE
QA Toolkit - Automatically Associate a New Project to All Users with (2) Roles

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#400]
# Enhancement Specification
The following material represents the enhancement update system functionality to automatically associate a new projects to all users with (2) roles “Power Reviewer” AND “ESC Manager” as stated in the Task 20 SOW.

## Automatically Associate a New Project to All Users with (2) Roles

1. Update system functionality to automatically associate a new projects to all users with (2) roles “Power Reviewer” AND “ESC Manager” at the point at which the new project is created (Save Project).

     - Test post-development functionality by validating the new project automatically shows in “Assigned Projects” of User Details menu for an applicable user.

![image](https://user-images.githubusercontent.com/25441512/38141726-89227c08-3407-11e8-9cf4-882f9baa167f.png)

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
working correctly in staging

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Item completed
