### ISSUE TITLE
QA Toolkit - Update to Email Notifications: SWM As-Built Related Emails

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#403]
Please **update the automatic system email functionality related to SWM As-Built workflow, to send emails only to the users associated to an applicable project**.

### New Requirement:
- Update so that **SWM As-Built Reps and Approvers will be emailed only if they are associated as users to the project.**  
- **Apply to two (2) types of automatic emails:** (1) triggered by the **basic system workflow** (during SWM request and response save), as well as (2) the **automatic, 2-week email notifications**. 

### Current Functionality (as of 5/1):
- Associated with GH #279 
- Emails are sent to all users who are "SWM Approvers" / "SWM Reps"
![image](https://user-images.githubusercontent.com/4098544/39491995-179daf4e-4d5c-11e8-9e8f-1f199ad67df2.png)

**Comment by vijme** [comment]
1. 2 week reminders have already been implemented in production.

2. The SWM request and response system flow has been updated to reflect this change.

Implemented in dev

**Comment by vijme** [comment]
The issue can be validated using the notifications tab recipient list.

To be used for testing purposes

Current District Rep in dev

Dave                                               Bartell                                            
Scott                                              Messier                                            
Christie                                           Minami                                             
Matthew (Matt)                              Gregory (Greg)                                     
rachel                                             wingender                                          
Tom                                                Linsenmeyer                                        
Tom                                                TEST                                               
Holly                                              Schueler                                           
Tad                                                Daniel     


Current AB Approvers in dev. 

Scott                                              Messier                                            
Matthew (Matt)                             Gregory (Greg)                                     
rachel                                             wingender                                          
Tom                                                Linsenmeyer                                        
Tom                                               TEST                                               
Holly                                              Schueler                                           
Tad                                                Daniel                                             
Clayton                                         Ballard                                            
Phil                                               Brentlinger

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Development Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been confirmed by the project stakeholder.

The status of this issue is "Ready for Staging"

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Appears to be working in staging

**Comment by HollySchuelerKCI** [comment]
This issue has been validated by the project stakeholder in the Staging Environment.

The status of this issue is "Ready for Production"

**Comment by Tad-Daniel** [comment]
Item completed
