### ISSUE TITLE
QA Toolkit - Update QA3 PDF Report - Spelling Correction

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#406]
Please fix **spelling on QA-3 PDF, Line at bottom of page 1**:
- **“proce” should be “price”**

![image](https://user-images.githubusercontent.com/4098544/41298715-e128ecc2-6e2f-11e8-84f2-0f1cdd0c80a2.png)

![image](https://user-images.githubusercontent.com/4098544/41298574-a4495fee-6e2f-11e8-8b93-6d4b0650c208.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by vijme** [comment]
Implemented in dev

**Comment by slmessier** [comment]
This issue has been confirmed by project team in the Development Environment.

**Comment by slmessier** [comment]
**this issue has been confirmed by stakeholders in the Staging environment and will be labeled as Ready for Production**

![image](https://user-images.githubusercontent.com/4098544/41499323-1716d92e-714c-11e8-9ba5-2c544abcd600.png)

**Comment by Tad-Daniel** [comment]
item completed
