### ISSUE TITLE
QA Toolkit - Update Mod Request Form - Update "Important Notes" Text

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#407]
Please **make the following (2) updates to the format of the "Important Notes" section on the Modification Request Form:**
1. **Increase font size**
2. **Update text using the following:**

_"Any change in a contract quantity resulting from revision will not be basis for renegotiation of unit price by either party for any affected item(s)._

_Ensure all sections of the request are complete and upload all the necessary documents including a legible plan sheet markup. Photos can also be helpful in the review process._

_To sign the request, click the proper button at the lower let of the page and then enter your name and password when prompted._

_Be sure to click on the "Save & Submit" button to enter the information into the system. Only click the button once and wait for the screen to refresh."_

![image](https://user-images.githubusercontent.com/4098544/41300542-02d21f3e-6e34-11e8-937c-9deaee5ddeda.png)

**Comment by vijme** [comment]
Implemented in dev. Please test and confirm

**Comment by slmessier** [comment]
This issue has been confirmed by project team in the Development Environment.

**Comment by slmessier** [comment]
**this issue has been confirmed by stakeholders in the Staging environment and will be labeled as Ready for Production**

![image](https://user-images.githubusercontent.com/4098544/41499323-1716d92e-714c-11e8-9ba5-2c544abcd600.png)

**Comment by Tad-Daniel** [comment]
Item complete
