### ISSUE TITLE
QA Toolkit - System Permissions Inoperative

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#409]
Users have reported the following high priority issue regarding system permissions that are not restricting functionality as designed. 

**Please reconcile using the capabilities listed below. Items in red font are high priority.**
![image](https://user-images.githubusercontent.com/4098544/41388761-7b9e6cce-6f5b-11e8-9461-2389ed0dd916.png)

**Comment by slmessier** [comment]
@Tad-Daniel **All Items have been fixed aside from the (1) exception noted below. Please confirm using DEV application:**
[http://oed.kci.com/SHAPORTAL/](url)

The following item appears to be a new capability that will require additional time to develop. **Until that time, Viji has removed edit and delete permissions for inspectors on the QA inspections subtab. They will be able to see the “Add Inspection” button. Please advise or confirm**:

![image](https://user-images.githubusercontent.com/4098544/41389116-0c724468-6f5d-11e8-8fca-2a7f11929264.png)

**Comment by Tad-Daniel** [comment]
I reviewed each account role this morning and everything look correct.  We will most likely keep the QA inspectors role as it currently is instead of manipulating it further.

**Comment by Tad-Daniel** [comment]
looked at everything this morning and it is all good

**Comment by slmessier** [comment]
@Tad-Daniel thank you - can you confirm this applies to STAGING environment? Or confirm there if applicable: 
[http://199.107.71.85/shaportal/](url)

**Comment by Tad-Daniel** [comment]
Yes it is in the staging envir.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by Tad-Daniel** [comment]
Item complete
