### ISSUE TITLE
MDE Toolkit - Login Analysis Menu - Erroneous Code Snippet Displayed

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#41]
The system currently displays a code snippet (that appears to be a system error message) when the "Login Analysis" screen is displayed.

![image](https://cloud.githubusercontent.com/assets/4098544/3446048/3ccf81c6-013d-11e4-8025-d48991604104.png)

Steps to replicate:
1. click on Admin --> Login Analysis Menu

**Comment by Tad-Daniel** [comment]
This issue has been corrected.  Issue closed.
