### ISSUE TITLE
QA Toolkit - Restore Deleted Project PG3975172 (Data Request)

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#418]
**Please re-enter / restore project information for project _PG3975172 - MD 210 New Bald Eagle Road Improvements_**. The project details information exists in STAGING.
![image](https://user-images.githubusercontent.com/4098544/42904185-370c493e-8aa2-11e8-9e0e-129095c8bfe7.png)

The process to restore a deleted project is a manual effort that can be divided into 2 generalized tasks:
1. Create a new project record that re-uses the Project ID of the original; re-connect orphaned relationships to inspections, etc (back-end)
2. Update Project Details information using Front-end toolkit interface (front-end)

**Comment by slmessier** [comment]
@Tad-Daniel  - a new project record has been created in PROD to represent _PG3975172_, and related associations have been restored. 

**Please examine the following information in detail for accuracy, and update as-needed to stage data appropriately using the toolkit front-end** 

**1. Project Details
2. QA Inspections tab Info
3. Mods Tab Info
4. QA Concurrence Tab Info
5. SWM Tab Info**

[http://www.oedtoolkits.net/](http://www.oedtoolkits.net/)

![image](https://user-images.githubusercontent.com/4098544/42953860-4f3163b2-8b49-11e8-9fed-3584495cebac.png)

**Comment by Tad-Daniel** [comment]
Project restored
