### ISSUE TITLE
QA Toolkit - Restore Deleted Projects PG5105177 (Data Request)

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#419]
**_Please re-enter / restore project information for Project # PG5105177_**
[QAInsp_PG5105177R_20180530.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2246170/QAInsp_PG5105177R_20180530.pdf)

_Origin of request is email from T.Daniel 7/31/2018 indicating that two (2) additional projects have been deleted from the Toolkit._

**Comment by vijme** [comment]
Project was restored back. Please resave the project with correct information for Project Type, FMIS, Stage and other checkbox values as they are not available from inspection report and were defaulted.

**Comment by vijme** [comment]
Two projects were restored.

**Comment by HollySchuelerKCI** [comment]
@Tad-Daniel  - new project records have been created in PROD to represent both PG5105177 and PG0395177, and their related associations have been restored.

Please examine the following information in detail for accuracy, and update as-needed to stage data appropriately using the toolkit front-end

1. Project Details
2. QA Inspections tab Info
3. Mods Tab Info
4. QA Concurrence Tab Info
5. SWM Tab Info

http://www.oedtoolkits.net/

**Comment by Tad-Daniel** [comment]
Project restored
