### ISSUE TITLE
QA Toolkit - Update Projects - Add new User - Select/Deselect All users in Grid Fails

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#42]
The system does not deselect records within the associated grid after the user has unchecked the associated (select-all) checkbox.

Steps to replicate:
1. Update existing project -->users subtab -->Add new User (bottom of page)
2. within the "Available Users Grid", click the checkbox to select all users within the associated grid (reference screenshot as needed)
3. Uncheck the checkbox to select all users - (the system does not uncheck all of the associated user records as expected)

![image](https://cloud.githubusercontent.com/assets/4098544/3446163/821342ee-013e-11e4-9644-0461c6302b64.png)

note: users are currently able to complete the associated workflow by working around (avoiding) this issue.

**Comment by vijme** [comment]
Fixed in dev

**Comment by rwingender** [comment]
Validated in dev.

**Comment by Tad-Daniel** [comment]
No longer an issue.  Appears to be corrected.  Issue closed
