### ISSUE TITLE
QA Toolkit - Restore Deleted Project PG0395177 (Data Request)

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#421]
**_Please re-enter / restore project information for Project # PG0395177_**
[QAInsp_PG0395177_20180706.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2246176/QAInsp_PG0395177_20180706.pdf)

_Origin of request is email from T.Daniel 7/31/2018 indicating that two (2) additional projects have been deleted from the Toolkit._

**Comment by slmessier** [comment]
Project has been restored. Please resave the project with correct information for Project Type, FMIS, Stage and other checkbox values as they are not available from inspection report and were defaulted.

**Comment by slmessier** [comment]
@Tad-Daniel  - new project record has been created in PROD to represent PG0395177, and their related associations have been restored.

Please examine the following information in detail for accuracy, and update as-needed to stage data appropriately using the toolkit front-end

1. Project Details
2. QA Inspections tab Info
3. Mods Tab Info
4. QA Concurrence Tab Info
5. SWM Tab Info

http://www.oedtoolkits.net/

**Comment by Tad-Daniel** [comment]
Project restored
