### ISSUE TITLE
SSRS Conversion: QA19 - YCList

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#424]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Projects Menu --> YC Cert Tab
2. Expand Search Panel (if necessary)
3. Click Print Button

![image](https://user-images.githubusercontent.com/4098544/45367298-ea9e9b00-b5ae-11e8-9930-418ca3683f3a.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA19 - YCList.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398305/QA19.-.YCList.pdf) (First page below)
![image](https://user-images.githubusercontent.com/4098544/45366679-5e3fa880-b5ad-11e8-8d76-4b3cbe37d7b9.png)

**Comment by vijme** [comment]
Implemented in dev. Please check, the same theme will be applied for all reports. If there is anything that you would like to change for color, font, please let me know.

**Comment by HollySchuelerKCI** [comment]
It seems that the font color for expired or revoked cards did not translate accurately. Please see #260 as reference to desired font colors for those users who have either expired or revoked cards.

**Comment by HollySchuelerKCI** [comment]
This report and the above color issue has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looking good

**Comment by HollySchuelerKCI** [comment]
This report has been tested and successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA19 - YCList - 424 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658185/QA19.-.YCList.-.424.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
