### ISSUE TITLE
SSRS Conversion: QA15 - ESC Grade Summary

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#425]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report

1. Click Reporting Tab
2. Click Reports Tab
3. Scroll to the bottom of the page to ESC / SWM Grade Summary
4. Enter date range
     a. example: 2/1/2015 - 12/1/2015
5. Click Report
![image](https://user-images.githubusercontent.com/25441512/45444544-bfdb4200-b695-11e8-86ee-5fa6ed29bd38.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA15 - ESCGradeSummary.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398258/QA15.-.ESCGradeSummary.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45444606-e8fbd280-b695-11e8-8324-936881450882.png)

**Comment by vijme** [comment]
Implemented in dev. The Statewide row appears at the prespecified location on the page. Sometimes when the rows aren't enough, there appears a gap between the districts and statewide row. 

I hope this doesnot functionally affect the report. Please let me know if its not agreed with the stakeholders.

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Report is looking good with some minor font adjustments needed.  Make the column headers a point or two smaller.

**Comment by vijme** [comment]
Column header size reduced.

**Comment by HollySchuelerKCI** [comment]
The project team has confirmed that the above request by the stakeholder to reduce column header size has been corrected in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 15 - ESC Grade Summary - 425 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658179/QA.15.-.ESC.Grade.Summary.-.425.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Enviornment._**
