### ISSUE TITLE
SSRS Conversion: QA7 - InspectionQAOne

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#426]
### Additional Re-Design Specification: 
(none)

===================================================================
### Steps to Generate Report
1. Under the Inspections Tab, click the QA1 subtab
2. From the QA Inspection List, click the project's pdf button to generate the Inspection Report
![image](https://user-images.githubusercontent.com/25441512/45444811-70e1dc80-b696-11e8-8d69-2d44a82e733c.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA7 - InspectionQAOne.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398200/QA7.-.InspectionQAOne.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45444884-b69ea500-b696-11e8-9d1a-4f6be308a88e.png)

**Comment by vijme** [comment]
This report has been completed in development env. The UI has a small change, ratings have been placed adjacent to the Grade table as opposed to underneath the Grade table in the original report. 

This report has to be tested for NO Grade and Final Inspections as well for QA1 type reports only.

**Comment by vijme** [comment]
Holly, as stated above in my comment, please note that this report template is used only for QA1 type inspections only. Those projects are OOC61 (07/01/2011) and are under implementation under GH 456.

Its kind of confusing, but remember this issue will be only for QA1 type, and GH 456 should be tested for types OOC61 (07/01/2011) and OOC61(09/02/2005) and GH 428 should be tested against OOC61(09/01/2005) type. I hope its clear, but please reach out if you have questions

**Comment by HollySchuelerKCI** [comment]
@vijme Thank you, this is clearer. I misunderstood your comment above.

This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
This form must be as close to the original as possible.

- Checkbox change on the first page
- Grade box and rating checkbox's need to be re-aligned properly
- Signature lines must be properly aligned
- Line 1.1 - 1.3 should be white and have an * in the point value column
- NPDES Header should be Grey
- can the border be removed around the total points available below each section.

**Comment by vijme** [comment]
All above comments are corrected.

**Comment by HollySchuelerKCI** [comment]
The above requested modifications have been validated by the project team in the **_Development Environment._**

**Comment by vijme** [comment]
@Tad-Daniel, Thanks for your markup

1. Page number at the top of page - Implemented
2. Changes to grade box - Implemented
3. Changes to rating box - Implemented
4. Received By signature Box: The signatures are rendered as subreports. Due to this, a slight one point shift to the text causes the whole report to widen and go over 2 sheets. 
5. Header font increased slightly
6. Removed and added borders accordingly
7. SSRS does not allow any form data to be in the footer (to be repeated on all pages). So inspected date cannot be made available to all pages. But printed date is current date and hence available in all pages
8. Moved down section 2.7, but the next section breaks in the middle. It is not possible to control the row height for different sections as they all are basically the same table and grouped to be shown separately.

Please let me know your comments. Once this form is finalized, will apply the same changes to other inspection forms.

**Comment by Tad-Daniel** [comment]
additional comment in markup.
[QAInsp_000111_20180410 (3).pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2703525/QAInsp_000111_20180410.3.pdf)

**Comment by vijme** [comment]
Thanks for your feedback. I have corrected all, except "If no, move to second line if possible". Please let me know your feedback. Once approved, the same changes will be applied to other inspection types.

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications have been validated by the project team in the **_Development Environment._**

@Tad-Daniel please see Viji's comment above requesting your feedback regarding the "If no, more to second line if possible".

**Comment by Tad-Daniel** [comment]
Looking good so far . please apply to other inspection types.   I will delay commenting on OOC61 until changes are made to the template.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 7 - InspectionQAOne - 426 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2746571/QA.7.-.InspectionQAOne.-.426.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
@vijme It appears that line item 3.7.3 in the QA1 report is misplaced.

![image](https://user-images.githubusercontent.com/25441512/52006753-e5c57f80-249a-11e9-9021-5f5572094ac8.png)

Here is the project / contract information:
![image](https://user-images.githubusercontent.com/25441512/52006983-74d29780-249b-11e9-8d2c-819b315d3ce7.png)

I could not replicate this misplacement with other QA1 forms, but it may have to due with the comment underneath line item 3.7.3?
![image](https://user-images.githubusercontent.com/25441512/52007464-81a3bb00-249c-11e9-8ea1-1ddabf3697d5.png)

**Comment by vijme** [comment]
@HollySchuelerKCI , Its very strange that we get the misplacement. I am not able to reproduce this in DEV on any other inspection. Will you be able to create a very similar inspection on DEV and try to reproduce

**Comment by HollySchuelerKCI** [comment]
The above referenced issue has been corrected and the project team confirmed the table is sorting correctly in the **_Staging Environment._**
