### ISSUE TITLE
SSRS Conversion: QA5 - QAInspectionLog

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#427]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, click the QA1 sub tab
2. Expand Search Panel 
3. Enter contract number
4. Click Print
5. Click Inspection Log in the pop up window
![image](https://user-images.githubusercontent.com/25441512/45444159-bb625980-b694-11e8-9986-153393539614.png)

![image](https://user-images.githubusercontent.com/25441512/45444210-dc2aaf00-b694-11e8-9e4b-a6884a95bd9f.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA5 - QAInspectionLog.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398162/QA5.-.QAInspectionLog.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/45444251-f9f81400-b694-11e8-98f0-b2417e2fd67c.png)

**Comment by HollySchuelerKCI** [comment]
@vijme Below are my observations from testing:
1. It appears that the green checkbox image is being stretched to the full height based on the text within the Grade and Reason for missed inspection column.  See screenshot below:
![image](https://user-images.githubusercontent.com/25441512/49227238-a0aba100-f3b6-11e8-9cd5-9f36d0974d28.png)

2. Column "E&S Permit Req" no longer has (Y/N) beneath.
![image](https://user-images.githubusercontent.com/25441512/49227519-43fcb600-f3b7-11e8-9b49-9428707d5ddd.png)

**Comment by vijme** [comment]
@HollySchuelerKCI, I have fixed this, can you test and confirm?

**Comment by HollySchuelerKCI** [comment]
@vijme The checkboxes are no longer stretched, however it appears that the image is now cutoff on the right. Please see example below:
![image](https://user-images.githubusercontent.com/25441512/49292512-7374f680-f47b-11e8-8b0c-80a19bc9dbab.png)

**Comment by vijme** [comment]
Fixed

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks Goos

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA5 - QAInspectionLog - 427 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658169/QA5.-.QAInspectionLog.-.427.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
