### ISSUE TITLE
SSRS Conversion: QA6 - Inspection 

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#428]
### Additional Re-Design Specification: 
1 - The notification list is not appearing at the bottom of the QA-1 form

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, click QA1
2. Locate project, and click the QA-1 button in the right column
![image](https://user-images.githubusercontent.com/25441512/45445375-092c9100-b698-11e8-83c0-ca14ff79345f.png)
3. Scroll to the bottom of the report and click the print button
![image](https://user-images.githubusercontent.com/25441512/45445428-3416e500-b698-11e8-8a8a-02ef90fb41d2.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA6 - Inspection.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398171/QA6.-.Inspection.pdf) (First page below)
![image](https://user-images.githubusercontent.com/25441512/45445568-953eb880-b698-11e8-8e00-10c062220b8b.png)

**Comment by vijme** [comment]
@HollySchuelerKCI , I have completed this report in dev. But I see that there is an additional specification for this item that notification list is not appearing at the bottom of the report. I checked the current reports in staging. The notification list do appear in the reports. Due to the email notifications failing in dev, the notification list do not appear in dev. But it should work in staging and production. Can you please double check that specification if I have misunderstood something?

**Comment by vijme** [comment]
To be tested for type OOC61.1  (09/01/2005)

**Comment by HollySchuelerKCI** [comment]
The report has been successfully validated by the project team in the **_Development Environment._**

Project team will investigate the reported issue that the notification list is not appearing at the bottom of the report. Findings will be reported once the project team is able to replicate this issue successfully.

**Comment by HollySchuelerKCI** [comment]
@Tad-Daniel Regarding your comment under "Additional Re-design Specifications" Could you please provide clarification / steps to replicate?

As Viji mentioned in her above comment, we both tested this report in the Staging Environment (due to email notifications failing in Dev) and were able to view the notification list at the end of the form.

Thank you!

**Comment by vijme** [comment]
Assigning to me (Viji) to fix the checkboxes and signature  panels

**Comment by HollySchuelerKCI** [comment]
@Tad-Daniel  Please test the OOC61.1 form notification list in STAGING. I've included the parameters below for you to use to confirm validation.

**Staging Parameters:** 
Contract No.: 123test3211
Project Description: testing219
Status: Final

_Reference Screenshot:_
![image](https://user-images.githubusercontent.com/25441512/50350983-c25bfc00-050e-11e9-9574-11535d1e16be.png)



================================================================
**Screnshot from report:**
![image](https://user-images.githubusercontent.com/25441512/50302714-e4934280-0458-11e9-99e7-088fa9e9c5c1.png)

**Comment by Tad-Daniel** [comment]
Appears to be working correctly

**Comment by slmessier** [comment]
@Tad-Daniel please indicate whether are you comfortable accepting at this time? thank you!

**Comment by Tad-Daniel** [comment]
Yes this is acceptable,

**Comment by vijme** [comment]
Implemented in dev. To be tested for OOC61(09/02/2005) and OOC61.1-09012005 types (Graded, No grade, draft, final )

**Comment by HollySchuelerKCI** [comment]
Both OOC61(09/02/2005) and OOC61.1-09012005 types (Graded, No grade, Draft, and Final ) have been successfully tested by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
I checked them and they all look god .  One final change is attached.  With this adjustment everything should be good.
[QAInsp_000111_20180410.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2742246/QAInsp_000111_20180410.pdf)

**Comment by vijme** [comment]
Nice Catch. Corrected the issue in all the report types

**Comment by HollySchuelerKCI** [comment]
This issue has been corrected in the **_Development Environment._**

@Tad-Daniel please confirm at your earliest convenience.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 6 - Inspection - 428 - FINAL OUPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2746566/QA.6.-.Inspection.-.428.-.FINAL.OUPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
