### ISSUE TITLE
SSRS Conversion: QA1 - InspectionSchedule

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#429]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, click on the Pending Insp subtab
2. Expand the search panel
3. Click Print
4. Click Inspections Schedule
![image](https://user-images.githubusercontent.com/25441512/45446323-94a72180-b69a-11e8-8d53-118a3ec2061c.png)

![image](https://user-images.githubusercontent.com/25441512/45446858-f74ced00-b69b-11e8-8d07-02fe8052a1ce.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA1 - InspectionSchedule.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398124/QA1.-.InspectionSchedule.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45446384-c0c2a280-b69a-11e8-8f53-7227b60b8017.png)

**Comment by sgpapakirk** [comment]
I have now finished all coding and testing for this "QA1 - InspectionSchedule" report.
I have committed and pushed to my Stylianos_Dev code branch, and then merged its changes into our master one.

**Comment by sgpapakirk** [comment]
Please note that I have just done some changes in this report, to use Arial 9pt, use 8inches for width, and other small formatting changes.
I just finished updating our master branch with them.

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk Thank you! The reason I added the label "Assigned to Developer" was for KCI tracking only. I will test once it has been merged.

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk Please update report to include **both** the title and subtitle to iterate on all pages. Currently, the title and subtitle are only shown on page 1.  See highlighted title and subtitle below:

![image](https://user-images.githubusercontent.com/25441512/47719154-ae87ce00-dc20-11e8-9930-8e00a340724b.png)

**Comment by sgpapakirk** [comment]
Holly, I have just merged now into our master code branch the above change that you wanted for this report.

**Comment by vijme** [comment]
Deployed and available for testing

**Comment by HollySchuelerKCI** [comment]
The above issue has been corrected on the report.

This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Please add the separation line in the column header like other reports have.  Looks good otherwise and appears to be working correctly.

**Comment by sgpapakirk** [comment]
I have now added the "DarkGray" 1pt border in the 2 header rows. This is the same border used in the
"Project List" tab's "Search Results" and "Project List By Company" reports.
I have also merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk Is it possible to remove the DarkGray 1pt vertical border? See Example below:

![image](https://user-images.githubusercontent.com/25441512/49164361-f754a480-f2fc-11e8-9932-ad8bab2c16cb.png)

![image](https://user-images.githubusercontent.com/25441512/49164551-561a1e00-f2fd-11e8-9a33-d1e9293d5feb.png)

**Comment by sgpapakirk** [comment]
Certainly Holly, very easy. It will be though on the next release of code.

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk Yes please remove those vertical borders as well. To be consistent with the original report, the top border can also be removed if feasible.

To confirm, the only border will be the bottom border. Please see example below:
![image](https://user-images.githubusercontent.com/25441512/49180937-19155200-f324-11e8-9742-30af93211aee.png)

**Comment by sgpapakirk** [comment]
I have now implemented these changes to the header. I only have the bottom "DarkGrey" 1pt line now.
I have merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by sgpapakirk** [comment]
Viji has deployed this report to http://oed.kci.com/shaportal

**Comment by HollySchuelerKCI** [comment]
This report with the requested modification has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 1 - InspectionSchedule - 429 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2676728/QA.1.-.InspectionSchedule.-.429.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
