### ISSUE TITLE
QA Toolkit - BP/SS - Reports - System Navigation / Close Button Failure

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#43]
During the Generate BP/SS Reports workflow, the user has the option to click the Close button to effectively terminate the workflow. However, currently after the user has clicked the Close button, the system displays the Inspection Report list, but also with the BP/SS-Reports tabs as active. (the active tabs are expected to match the grid below, meaning the system should display the Inspections-Reports tab as the active tabs in this case)

Steps to replicate:
1. Click BP/SS Tab -->Reports Subtab --> click Close button
2. Examine each of the following and note the inconsistency:
- The BP/SS tab is displayed as active
- The (BP/SS) Reports subtab is displayed as active
- The Inspection (reports) Grid is displayed in the tabular grid

![image](https://cloud.githubusercontent.com/assets/4098544/3446389/3bd6fc5a-0141-11e4-9ce1-7e4074f52b7a.png)

**Comment by vijme** [comment]
Right now the system is configured to load the main tabs and subtabs through click event. To ensure uniformity it may be a better option to remove the "CLOSE" button from this page and use the tabs for page navigation.

**Comment by Tad-Daniel** [comment]
I agree.

**Comment by vijme** [comment]
Button removed in dev

**Comment by rwingender** [comment]
Validated in Dev.

**Comment by Tad-Daniel** [comment]
Issue corrected, Issue closed
