### ISSUE TITLE
SSRS Conversion: QA2 - InspectionHold

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#430]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, click the Pending Insp subtab
2. Expand the search panel
3. Click the print button
4. Click Projects on Hold
![image](https://user-images.githubusercontent.com/25441512/45446670-7f7ec280-b69b-11e8-9e94-420281b18e1c.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA2 - InspectionHold.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398132/QA2.-.InspectionHold.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45446757-b523ab80-b69b-11e8-8307-9ef473a3f6db.png)

**Comment by sgpapakirk** [comment]
I have now finished all coding and testing for this "QA2 - InspectionHold" report.
I have committed and pushed to my Stylianos_Dev code branch, and then merged its changes into our master one.
This report also now uses Arial 9pt, width of 8 inches, and etc. formatting fixes.

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Please add the separation line in the column header like the project search reports have. Looks good otherwise and appears to be working correctly.

**Comment by sgpapakirk** [comment]
I have now added the "DarkGray" 1pt border in the header row. This is the same border used in the
"Project List" tab's "Search Results" and "Project List By Company" reports.
I have also merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk Is it possible to remove the DarkGray 1pt vertical border? See Example below:

![image](https://user-images.githubusercontent.com/25441512/49164361-f754a480-f2fc-11e8-9932-ad8bab2c16cb.png)

![image](https://user-images.githubusercontent.com/25441512/49164551-561a1e00-f2fd-11e8-9a33-d1e9293d5feb.png)

**Comment by sgpapakirk** [comment]
Certainly Holly, very easy. It will be though on the next release of code.

**Comment by sgpapakirk** [comment]
Holly 2 questions:
1) Should I remove all the vertical borders, even the first and the last one?
2) Should other reports be fixed similarly, like say in the "Project List" tab the "Search Results" and the "Project List By Company" reports?
![image](https://user-images.githubusercontent.com/20664384/49180019-a1462800-f321-11e8-9d46-1b709eba3996.png)

**Comment by HollySchuelerKCI** [comment]
@sgpapakirk Yes please remove those vertical borders as well. To be consistent with the original report, the top border can also be removed if feasible.

To confirm, the only border will be the bottom border. Please see example below:
![image](https://user-images.githubusercontent.com/25441512/49180937-19155200-f324-11e8-9742-30af93211aee.png)

**Comment by sgpapakirk** [comment]
I have now implemented these changes to the header. I only have the bottom "DarkGrey" 1pt line now.
I have merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by sgpapakirk** [comment]
Viji has deployed this report to http://oed.kci.com/shaportal

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 2 - InspectionHold - 430 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2676762/QA.2.-.InspectionHold.-.430.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
