### ISSUE TITLE
SSRS Conversion: QA11 - QAInspectionPerDistrict

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#431]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Reporting Tab
2. Click the Reports stubtab
3. Locate QA Projects By District report
4. Select District from the dropdown.
5. Click Report
![image](https://user-images.githubusercontent.com/25441512/45490946-6d9e2d80-b736-11e8-9730-5fce4250e067.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA11 - QAInspectionPerDistrict.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398215/QA11.-.QAInspectionPerDistrict.pdf)  (First page below)
![image](https://user-images.githubusercontent.com/25441512/45491011-9de5cc00-b736-11e8-8abe-3743957562b0.png)

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks great except can the chart be wider so that when it is completely full there is no misalignment of the Delete repeated word numbers along the horizontal axis 
![image](https://user-images.githubusercontent.com/7913678/49654941-2a86ea00-fa07-11e8-9e74-64aa86e27a8a.png)

**Comment by vijme** [comment]
@Tad-Daniel, I did widen the chart, does that satisfy your requirement?
 Or do you want the bars to be slightly wider as well?

**Comment by HollySchuelerKCI** [comment]
### SHA Approved Converted Report
Full Downloadable Report: [QA11 - QAInspectionPerDistrict.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2657800/QA11.-.QAInspectionPerDistrict.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
