### ISSUE TITLE
SSRS Conversion: QA17 ModSummary

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#432]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Reporting Tab
2. Click the Reports subtab
3. Locate Modification Summary
4. Enter date range
5. Click Report

![image](https://user-images.githubusercontent.com/25441512/46804632-1ee1b480-cd31-11e8-8213-05c4dfae284f.png)

===================================================================
### Example of Report
**Full Downloadable Report:**  [QA17 ModSummary.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2468806/QA17.ModSummary.pdf)  (First page below)
![image](https://user-images.githubusercontent.com/25441512/46804804-96174880-cd31-11e8-94b3-10b44172a3df.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

Awaiting stakeholder confirmation of proffered color palate.

**Comment by vijme** [comment]
@Tad-Daniel, Need your input on this: 
- Under Modifications Summary, I have added a duplicate chart that have bars separated, but please note that all bars will be of the same color in that case. This is the SSRS chart behavior.
- Under Modification Approval Time, Average Approval Time chart is also duplicated with the vertical bars separated. 

Please let me know your preferences.

Other than that, the first two boxes are aligned and yes, the last quarter does not have any data in dev to show up.

**Comment by Tad-Daniel** [comment]
I do not mind the bars all being the same color.  I prefer the separation.   Is this true for all the different reports throughout the toolkit.  If so then all the charts can have same color bars if it allows for a separation.

**Comment by vijme** [comment]
@Tad-Daniel , mostly yes, except for the Quarter Chart in QASummaryBPR Report, we can have all chart bars separated and have the same color.

**Comment by Tad-Daniel** [comment]
Great.  Lets do this.

**Comment by vijme** [comment]
Chart redesigned according to latest spec of inter bar spaces.

**Comment by HollySchuelerKCI** [comment]
This report with the above chart modification has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Our data is sporadic in the DEV environment so I am unable to see a full 4 quarters charted out.  It currently appear that not all the quarters show in the report.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
FINAL REPORT OUTPUT SAMPLE:
[QA 17 - ModSummary - 432 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2703011/QA.17.-.ModSummary.-.432.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**

For testing purposes, please use 7/1/2016 - 6/3/2017 as the report date range.
