### ISSUE TITLE
SSRS Conversion: QA13 - QAESCSummaryBPR

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#433]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Reporting Tab
2. Click the Reports subtab
3. Locate the ESC QA Summary for Business Plan Reporting report
4. Enter Fiscal year
5. Enter District
6. Click Report
![image](https://user-images.githubusercontent.com/25441512/45491928-f027ec80-b738-11e8-8d1a-adddaa4be3d5.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA13 - QAESCSummaryBPR.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398234/QA13.-.QAESCSummaryBPR.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/45492012-2a918980-b739-11e8-914e-1c25c1d4021a.png)

**Comment by vijme** [comment]
Having limitations with regard to 
-orientation of labels
-colors and positions of bar
-display the actual value inside the bar center

**Comment by HollySchuelerKCI** [comment]
While testing FY 2014 with "ALL" districts selected, I noticed the following:
1.  The table "Number of quality assurance (QA) inspections performed" was cut off on page 1 and ran over onto page 2. 
2. The table "Percentage of compliance on erosion/sediment control ratings" was cut off on page 3 and ran over onto page 4.
3. The table "Projects with minimum specified visits" was cut off on page 5 and ran over onto page 6.

See example:
![image](https://user-images.githubusercontent.com/25441512/47724305-ca916c80-dc2c-11e8-87b3-9469140ace10.png)

**Comment by vijme** [comment]
Fixed the aligning issues, now the table will not break during a page break. Also I moved the values outside the bar for readability.  Removed the grid lines for some of the graphs for readability. Please let me know if this can be implemented/removed from all the charts.

**Comment by HollySchuelerKCI** [comment]
The above issue has been corrected in the **_Development Environment._**

Grid lines (kept or removed) will be decided by the stakeholder during testing.

**Comment by Tad-Daniel** [comment]
Working correctly.  Please have the quarter chart mimic the look of the FY chart and slant or reduce the font size of the years in the FY chart so they are not miss-alligned

**Comment by vijme** [comment]
@Tad-Daniel, Due to the nature of the data in this chart, it was not possible to have spaces between the vertical bars in the quarter chart. I have tried to induce spaces in the end and reduce the size of the bar, for a somewhat closer look. Please have a look and let me know your comments.  Once the design is confirmed for first one, I will follow the similar pattern to other charts in the report

Otherwise, The font size of years reduced

**Comment by vijme** [comment]
Chart redesigned according to latest spec of inter bar spaces.

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Charting looks good.

Please add some space between these two charts so that the last two grids and charts show up on a separate page from all the others

![image](https://user-images.githubusercontent.com/7913678/49808623-f5daa180-fd2a-11e8-82e6-f16fad8d6050.png)

**Comment by vijme** [comment]
Introduced a page break so last two charts appear on a separate page

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 13 - QAESCSummaryBPR - 433 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2676755/QA.13.-.QAESCSummaryBPR.-.433.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
@vijme I noticed an issue while testing in staging:

It appears that Q4 data under Percentage of compliance on erosion/sediment control ratings section is not displaying accurately in the bar graph. See screen capture below:
![image](https://user-images.githubusercontent.com/25441512/51991614-725f4600-2479-11e9-91ba-997b0f5c841c.png)

I tested FY 2014 All districts, and 2013 All Districts and the bar graph displayed correctly.

#### Steps to Replicate:
1. Enter the following parameters on the reporting tab
![image](https://user-images.githubusercontent.com/25441512/51991659-8e62e780-2479-11e9-9423-43045f696cdc.png)

2. Click Report
3. Scroll to the Percentage of compliance on erosion/sediment control ratings section.

**Comment by vijme** [comment]
@HollySchuelerKCI , the issue here is the graph range is set from 95 - 100. It is expected in PROD to be in the value range. Since this is test data, there are values below 95% and they don't show on graph.

**Comment by HollySchuelerKCI** [comment]
@vijme Thank you for confirming.
