### ISSUE TITLE
SSRS Conversion: QA4 - QAInspectionGradeLog

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#435]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, click the QA1 subtab
2. Expand the Search Panel
3. Enter search parameters
4. Click Print
5. Select Inspection Grade Log

![image](https://user-images.githubusercontent.com/25441512/49228338-24668d00-f3b9-11e8-809c-5d94922d3226.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA4 - QAInspectionGradeLog.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2629480/QA4.-.QAInspectionGradeLog.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/49228390-3d6f3e00-f3b9-11e8-8b06-ccb032b259d7.png)

**Comment by HollySchuelerKCI** [comment]
@vijme Column "E&S Permit Req" no longer has (Y/N) beneath.
![image](https://user-images.githubusercontent.com/25441512/49228581-ab1b6a00-f3b9-11e8-945b-fefc52269c6d.png)

**Comment by vijme** [comment]
Issue fixed

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
formatting looks good but why are all the reports not showing.  Is this just because we are in the developer environment?

**Comment by slmessier** [comment]
@Tad-Daniel  - could you please provide a description of what youre expecting to see that is not occurring? a screencap annotation may be most effective.

are you otherwise comfortable accepting at this time?

**Comment by Tad-Daniel** [comment]
I figured it out.   Drafts do not show and it is functioning correctly.     This is acceptable

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 4 - QAInspectionGradeLog - 435 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2769887/QA.4.-.QAInspectionGradeLog.-.435.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
