### ISSUE TITLE
SSRS Conversion: QA 23 - UserSubscriptions

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#436]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Admin Tab
2. From the User List tab, click the Subscription Summary button found in the lower right corner.
![image](https://user-images.githubusercontent.com/25441512/45501402-148ec380-b74f-11e8-9dff-9ba9d018c550.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA 23 - UserSubscriptions.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398351/QA.23.-.UserSubscriptions.pdf) (First page below)
![image](https://user-images.githubusercontent.com/25441512/45501497-5c154f80-b74f-11e8-902e-a9087df7449d.png)

**Comment by sgpapakirk** [comment]
I have now finished all coding and testing for this "QA23 - UserSubscriptions" report.
I have committed and pushed to my Stylianos_Dev code branch, and then merged its changes into our master one.

Note only that I had trouble showing the top vertical headers to the right like "No Grade", "Compliance", etc. Our Crystal report would show them read bottom to top, vs. my current top to bottom.
Our current SSRS version is fairly older, later SSRS version have support for this ("Rotate270").
If you insist though I can spend some time trying a solution that I found online (uses graphics, etc.).

**Comment by HollySchuelerKCI** [comment]
The report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
LOOKS GREAT

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 23 - UserSubscriptions - 436 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658144/QA.23.-.UserSubscriptions.-.436.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
