### ISSUE TITLE
SSRS Conversion: QA 9 - PQA2List

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#437]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, click the QA2 subtab
2. Expand the Search Panel
3. Enter search criteria
    a. example: inspector name
4. Click Search
5. Click Print

![image](https://user-images.githubusercontent.com/25441512/45512139-e5874a80-b76c-11e8-899c-624bfd7a7c23.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA 9 - PQA2List.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2380789/QA.9.-.PQA2List.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/45512210-1f585100-b76d-11e8-9836-4c7cf230944c.png)

**Comment by vijme** [comment]
Implemented in dev. Please check, the same theme will be applied for all reports. If there is anything that you would like to change for color, font, please let me know.

**Comment by HollySchuelerKCI** [comment]
While testing noticed that the report has a blank last page. Can you investigate how to remove this page?

**Comment by vijme** [comment]
Nothing major. Its just an alignment issue. The horizontal width should be less. I will fix it and let you know

**Comment by vijme** [comment]
Issue fixed

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good although the column heeders should not be all caps.

**Comment by HollySchuelerKCI** [comment]
This report with the above modification has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 9 - PQA2List - 437 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658102/QA.9.-.PQA2List.-.437.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
