### ISSUE TITLE
SSRS Conversion: QA 12 - QAInspectionPerInspector

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#438]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the Reporting Tab, click the Reports subtab
2. Locate the QA Projects/Grade Distribution by Inspector
3. Enter Inspector Name
4. Enter Date Range
5. Click Report
![image](https://user-images.githubusercontent.com/25441512/49667046-db04e600-fa27-11e8-943b-6970d2dc54ec.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA 12 - QAInspectionPerInspector.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658488/QA.12.-.QAInspectionPerInspector.pdf)
(First page below)

![image](https://user-images.githubusercontent.com/25441512/49667486-32578600-fa29-11e8-93f2-02da6fe36ba9.png)

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good.  please change the column headers so they are not all caps.

**Comment by vijme** [comment]
Issue Fixed

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 12 - QAInspectionPerInspector - 438 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658065/QA.12.-.QAInspectionPerInspector.-.438.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
@Tad-Daniel There was an mix-up in reports. Please test and confirm this report located on the **Reports Tab**. If needed,use the Steps to Replicate above for guidance. 

Viji has implemented your requested chart preferences, please test and confirm all charts from those found on the reporting page:
1. QA Project Inspections By Date
2. QA Projects By District
3. QA Projects/Grade Distribution By Inspector
4. ESC QA Summary for Business Plan Reporting
5. Modification Summary
6. ESC/ SWM Grade Summary

Thank you.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 12 - QAInspectionPerInspector - 438 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2703643/QA.12.-.QAInspectionPerInspector.-.438.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
