### ISSUE TITLE
SSRS Conversion: QA 14 - QANonComplFind

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#439]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Reporting Tab
2. Click Non-Compliance Tab
3. Expand Search Panel
4. Click Print

![image](https://user-images.githubusercontent.com/25441512/46761217-f3fc4f80-cca1-11e8-8833-21c57e46ae38.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA 14 - QANonComplFind.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2466192/QA.14.-.QANonComplFind.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/46761261-09717980-cca2-11e8-98d0-9a2550a07435.png)

**Comment by vijme** [comment]
Implemented in dev.

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good except for a formatting issues with the "action taken" section

**Comment by vijme** [comment]
Formatting Issue fixed

**Comment by HollySchuelerKCI** [comment]
The project team has confirmed that the above request by the stakeholder to reformat the "action taken" section has been corrected in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 14 - QANonCompFind - 439 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658049/QA.14.-.QANonCompFind.-.439.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
