### ISSUE TITLE
SSRS Conversion: QA18 - SWMList

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#440]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Projects Tab
2. Click the SWM AB Summary subtab
3. Expand the Search Panel
4. Click Print

![image](https://user-images.githubusercontent.com/25441512/45564748-6f8feb80-b81f-11e8-91ca-db0b2147079c.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA18 - SWMList.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398304/QA18.-.SWMList.pdf)   (First page below)
![image](https://user-images.githubusercontent.com/25441512/45564824-a6660180-b81f-11e8-8a6c-42494b16ce64.png)

**Comment by vijme** [comment]
Ready for testing

**Comment by HollySchuelerKCI** [comment]
This report has Contract # as a header. Please change to Contract No. as discussed via email.

**Comment by vijme** [comment]
Item fixed.

**Comment by HollySchuelerKCI** [comment]
The above issue has been corrected.

This report has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA18 - SWMList - 440 - FINAL OUPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2657928/QA18.-.SWMList.-.440.-.FINAL.OUPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
