### ISSUE TITLE
SSRS Conversion: G6 - PUserList

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#441]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Admin Tab
2. From the User List Tab, click the Print List button found at the bottom right corner

![image](https://user-images.githubusercontent.com/25441512/45565017-5b002300-b820-11e8-829f-90bac2c2ba12.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [G6 - PUserList.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398112/G6.-.PUserList.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/45565128-a4e90900-b820-11e8-9caa-427d17172a67.png)

**Comment by vijme** [comment]
Ready for testing in dev

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good but missing the alternating gray and white shading

**Comment by vijme** [comment]
Issue fixed

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[G6 - PUserList - 441 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2657909/G6.-.PUserList.-.441.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
