### ISSUE TITLE
SSRS Conversion: IEM8 - ProjectStatus

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#442]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, select a project
2. Click the Reports Tab
3. Enter Date Range
4. Click Generate Report button
![image](https://user-images.githubusercontent.com/25441512/45704072-06241b80-bb44-11e8-916e-833b81b4fa01.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [IEM8 - ProjectStatus.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398321/IEM8.-.ProjectStatus.pdf)  (First page below)
![image](https://user-images.githubusercontent.com/25441512/45704239-5dc28700-bb44-11e8-8ed4-516e8fe3e381.png)

**Comment by vijme** [comment]
Implemented in dev. The original report has an issue. It repeats each issue for the total number of issue times.  This has been fixed and each issue shows up only once.

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[IEM 8 - ProjectStatus - 442 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2746578/IEM.8.-.ProjectStatus.-.442.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
