### ISSUE TITLE
SSRS Conversion: G2 - ProjectSearchCompany

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#443]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Projects tab
2. Click the Projects List subtab
3. Expand the Search panel
4. Click Print
5. Click Project List by Company
![image](https://user-images.githubusercontent.com/25441512/45566558-0612db80-b825-11e8-8dbc-ae3dc2d6bfe5.png)

![image](https://user-images.githubusercontent.com/25441512/45566572-10cd7080-b825-11e8-86f1-56117c43acb0.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [G2 - ProjectSearchCompany.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398029/G2.-.ProjectSearchCompany.pdf)  (First page below)
![image](https://user-images.githubusercontent.com/25441512/45566542-f3000b80-b824-11e8-976f-a1b50de5fcd8.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[G2 - ProjectSearchCompany - 443 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2657900/G2.-.ProjectSearchCompany.-.443.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
