### ISSUE TITLE
SSRS Conversion: G5 - PPermitList

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#444]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Permits Tab
2. Expand the Search Panel
3. Click Print
![image](https://user-images.githubusercontent.com/25441512/45622993-de558a80-ba53-11e8-87a1-488944af13a2.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [G5 - PPermitList.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398061/G5.-.PPermitList.pdf) (First page below)
![image](https://user-images.githubusercontent.com/25441512/45623636-034afd00-ba56-11e8-8cc0-acfc373a4f9b.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
Noted in report that "Expired" is spelled incorrectly.

![image](https://user-images.githubusercontent.com/25441512/47674287-518f0800-db8d-11e8-859b-50235b6f6b38.png)

**Comment by vijme** [comment]
Permits will expire in future. Changed it to "expires" instead of "expired" as consistent with the UI

**Comment by HollySchuelerKCI** [comment]
This issue has been corrected.

This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[G5 - PPermitList - 444 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2657890/G5.-.PPermitList.-.444.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
