### ISSUE TITLE
SSRS Conversion: G4 - ProjectDetails

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#445]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Projects Tab
2. From the Project List subtab, locate project and click the PDF button found in the right column.

![image](https://user-images.githubusercontent.com/25441512/45624453-59b93b00-ba58-11e8-8dbd-ee2dcd219e7a.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [G4 - ProjectDetails.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398057/G4.-.ProjectDetails.pdf)  (First page below)
![image](https://user-images.githubusercontent.com/25441512/45624498-7bb2bd80-ba58-11e8-9b7c-f18defc4aea7.png)

**Comment by sgpapakirk** [comment]
I have now finished all coding and testing for this "G4 - ProjectDetails" report.
I have committed and pushed to my Stylianos_Dev code branch, and then merged its changes into our master one.

Please note that in the original Crystal Report some sub-reports would print on a new page the top grid labels, while others wouldn't. I have now standardized to always print again these top grid labels, if say the grid is shown on following pages.

Extra place to test this report from:
1) Click on the top "Permits" tab.
2) From the shown grid, pick a row and click on its middle Edit (pencil) icon.
3) In the shown page, find the "Project" label and click on the "..." button next to it.
4) In the shown grid, pick any row and click on its right-most "Print PDF" icon.

**Comment by vijme** [comment]
Deployed and Available for testing

**Comment by HollySchuelerKCI** [comment]
The report has been successfully validated in both user workflows as mentioned above in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good but is one of the lines off center under the project resource impacts?

**Comment by sgpapakirk** [comment]
In the grids shown under the "Project Resource Impact Details" area I made the first column's header
to not be underlined and to be left-aligned, closer to the original look.
I have also merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by sgpapakirk** [comment]
This issue has now being deployed to http://oed.kci.com/shaportal

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[G4 - ProjectDetails - 445 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2657888/G4.-.ProjectDetails.-.445.-.FINAL.OUTPUT.pdf)

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI I found these other ways that this "Project Details" report is generated:

3rd way:
1) Still in the QA Toolkit, click on the top right side's "Admin" tab.
2) Click in the shown "Data Cleanup" tab.
3) In this "Project Duplicates" page, in the shown grid, pick any row and click on its 4th "Print" icon (a printer).

Unfortunately for now the following 4th and 5th way don't currently work.
We get an "ORA-00942: table or view does not exist" exception.
4th way:
1) Login in the IEM Toolkit.
2) Click on the top "Projects" tab.
3) In the shown grid, pick any row and click on its 4th "Print" icon (a PDF document).

5th way:
1) Login in the MDE Toolkit.
2) Click on the top "Projects" tab.
3) In the shown grid, pick any row and click on its 4th "Print" icon (a PDF document).

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
