### ISSUE TITLE
SSRS Conversion: IEM3 - DailyInspectionTemplate

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#447]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Login to the EM Toolkit
2. Click the Inspections Tab
3. Scroll to the bottom of the page and enter a date into the Create Inspection Template
![image](https://user-images.githubusercontent.com/25441512/45628671-912ce500-ba62-11e8-8b16-e3610faa94d2.png)
4. Click the Create button

===================================================================
### Example of Report
**Full Downloadable Report:** [IEM3 - DailyInspectionTemplate.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398399/IEM3.-.DailyInspectionTemplate.pdf) (First page below)
![image](https://user-images.githubusercontent.com/25441512/45628763-c802fb00-ba62-11e8-915c-f87b9dde0595.png)

**Comment by vijme** [comment]
Implemented in dev.

Minor Design Changes:
1. Weather/Soil/Stream : All placed in straight line. 
2. Due to SSRS limitations, Inspection Date value cannot be repeated in all pages. A workaround is implemented and the date is now displayed on the top left on all pages. Due to this the table header is repeated on all pages.

I hope these changes are minor, but let me know if something needs to be changed.

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Development Environment._**

@Tad-Daniel Please refer to Viji's comment above regarding the SSRS design modifications she needed to implement.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
FINAL REPORT OUTPUT SAMPLE:
[IEM 3 - DailyInspectionTemplate - 447 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2703203/IEM.3.-.DailyInspectionTemplate.-.447.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
