### ISSUE TITLE
SSRS Conversion: G1 - ProjectSearch

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#448]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Projects Tab
2. Expand the Search Panel
3. Enter Search Parameters
4. Click Search
![image](https://user-images.githubusercontent.com/25441512/45633088-eb32a800-ba6c-11e8-86bd-881e5e083021.png)
5. Click Print
6. Click Search Results

===================================================================
### Example of Report
**Full Downloadable Report:**[G1 - ProjectSearch.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398023/G1.-.ProjectSearch.pdf) (First page below)
![image](https://user-images.githubusercontent.com/25441512/45633157-12897500-ba6d-11e8-9e5d-394ea27efdb9.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
While testing it appears that when the report is generated every other page is blank. Unsure what may be causing this issue.

**Comment by vijme** [comment]
Issue fixed

**Comment by HollySchuelerKCI** [comment]
The above issue has been resolved.

This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good and appears to be working correctly

**Comment by HollySchuelerKCI** [comment]
This report has been tested and successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[G1 - ProjectSearch - 448 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2657883/G1.-.ProjectSearch.-.448.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
