### ISSUE TITLE
SSRS Conversion: IEM1 - DailyInspectionListReport

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#450]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, click Edit subtab
2. Select a project using the select project button in the right column
3. Expand the search Panel
4. Click Print
![image](https://user-images.githubusercontent.com/25441512/45760343-d0406f00-bbf7-11e8-9175-6e0643cb84d2.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [IEM1 - DailyInspectionListReport.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398411/IEM1.-.DailyInspectionListReport.pdf) First page below)

![image](https://user-images.githubusercontent.com/25441512/45760443-15fd3780-bbf8-11e8-8b76-9ae9e732fc19.png)

**Comment by HollySchuelerKCI** [comment]
@vijme Below are my comments regarding IEM 1:
1.  Please change (or as close to) the following green: **008000**
2.  Please change the column header font to arial, and remove green background. Below is the original report.
![image](https://user-images.githubusercontent.com/25441512/49957579-47735f80-fed6-11e8-85b8-5fe68fd4084a.png)

**Comment by vijme** [comment]
@HollySchuelerKCI , Changed all others except the green background, as it looks much better

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
FINAL REPORT OUTPUT SAMPLE:
[IEM 1 - DailyInspectionListReport - 450 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2703128/IEM.1.-.DailyInspectionListReport.-.450.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
