### ISSUE TITLE
SSRS Conversion: IEM7 - IssueSummaryReport

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#453]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the EM Toolkit --> Inspections Tab, select a project
2. Click the Issues Tab
3. Expand the Search Panel
4. Click Print
![image](https://user-images.githubusercontent.com/25441512/45762994-9d997500-bbfd-11e8-9336-601f33918020.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [IEM7 - IssueSummaryReport.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2398338/IEM7.-.IssueSummaryReport.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/45763096-cde11380-bbfd-11e8-9b97-cabc98d227b4.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[IEM 7 - IssueSummaryReport - 453 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2746585/IEM.7.-.IssueSummaryReport.-.453.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
