### ISSUE TITLE
SSRS Conversion: G3 - ProjectCommunicationReport

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#454]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click Projects Tab
2. Click Comment button found in the right column
3. Expand Search Panel
4. Click Print

![image](https://user-images.githubusercontent.com/25441512/45884180-3278ab80-bd81-11e8-91b1-838a9905d759.png)

===================================================================

**Comment by slmessier** [comment]
@Tad-Daniel  - You may recall this report has never been functional as the toolkit was inherited without the UI code to successfully connect this report to the toolkit database. 

**Please provide authorization to "close" the work item within the context of WO 23 using the approach below.** This plans reflects conversations we have agreed to verbally, just looking to get our approach on record:

1. **Under WO#24 Viji would perform the code updates required to connect report to the database.** 

2. This would be performed **distinctly within SHA's internal application environment, as it represents the "master", and optimal target for new code development going forward.**

3. As such we are suggesting this work item be considered exempt, as a form of completion under WO#23, and will queue up for development under WO#24.

Please advise - thank you!

**Comment by Tad-Daniel** [comment]
I agree

**Comment by vijme** [comment]
This report has been implemented using the developers design. Besides, Some UI aspects of the page like buttons and alignment have been fixed. (In comments response page). Please let me know if there needs to be any additions/modifications in the report.

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good in dev. ready for staging

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
This report has been validated by project team in the **_Staging Environment._**
