### ISSUE TITLE
SSRS Conversion: QA3 - QAInspections

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#455]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, click the QA1 subtab
2. Expand Search Panel
3. Enter Search Parameters
4. Click Search
5. Click Print

![image](https://user-images.githubusercontent.com/25441512/45884904-11b15580-bd83-11e8-8506-0ac7f1e302ec.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA3 - QAInspections.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2405614/QA3.-.QAInspections.pdf)   (First page below)

![image](https://user-images.githubusercontent.com/25441512/45885712-1ecf4400-bd85-11e8-9062-83c66964d11f.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA3 - QAInspections - 455.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2657844/QA3.-.QAInspections.-.455.pdf)
