### ISSUE TITLE
SSRS Conversion: QA8 - InspectionWeighted

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#456]
### Additional Re-Design Specification: 

===================================================================
### Steps to Generate Report
1. From the Inspections Tab, Click the QA1 subtab
2. Locate project with QA1 Inspection of OOC61(07/01/2011) 
3. Click Edit
4. Click Print
![image](https://user-images.githubusercontent.com/25441512/45886494-46bfa700-bd87-11e8-8295-2d3cd76e6a3e.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA8 - InspectionWeighted.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2405685/QA8.-.InspectionWeighted.pdf)  (First page below)
![image](https://user-images.githubusercontent.com/25441512/45886538-635bdf00-bd87-11e8-9f63-6957261effae.png)

**Comment by vijme** [comment]
Implemented in dev. OOC61(07/01/2011) type reports to be tested for this type.

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
The alignment of the checkbox's and the associated text much match the original.  
The checkbox's should al be the same size  ( this was fixed on previous report utilizing standard box's)
Signature line descriptors are also out of alignment.

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
I am not seeing any changes.

**Comment by HollySchuelerKCI** [comment]
@Tad-Daniel this report is for the OOC61(07/01/2011) form. In DEV you can refer to **Contract No. 123333** for validation.

**Comment by vijme** [comment]
All changes to InspectionQA1 applied to this report type as well.

**Comment by Tad-Daniel** [comment]
Everything looks goods  Please ensure that the attachment description is include on the page with the photo.

**Comment by vijme** [comment]
@Tad-Daniel, it is verified that the description is included on the photo attachment page, (As it has always been, we cannot include description on a pdf attachment though). 

Please see the example report below

[QAInsp_123333_20181203_sampleattachment.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2728262/QAInsp_123333_20181203_sampleattachment.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 8 - InspectionWeighted - 456 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2746610/QA.8.-.InspectionWeighted.-.456.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
