### ISSUE TITLE
SSRS Conversion: QA20 - ModReport

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#457]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click Projects Tab
2. Click Mods Summary subtab
3. Expand Search Panel
4. Click Print
![image](https://user-images.githubusercontent.com/25441512/45887634-3957ec00-bd8a-11e8-9c7f-78de393739e1.png)

===================================================================
### Example of Report
**Full Downloadable Report:** [QA20 - ModReport.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2405784/QA20.-.ModReport.pdf)   (First page below)

![image](https://user-images.githubusercontent.com/25441512/45887666-4ecd1600-bd8a-11e8-924a-ee5a98bd1f88.png)

**Comment by vijme** [comment]
Implemented in dev

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA20 - ModReport - 457.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2657831/QA20.-.ModReport.-.457.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
