### ISSUE TITLE
SSRS Conversion: MDE1 - Accounting

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#462]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Login to the MDE Toolkit as the profile Permit Reviewer
2. From the Reviews Tab, click print
3. Click Accounting from the Pop-Up window
![image](https://user-images.githubusercontent.com/25441512/45892010-f9e2cd00-bd94-11e8-9b7f-5557c77d4e4b.png)

===================================================================
### Example of Report
**Full Downloadable Report:**   [MDE1 - Accounting.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2406064/MDE1.-.Accounting.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45892447-2a773680-bd96-11e8-8df3-108f4bb962b3.png)

**Comment by sgpapakirk** [comment]
I have now finished all coding and testing for this "MDE1 - Accounting" report.
Please don't forget to test both the PDF and the Excel output from the shown popup.

**Comment by sgpapakirk** [comment]
Holly, I have done changes to this report. I now use:
1) Arial 8.25 pt for the grid header row
2) Arial 8 pt for the grid content rows
I adjusted a bit the column widths to be less crowded.
I just merged these changes in both the master & the viji_reports code branches.

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[MDE1 - Accounting - 462 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658324/MDE1.-.Accounting.-.462.-.FINAL.OUTPUT.pdf)
