### ISSUE TITLE
SSRS Conversion: MDE2- Current

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#463]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Login to the MDE Toolkit as the profile Permit Reviewer
2. From the Reviews Tab, click print
3. Click Current from the Pop-Up window
![image](https://user-images.githubusercontent.com/25441512/45892572-7de98480-bd96-11e8-8add-6ee7a58c60e3.png)

===================================================================
### Example of Report
**Full Downloadable Report:**  [MDE2- Current.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2406088/MDE2-.Current.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/45892632-a4a7bb00-bd96-11e8-80fd-e286509928f9.png)

**Comment by sgpapakirk** [comment]
I have now finished all coding and testing for this "MDE2 - Current" report.
I have merged its code changes from my Stylianos_Dev branch into the master one.
Please don't forget to test both the PDF and the Excel output from the shown popup.

**Comment by sgpapakirk** [comment]
Holly, I have done changes to this report. I now use:
1) Arial 8.25 pt for the grid header row
2) Arial 8 pt for the grid content rows
I adjusted a bit the column widths to be less crowded, and I fixed this "Consultant#" header, too.
I just merged these changes in both the master & the viji_reports code branches.

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications have been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[MDE2 - Current - 463 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658314/MDE2.-.Current.-.463.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
