### ISSUE TITLE
SSRS Conversion: MDE3 - EPD

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#464]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Login to the MDE Toolkit as the profile Permit Reviewer
2. From the Reviews Tab, click print
3. Click EPD (any status) from the Pop-Up window
![image](https://user-images.githubusercontent.com/25441512/45892754-1253e700-bd97-11e8-9bc5-72a3a42f93a7.png)

===================================================================
### Example of Report
**Full Downloadable Report:**   [MDE3 - EPD.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2406101/MDE3.-.EPD.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45892793-2c8dc500-bd97-11e8-93c8-b8543cf2b7db.png)

**Comment by sgpapakirk** [comment]
I have now finished all coding and testing for this "MDE3 - EPD" report.
I have merged its code changes from my Stylianos_Dev branch into the master one.
Please don't forget to test both the PDF and the Excel output from the shown popup.

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by sgpapakirk** [comment]
Holly, I have done changes to this report. I now use:
1) Arial 8.25 pt for the grid header row
2) Arial 8 pt for the grid content rows

I adjusted a bit the column widths to be less crowded, and I fixed this "Consultant#" header, too.
I just merged these changes in both the master & the viji_reports code branches.

**Comment by sgpapakirk** [comment]
This issue has now being deployed to http://oed.kci.com/shaportal

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[MDE3 - EPD - 464 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2658309/MDE3.-.EPD.-.464.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
