### ISSUE TITLE
SSRS Conversion: MDE5 - EPDWorkload

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#465]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Login to the MDE Toolkit as the profile Permit Reviewer
2. From the Reviews Tab, click print
3. Click EPD Workload from the Pop-Up window
![image](https://user-images.githubusercontent.com/25441512/45893099-3106ad80-bd98-11e8-8991-479a76a25f26.png)

===================================================================
### Example of Report
**Full Downloadable Report:**   [MDE5 - EPDWorkload.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2406129/MDE5.-.EPDWorkload.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/45893205-762adf80-bd98-11e8-9ea1-10d97ec7d8e6.png)

**Comment by sgpapakirk** [comment]
(exact same comment as in the 472 issue):
Holly, I have finished coding this report. Similar to the other MDE reports, I adjusted a bit the column widths to be less crowded. I also now use:
1) Arial 8.25 pt for the grid header row
2) Arial 8 pt for the grid content rows

**Please note though this one limitation:** 
When you use the PDF export, there is no problem rendering of the small 2 sub-report grids that show up in certain rows. You can see these 2 grids in the record that has FMIS =12345, and some other ones.
**But unfortunately, the current Excel export renders only the main grid rows, not these small 2 sub-report grids in certain rows. I tried many approaches, and internet suggestions, but nothing worked.**
I had to use sub-reports to accomplish this report.
Now these are my errors when I tried to use 2 grid tables within the main grid table instead:
1) "Subreports within table/matrix cells are ignored."
2) "Data Regions within table/matrix cells are ignored."

As far as I know now we actually use SSRS ver. 2005 which is fairly old.
I am positive that if we upgrade to at least 2008, 2010 or higher, this Excel issue will be fixed.

Finally, I just merged these changes in both the master & the viji_reports code branches.

**Comment by sgpapakirk** [comment]
This issue has now being deployed to http://oed.kci.com/shaportal

**Comment by HollySchuelerKCI** [comment]
The PDF version of this report has been successfully validated by the project team in the **_Development Environment._**

The Excel version of this report was executable, and as the Developer noted above the sub reports do not display due to SSRS limitations.

**_Will discuss these limitations with the stakeholder to determine best path forward._**

**Comment by Tad-Daniel** [comment]
I just downloaded the reports and the nested information appears in the XLS report.  What am I missing?

**Comment by Tad-Daniel** [comment]
I got it now.   I am reaching out to EPD for input.  As soon as I hear back I will let you know..

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, I have now finished coding so that we can now correctly produce both the PDF and the Excel files.
As I said in the Issue 467, I couldn't use say this new Excel .rdlc to produce also the PDF files because
it was leaving the main grid’s first row empty on the pages 2, 3, 4, etc. (a weird rendering issue that I couldn’t fix).

Finally, I just merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by HollySchuelerKCI** [comment]
Both the PDF and Excel versions of this report has been successfully tested by the project team in the **_Development Environment._**

Sub-Reports were successfully incorporated into the Excel report.

**Comment by Tad-Daniel** [comment]
Looks Good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[MDE 5 - EPDWorkload - 465 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2699909/MDE.5.-.EPDWorkload.-.465.-.FINAL.OUTPUT.pdf)

**Comment by Tad-Daniel** [comment]
The Final Report is accepted

**Comment by HollySchuelerKCI** [comment]
This report including sub-reports have been validated by the project team in the **_Staging Environment._**
