### ISSUE TITLE
SSRS Conversion: MDE6 - MDE

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#466]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Login to the MDE Toolkit as the profile Permit Reviewer
2. From the Reviews Tab, click print
3. Click MDE from the Pop-Up window
![image](https://user-images.githubusercontent.com/25441512/45893335-e0438480-bd98-11e8-8884-bed180dd7d0c.png)

===================================================================
### Example of Report
**Full Downloadable Report:**   [MDE6 - MDE.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2406143/MDE6.-.MDE.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/45893388-0c5f0580-bd99-11e8-8209-0d3aaf5697c9.png)

**Comment by sgpapakirk** [comment]
I have now finished all coding and testing for this "MDE6 - MDE" report.
I have merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.
Please don't forget to test both the PDF and the Excel output from the shown popup.

**Comment by sgpapakirk** [comment]
Viji has deployed this report to http://oed.kci.com/shaportal

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**
