### ISSUE TITLE
SSRS Conversion: MDE10 - WorkloadEPD

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#470]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate (3) Reports

1. EPD - Sorted by Team Leader

     - Login to the MDE Toolkit as the profile Permit Reviewer
     - From the Reviews Tab, click print
     - Locate EPD, and click Sorted by Team Leader

![image](https://user-images.githubusercontent.com/25441512/50015649-1017b800-ff95-11e8-9ac1-b2d4f2481a0f.png)

2. EPD - Sorted by Ad / Due, Bid, Prod

     - Login to the MDE Toolkit as the profile Permit Reviewer
     - From the Reviews Tab, click print
     - Locate EPD, and click Sorted by Ad / Due, Bid, Prod

![image](https://user-images.githubusercontent.com/25441512/50015751-448b7400-ff95-11e8-9ba8-6ab1ddaa65a1.png)

3. EPD - Sorted by Contract #

     - Login to the MDE Toolkit as the profile Permit Reviewer
     - From the Reviews Tab, click print
     - Locate EPD, and click Sorted by Contract # 

![image](https://user-images.githubusercontent.com/25441512/50015804-671d8d00-ff95-11e8-9dc1-80234fdae309.png)

===================================================================
### Example of EPD - Sorted by Team Leader Report
**Full Downloadable Report:**  [MDE10 - WorkloadEPD - Sorted By Team Leader.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2681021/MDE10.-.WorkloadEPD.-.Sorted.By.Team.Leader.pdf)  (First page below)

![image](https://user-images.githubusercontent.com/25441512/50016047-12c6dd00-ff96-11e8-94bf-31fe2f6c3d58.png)

### Example of EPD - Sorted by Ad / Due, Bid, Prod
**Full Downloadable Report:** [MDE10 - WorkloadEPD - Sorted By AdDueBidProd.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2681030/MDE10.-.WorkloadEPD.-.Sorted.By.AdDueBidProd.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/50016134-4bff4d00-ff96-11e8-95d6-db245d853f46.png)

### Example of EPD - Sorted by Contract #  
**Full Downloadable Report:** [MDE10 - WorkloadEPD - Sorted By Contract #.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2681035/MDE10.-.WorkloadEPD.-.Sorted.By.Contract.pdf) (First page below)

![image](https://user-images.githubusercontent.com/25441512/50016257-a8626c80-ff96-11e8-9d6b-f1c87764ad84.png)

**Comment by sgpapakirk** [comment]
@HollySchuelerKCI, I have now finished coding this report. Please note that it doesn't contain subreports, so I used only 1 .rdlc file.
Please note that this report has some extra functionality. If the end user has a value selected from the main page's "Reviewer Org." drop down list, then in the report you will see under the main top header a smaller one like this say: "Reviewed by McCormick Taylor".
Also don't forget to test noth the PDF and the Excel files produced.

Finally, I just merged my "Stylianos_Dev" code branch into the "master" and the "viji-reports" branches.

**Comment by vijme** [comment]
Deployed

**Comment by HollySchuelerKCI** [comment]
#### EPD - Sorted by Team Leader (PDF and EXCEL)
Both the PDF and Excel versions of this report has been successfully tested by the project team in the Development Environment.

#### EPD - Sorted by Ad / Due, Bid, Prod
Both the PDF and Excel versions of this report has been successfully tested by the project team in the Development Environment.

#### EPD - Sorted by Contract #  
Both the PDF and Excel versions of this report has been successfully tested by the project team in the Development Environment.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE FOR EPD SORTED BY TEAM LEADER:
[MDE 10 - WorkloadEPD_Sorted_by_TeamLeader  - 470 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2721133/MDE.10.-.WorkloadEPD_Sorted_by_TeamLeader.-.470.-.FINAL.OUTPUT.pdf)

### FINAL REPORT OUTPUT SAMPLE FOR EPD SORTED BY AD / DUE, BID, PROD:
[MDE 10 - WorkloadEPD_Sorted_by_AD_Due_BidProd  - 470 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2721141/MDE.10.-.WorkloadEPD_Sorted_by_AD_Due_BidProd.-.470.-.FINAL.OUTPUT.pdf)

### FINAL REPORT OUTPUT SAMPLE FOR EPD SORTED BY CONTRACT NUMBER:
[MDE 10 - WorkloadEPD_Sorted_by_ContractNo  - 470 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2721145/MDE.10.-.WorkloadEPD_Sorted_by_ContractNo.-.470.-.FINAL.OUTPUT.pdf)

**Comment by Tad-Daniel** [comment]
All three reports are accepted

**Comment by HollySchuelerKCI** [comment]
1. EPD - Sorted by Team Leader
     - The PDF and Excel reports have been successfully validated by the project team in the **_Staging Environment._**

2. EPD - Sorted by Ad / Due, Bid, Prod
     - The PDF and Excel reports have been successfully validated by the project team in the **_Staging Environment._**

3. EPD - Sorted by Contract #
     - The PDF and Excel reports have been successfully validated by the project team in the **_Staging Environment._**
