### ISSUE TITLE
SSRS Conversion: QA16 ModApproval 

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#473]
### Additional Re-Design Specification: 
(None)

===================================================================
### Steps to Generate Report
1. Click the Reporting Tab
2. Click the Reports subtab
3. Locate Modification Summary
4. Enter date range
5. Click Report

![image](https://user-images.githubusercontent.com/25441512/46804632-1ee1b480-cd31-11e8-8213-05c4dfae284f.png)

===================================================================
### Example of Report
**Full Downloadable Report:**   [QA16 ModApproval.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2468908/QA16.ModApproval.pdf)  (First page below)
![image](https://user-images.githubusercontent.com/25441512/46804749-76802000-cd31-11e8-945d-f0a3a0c9c778.png)

**Comment by HollySchuelerKCI** [comment]
This report has been successfully validated by the project team in the **_Development Environment._**

Awaiting stakeholder confirmation of proffered color palate.

**Comment by Tad-Daniel** [comment]
ensure there is a space in between any bars of the charts.  It is inconsistent.   some have a space and some do not

**Comment by vijme** [comment]
Chart redesigned according to latest spec of inter bar spaces.

**Comment by HollySchuelerKCI** [comment]
This report with the above modifications has been validated by the project team in the **_Development Environment._**

**Comment by Tad-Daniel** [comment]
Our data is sporadic in the DEV environment so I am unable to see a full 4 quarters charted out. It currently appear that not all the quarters show in the report.

**Comment by Tad-Daniel** [comment]
Looks good

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the stakeholder in the **_Development Environment._**

**Comment by HollySchuelerKCI** [comment]
### FINAL REPORT OUTPUT SAMPLE:
[QA 16 - ModApproval - 473 - FINAL OUTPUT.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2703545/QA.16.-.ModApproval.-.473.-.FINAL.OUTPUT.pdf)

**Comment by HollySchuelerKCI** [comment]
This report has been validated by the project team in the **_Staging Environment._**

For testing purposes, please use 7/1/2016 - 6/3/2017 as the report date range.
