### ISSUE TITLE
QA Toolkit - Attach to Projects: Documents, Sheets & Plates, & Incentive Periods

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#48]
1. Ability for any user to add Documents, Sheets & Plates and Incentive Periods into a project record 
   1. Ability to sort “Documents” in the project record by column header

![image](https://cloud.githubusercontent.com/assets/4098544/3510785/c98a5e30-06a9-11e4-8e8a-5e3b83f4f103.png)

**Comment by Tad-Daniel** [comment]
Parts of this item have been addressed and the remainder will be in a new task.  Item closed
