### ISSUE TITLE
All (3) Toolkits - Cancel Delete Function

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#490]
### The QA Toolkit is not responding appropriately when users cancel the workflow to delete a permit (Permits Menu).

**Steps to Replicate:**
1. On the Reviews Menu, click the Delete button to delete an existing review record from the grid.
2. Click Cancel on the confirmation window.
3. **The MDE toolkit does not respond.**

**Example:**
![MDE-Cancel-DeleteReview](https://user-images.githubusercontent.com/4098544/66930767-14708f80-f003-11e9-87f4-c7db8df0335a.gif)

**Comment by slmessier** [comment]
@viji this issue persists as of this writing @AndyWuKCI

**Comment by vijme** [comment]
Issue resolved and ready for testing

**Comment by slmessier** [comment]
@vijme @andywu123 
Issue appears resolved in previously identified regions of UI. However, **I have encountered this issue on the the QA Toolkit - Permit Templates Menu. Please investigate whether this can be reconciled using the same solution as developed previously.**

![Cancel_DeletePermitTemplate20191125](https://user-images.githubusercontent.com/4098544/69571631-7fad6a00-0f90-11ea-8a8b-ba3ae08f3e6a.gif)

**Comment by vijme** [comment]
Fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated for IEM, MDE and QA Toolkits.
