### ISSUE TITLE
IEM & MDE (2) Toolkits - Admin Update Existing User - Error Msg & Unable to Save

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#491]
### (The QA Toolkit does not appear to be impacted by this issue.)

**Steps to Replicate:**
1. In the Admin Menu, click to edit an existing user
2. **The system displays an error message without any triggered action from the user**
3. Perform updates to the user configuration information, & click Update button to commit.
4. **The system does not commit the updated information.** (exit and view again to validate)

**Example:**
![Admin_EditUser_Errors](https://user-images.githubusercontent.com/4098544/67039840-37c53880-f0f0-11e9-9cfc-1217a1840452.gif)

**Comment by slmessier** [comment]
@vijme this issue is preventing testing across multiple system profiles as I am unable to update my user profile. Could you please process with high priority so that we are able to proceed? Thank you!

@HollySchuelerKCI fyi

**Comment by vijme** [comment]
@slmessier, this issue is due to the fact that I updated the database for development. Didn’t realize that both dev and testing are working on same db. If we dont see any major changes, then i think it would be ideal to push the current code into testing. I can do that tomorrow. What do you day?

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated in the IEM and MDE Toolkits.
