### ISSUE TITLE
QA Toolkit - Error Creating New MOD

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#492]
An error has occurred in the QA Toolkit when the user selects "New Request" when creating a new MOD.

### **Steps to Replicate:**
1. Inspections -> QA Tab
2. Select a Project
![image](https://user-images.githubusercontent.com/25441512/67109556-c1cbda80-f19e-11e9-87d4-c3ebd8782cf2.png)
3.  Select MODS Tab
![image](https://user-images.githubusercontent.com/25441512/67109885-736b0b80-f19f-11e9-91c8-134bd122c157.png)

4. Click the "New Request" Button
![image](https://user-images.githubusercontent.com/25441512/67109659-03f51c00-f19f-11e9-9ce0-332ca3430966.png)
5. Error Message:
![image](https://user-images.githubusercontent.com/25441512/67109686-11aaa180-f19f-11e9-8a54-a4ff7b5b6fd4.png)

**Comment by vijme** [comment]
Issue fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team.
