### ISSUE TITLE
QA Toolkit - QA3 Error

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#493]
An error has occurred when the user selects the QA3 button in the QA Toolkit.

Steps to Replicate:
1.Inspections -> QA Tab
2. Select a Project
![image](https://user-images.githubusercontent.com/25441512/67110519-f3de3c00-f1a0-11e9-82ba-2f391df6ce31.png)
3. Select MODS Tab
![image](https://user-images.githubusercontent.com/25441512/67110559-0b1d2980-f1a1-11e9-9db2-6049664e59b5.png)
4. Click QA3 Button
![image](https://user-images.githubusercontent.com/25441512/67110652-40297c00-f1a1-11e9-8f68-a8c453681194.png)
5. Error Message:
![image](https://user-images.githubusercontent.com/25441512/67110683-4b7ca780-f1a1-11e9-94f1-242a22e91cd1.png)

**Comment by vijme** [comment]
Issue fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team.
