### ISSUE TITLE
QA Toolkit - Print Detailed PDF of QA Calendar

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#494]
An issue has occurred when the user would like to print the QA Calendar while selected Detailed PDF.

### **Steps to Replicate:**
1. Inspections -> QA Calendar
2. Expand Search Panel
![image](https://user-images.githubusercontent.com/25441512/67112708-d65fa100-f1a5-11e9-867f-91ee4a9fb4d8.png)
3. Click Print
4. Select Detailed PDF
![image](https://user-images.githubusercontent.com/25441512/67112765-fc854100-f1a5-11e9-881f-54a08a96d62a.png)
5. New tab opens in the web browser, however the PDF does not open

**Comment by vijme** [comment]
Issue fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team.
