### ISSUE TITLE
QA Toolkit - Reference Docs Landing Page

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#499]
_Test results that were initiated on 11/7/2019_

The following (3) items were identified when comparing hyperlink functionality available on the Reference Document Section of the QA Toolkit Landing Page.

**1. The list of Reference Docs in development does **NOT** match the list currently in Production.**

Dev Environment:
![image](https://user-images.githubusercontent.com/25441512/68425315-daaf2680-0173-11ea-9fb4-f6c6115e1241.png)

Production Environment:
![image](https://user-images.githubusercontent.com/25441512/68425373-f5819b00-0173-11ea-8f70-f810f6d7aa6e.png)

**2. The Modification instructions document contains a blank file**

**3. The SWM instructions link to the blank Modification document.**

**Comment by vijme** [comment]
It would not match the production. What appears here and the actual document is **completely configurable by the admin using the tab "Admin->Standard Forms".** Any document that is configured to be available to **contractors** in that tab will appear here.

**Comment by HollySchuelerKCI** [comment]
This issue will be dependent on stakeholder via the path above. This issue has been resolved.
