### ISSUE TITLE
ALL Toolkits - Error Generating PDF Reports

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#500]
_Test results that were initiated on 11/7/2019_

**The system produces error messages generating a PDF report for each of the following (4) PDF functions within the QA Toolkit and IEM Toolkit Admin Menu.**

### QA Toolkit
**1. Under the User List Tab, an error occurs when the user selects the Subscription Summary Button**
![image](https://user-images.githubusercontent.com/25441512/68426039-4645c380-0175-11ea-9d7c-011c53ed8a87.png)
![image](https://user-images.githubusercontent.com/4098544/68428330-f61d3000-0179-11ea-8cef-3bbb30d1aa64.png)

**2. Under the User List Tab, an error occurs when the user selects the Print List Button**
![image](https://user-images.githubusercontent.com/25441512/68426052-4d6cd180-0175-11ea-8f00-38afa31b6c4a.png)
![image](https://user-images.githubusercontent.com/4098544/68428322-edc4f500-0179-11ea-8710-5a234f5b9972.png)

**3. Under the Data Cleanup Tab -> Project Dups, an error occurs when the user selects Print for an item in the grid.**
![image](https://user-images.githubusercontent.com/25441512/68426301-d84dcc00-0175-11ea-9d1d-af9e029e5ff1.png)
![image](https://user-images.githubusercontent.com/4098544/68428384-12b96800-017a-11ea-97fb-7e83bff38434.png)

**4. Under the Data Cleanup Tab -> Inspection Dups, an error occurs when the user selects Print under the Search Panel.**
![image](https://user-images.githubusercontent.com/25441512/68426401-0c28f180-0176-11ea-835f-5d5c5cc77d17.png)
![image](https://user-images.githubusercontent.com/4098544/68428413-2238b100-017a-11ea-92fb-91a01b083fc6.png)

### IEM Toolkit
**1.Under the User List Tab, an error occurs when the user selects the Print List Button**
![image](https://user-images.githubusercontent.com/25441512/68488742-bc006c80-0213-11ea-9d07-6624856a9786.png)

![image](https://user-images.githubusercontent.com/25441512/68488852-efdb9200-0213-11ea-900c-19c1ff8c7f35.png)

### MDE Toolkit
**1.Under the User List Tab, an error occurs when the user selects the Print List Button**
![image](https://user-images.githubusercontent.com/25441512/68426052-4d6cd180-0175-11ea-8f00-38afa31b6c4a.png)

![image](https://user-images.githubusercontent.com/25441512/68499815-2f13de00-0228-11ea-953c-6d74e996b331.png)

**Comment by vijme** [comment]
Issue fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
All the above issues have been successfully validated by the project team.
