### ISSUE TITLE
ALL Toolkits - Logins by Hour Graph Does Not Appear

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#501]
_Test results that were initiated on 11/7/2019 and 11/8/2019_

The following issue has occurred under the Admin Tab of the QA, MDE, and IEM Toolkits.

### QA Toolkit

**1. Under the Analysis Tab -> Login Analysis, the Logins by Hour graph is NOT displayed on the page.**

Development Environment:
![image](https://user-images.githubusercontent.com/25441512/68427387-016f5c00-0178-11ea-8ff7-4aad08130fef.png)

Staging Environment:
![image](https://user-images.githubusercontent.com/25441512/68427356-f4526d00-0177-11ea-8a18-23a8ddaaa1c3.png)

### IEM Toolkit

**1. Under the Admin Tab -> Login Analysis Tab, the Logins by Hour graph is NOT displayed on the page.**

![image](https://user-images.githubusercontent.com/25441512/68489091-66788f80-0214-11ea-9902-1f7dcb36e8e9.png)

### MDE Toolkit
**1. Under the Admin Tab -> Login Analysis Tab, the Logins by Hour graph is NOT displayed on the page.**
![image](https://user-images.githubusercontent.com/25441512/68499971-8dd95780-0228-11ea-992f-be0f831cd5f1.png)

**Comment by vijme** [comment]
Issue fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated in the IEM, MDE, and QA Toolkits.
