### ISSUE TITLE
IEM & MDE Toolkits - Request New Account & Update Account Error

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#502]
_Test results that were initiated on 11/8/2019_

The following issues have occurred on the IEM and MDE Toolkits Login Webpages.

**1. When the user selects the Request New Account button, the system returns a 404 Error.**
![image](https://user-images.githubusercontent.com/25441512/68486741-be60c780-020f-11ea-8848-5497fdc557cc.png)

![image](https://user-images.githubusercontent.com/25441512/68486768-ccaee380-020f-11ea-88a1-30938fccd007.png)

**2. When the user selects the Update Account button, the system returns a 404 error.**
![image](https://user-images.githubusercontent.com/25441512/68486839-f9fb9180-020f-11ea-959c-40a5df0461d1.png)

![image](https://user-images.githubusercontent.com/25441512/68486768-ccaee380-020f-11ea-88a1-30938fccd007.png)

**Comment by vijme** [comment]
Issue fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team.
