### ISSUE TITLE
QA Toolkit - New User First Time Login

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#504]
_Error occurred on 11/14/2019 during Security Requirements testing._
This issue has been merged with #505 

**An error occurs when a new account user attempts to login for the first time after his/her account has been created and approved by an Admin. The New User password does not contain number or special characters in them.**

### Steps to Replicate:

1. Admin logs into QA Toolkit
2. Click Admin Tab
3. Click New User button to create a new user
-or-
4. New User requests a new account on the landing page
5. Toolkit Admin Clicks Analysis Tab
6. Approve Accounts
7. Select Requested Account
8. Enter new user login
9. Click Approve

____________________________________________________________________________

### New User Enters Login and Password. The system returns the following error:
![image](https://user-images.githubusercontent.com/25441512/68893918-2a519d00-06f4-11ea-92dc-5d83820a7dc9.png)

**Comment by vijme** [comment]
Issue fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue will require email notifications to fully test and validate. Testing will begin once email functionality has been enabled,

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team.
