### ISSUE TITLE
Password generated for new user doesnot adhere to standards

### ISSUE THREAD

**Issue by vijme** [kcigeospatial/sha_oed_issues#505]
New User password doesnot contain number or special characters in them.

**Comment by AndyWuKCI** [comment]
@HollySchuelerKCI @slmessier  @vijme It's fixed. Please feel free to test.

**Comment by HollySchuelerKCI** [comment]
This issue will require email notifications to fully test and validate. Testing will begin once email functionality has been enabled.

**Comment by HollySchuelerKCI** [comment]
This issue is related to issue #504 and have been merged.
