### ISSUE TITLE
Inspection View page has inactivity pop ups show up at the bottom of page

### ISSUE THREAD

**Issue by vijme** [kcigeospatial/sha_oed_issues#506]
Inspection->QA1->View Inspection. Scroll to the bottom of page. Popups are shown.

**Comment by slmessier** [comment]
@vijme @andywu123  - please be advised these pop ups appear at the bottom of every page in all toolkits (that I have seen so far):

QA Toolkit:
![image](https://user-images.githubusercontent.com/4098544/69176995-c274cb00-0ad4-11ea-99db-5fbadc3ed4fe.png)

MDE Toolkit:
![image](https://user-images.githubusercontent.com/4098544/69177036-d1f41400-0ad4-11ea-9956-c6d95a402c2f.png)

IEM Toolkit:
![image](https://user-images.githubusercontent.com/4098544/69177068-dcaea900-0ad4-11ea-8b9e-447f2dfe36c5.png)

**Comment by vijme** [comment]
Issue seems to be due to a missing javascript refrence.

**Comment by AndyWuKCI** [comment]
Hi Holly, The issue is fixed. Feel free to test. Thank you!

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated in IEM, MDE and QA Toolkits.
