### ISSUE TITLE
All Toolkits - Search Filter Panels - Missing Collapse/Expand Capability

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#507]
### QA Toolkit:
**Missing +/- Collapse Button - panel does not collapse**
![image](https://user-images.githubusercontent.com/4098544/69176107-1b436400-0ad3-11ea-9d0d-6e7c34e0e283.png)

### MDE Toolkit:
**+/- Collapse Button Appears - however panel does not collapse**
![image](https://user-images.githubusercontent.com/4098544/69176134-2ac2ad00-0ad3-11ea-97b4-a338a2df77fd.png)

### IEM Toolkit:
**+/- Collapse Button Appears incorrectly - panel does not collapse**
![image](https://user-images.githubusercontent.com/4098544/69176499-d0761c00-0ad3-11ea-9e83-294b0e86c2d2.png)

**Comment by vijme** [comment]
@slmessier, can you try clearing your browser cache and try again

**Comment by slmessier** [comment]
@vijme I can confirm this issue does consistently occur for all collapsible panels in the UI exclusively when testing on IE 11 browser platform (version below).

**Collapse/Expand functionality functions successfully, as expected using Chrome, Firefox, MS Edge.**
![image](https://user-images.githubusercontent.com/4098544/69182286-b1c95280-0ade-11ea-9524-b1bb09fec839.png)

**Comment by vijme** [comment]
Issue fixed and ready for testing. Interesting issue. Issue seems to be because of console.log function, where console is not ready in IE till we open it deliberately.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated for IEM, MDE, and QA Toolkits.
