### ISSUE TITLE
MDE Toolkit - EPD Any Status and Raw Data Report Error

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#509]
_Test results that were initiated on 11/20/2019_

The following (2) report errors occurred when attempting to print:

### 1. EPD Any Status Report - PDF and Spreadsheet formats
a. From the reviews tab, click Print.
b. Next, click EPD any status
c. The system displays an unrecoverable error message.

### 2. RAW Data Report - PDF and Spreadsheet formats
a. From the reviews tab, click Print.
b. Next, click Raw Data
c. The system displays an unrecoverable error message.

**Comment by vijme** [comment]
Issues fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team.

**Comment by HollySchuelerKCI** [comment]
@vijme While performing the testplan, I noticed the MDE Workload Report now returns an error.

**Comment by vijme** [comment]
@HollySchuelerKCI , Can you provide screenshot. Both of them works fine from my end.

**Comment by HollySchuelerKCI** [comment]
Update: Per developer, after performing a browser refresh, the errors for the above reports has been resolved.

Will continue to monitor should this issue arise again.
