### ISSUE TITLE
MDE Toolkit - Add New Comment Log

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#510]
_Test results that were initiated on 11/20/2019_

An unrecoverable error has occurred when the user adds a new comment log to a review.

### Steps To Replicate:
1. Click Edit button from the Reviews Tab
2. Scroll down and click Comment log
![image](https://user-images.githubusercontent.com/25441512/69268464-2f539800-0b9d-11ea-8959-a03fe44ecc5e.png)
3. Add required information to the comment log
![image](https://user-images.githubusercontent.com/25441512/69268532-50b48400-0b9d-11ea-9fbf-7737d95f2feb.png)

4. Click update
5. The system displays unrecoverable error message

**Comment by vijme** [comment]
Oracle update error. Issue fixed in dev. Will be available for testing tomorrow

**Comment by vijme** [comment]
Ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team.
