### ISSUE TITLE
QA Toolkit - Reporting Menu - Add New Skipped Inspection - Fails to Save

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#512]
### The QA Toolkit does not properly save entered "Skipped Inspection" information (see animated graphic below).

**Note: this issue exists in STAGING as well** @vijme @AndyWuKCI 

The system allows the user to complete the workflow, however **when the user clicks Save the system begins processing and never issues a response.**
![AddSkippedInspection_20191125](https://user-images.githubusercontent.com/4098544/69576205-d4a1ae00-0f99-11ea-9b94-f409ee6c9c2e.gif)

**Comment by vijme** [comment]
This issue is fixed and ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team.

**Comment by slmessier** [comment]
@vijme this issue is a precursor to #519
