### ISSUE TITLE
QA Toolkit - Reporting Menu - Edit Existing Non-Compliance - Application Error

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#513]
### The QA Toolkit does not properly display the (Reporting Menu) Edit Compliance Details page, the application errors out (see graphic below).

**When the user clicks to edit an existing Non-Compliance Record, the system produces an application error.**

![EditNonCompliance_20191125](https://user-images.githubusercontent.com/4098544/69577727-f9e3eb80-0f9c-11ea-8e1d-6b1893915f7b.gif)

**Comment by vijme** [comment]
Issue related to oracle upgrade. Fixed in dev

**Comment by vijme** [comment]
This issue is ready for testing

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully tested by the project team.
