### ISSUE TITLE
QA Toolkit - Projects - Remove / Hide "Team Index" & "Centroid" user input fields

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#56]
Remove (hide) “team Index” and “Centriod” from project details.

![image](https://cloud.githubusercontent.com/assets/4098544/3513798/4b0818be-06c6-11e4-964b-2a9ec5b9dc98.png)

**Comment by Tad-Daniel** [comment]
Close issue as it no longer is necessary
