### ISSUE TITLE
QA Toolkit - Projects - Milestones Subtab - Date Fields

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#59]
Calendar field not working correctly in project milestones.

Steps to Replicate:
1. Projects Tab --> Milestones Subtab --> Add New Milestone
2. Use the Calendar button to type in a Date
3. The system does not accept the input from the Calendar selector popout.

![image](https://cloud.githubusercontent.com/assets/4098544/3514079/f20eee92-06c8-11e4-86b6-f6614e98a920.png)

**Comment by slmessier** [comment]
This issue is identical to issue #270 . Development of a solution will be monitored and tracked within that issue. This issue will be closed.

**Comment by vijme** [comment]
SInce this has additional information, closing issue 270 and reopening this

**Comment by Tad-Daniel** [comment]
This issue is now complete and working correctly in production.
