### ISSUE TITLE
QA Toolkit - Inspections - Search Panel Functionality - Add new Fields: "Non-Compliance" & "Project Description"

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#60]
Add to Inspections list search panel:
1. "Non-compliance” with associated checkbox.
2. “Project Description” with associated text user input field.

![image](https://cloud.githubusercontent.com/assets/4098544/3514255/936ef772-06ca-11e4-9fea-825009a494f0.png)

**Comment by Tad-Daniel** [comment]
This has been done and put into production.
