### ISSUE TITLE
QA Toolkit - Merge Projects - Relocate Launch Point to Within Admin Menu

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#62]
k.  Should “Merge Projects” be somewhere else? (Data Cleanup menu)

(Update the system so that the Merge Projects function is accessed exclusively from within the ADMIN menu - assuming only by authorized users with administrator permissions)

![image](https://cloud.githubusercontent.com/assets/4098544/3514501/88f99516-06cc-11e4-8d5a-d1d46cc9418c.png)
(currently accessed via Projects tab)

**Comment by Tad-Daniel** [comment]
This enhancement will be addressed under task 15. issue closed
