### ISSUE TITLE
QA Toolkit - Design & Develop Non-Compliance Tracking System Enhancements

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#64]
Enhancement request from SHA. Full scope of enhancement is unclear at the current time. Additional background explanation from SHA is requested by KCI, as noted within the questions below.
# Request from SHA

![image](https://cloud.githubusercontent.com/assets/4098544/3525323/f1e7eafa-0771-11e4-8a5e-fb622a62f73e.png)
1. Non-Compliance Tracking System. 
   1. N.G.  Reports count as Non-Compliance as check box reflects in report. (monthly summaries)
   2. Add search field for NG/NC.  (checkbox to include NG NC)
## Questions for SHA:
1. What is represented by the abbreviation N. G. in no.1 above? No-Grade?
2. Is the general request of no.1 above to update the system to process No-grade inspections as it does currently for non-compliance inspections, including the automated system notifications? Generally, please provide clear, descriptive information on the nature of this request, without abbreviating words or ideas.
3. In regard to no.2 above, to which screen would the new search checkbox for NG/NC be added - Inspections? Can you confirm that the associated functionality of the activated checkbox would be for the system to display only those inspections with either No-Grade OR were found Non-Compliant?

**Comment by Tad-Daniel** [comment]
This item has been addressed in other enhancements.  Issue closed
