### ISSUE TITLE
QA Toolkit - Design & Develop Automated Incentive Enhancements

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#66]
Enhancement request from SHA. Full scope of enhancement is unclear at the current time. Additional background explanation from SHA is requested by KCI, as noted within the questions below.
# Request from SHA

![image](https://cloud.githubusercontent.com/assets/4098544/3525869/3d9b3a24-0777-11e4-85ef-be1c79afb6fc.png)
1. Implement way for specific user to add incentives. 
2. System should calculate grade based on dates and QA reports. This system could be mostly automatic based on NTP dates. 
3. Print a report related to incentive tracking system
## Questions for SHA:
1. In regard to no.1 above, authorized Users currently have the capability to add QA incentives using the Projects Tab-->QA Incentives Subtab. Please describe how the requested enhanced functionality would differ from this capability that already exists currently.
2. In regard to no.2 above, The system currently automatically determines the grade for a particular inspection based on the survey questions that are answered by Inspectors. Please describe how the requested enhanced functionality would differ from this capability that already exists currently. In particular, what entity receives the grade in the enhanced scenario? Our current understanding is that Grades are only generated within daily inspections and then attached to a project. Is the enhanced request to produce a grade value for the project using logic that considers all associated inspections (using the average or most-recent value)? Please elaborate on this thought without abbreviating words or ideas.
3. In regard to no. 3 above, what attribute information is displayed within the conceptual report? We're very unclear what is intended by the term "incentive tracking system" - please provide a much more detailed explanation of all aspects of the conceptual "incentive tracking system" (what information is displayed? what functions are available?) .

**Comment by Tad-Daniel** [comment]
1.In regard to no.1 above, authorized Users currently have the capability to add QA incentives using the Projects Tab-->QA Incentives Subtab. Please describe how the requested enhanced functionality would differ from this capability that already exists currently.

**- The goal is to automate the documenting/tracking of incentive and LD's based on the NTP date.  I would like the option added to have the system automatically track this information base on the specification while retaining the ability of the user to add in specific dates as it currently works.
The current specs reads;
"Incentive Payments.  When specified in the Contract Documents, the Administration may include incentive payments to the Contractor. Starting at the Notice to Proceed, an Incentive Payment will be made for a rating quarter consisting of 3 months when; at least four inspections were performed by the Quality Assurance Inspector and an average score equal to or greater than 85 for the entire rating quarter is received.  The quarterly incentive payment will be made within 60 days after the end of the rating quarter. No incentive will be paid for partial quarters or for quarters with less than four inspections.  No incentives will be paid for any quarter in which a 'D' or 'F' rating is received.  When a project receives no 'D' or ‘F’ ratings and the overall average score is equal to or greater than 85, the final incentive payment will be made at final project closeout. If a time extension is granted, additional quarterly incentive payments will be drawn from the final incentive payment. 
Liquidated Damages. Whenever a project is rated 'D' or 'F', the Administration will assess Liquidated Damages. Liquidated Damages shall be paid within 30 days from the date of notification to the Contractor. Payments will not be allowed to accrue for consideration at final project closeout. "**

2.In regard to no.2 above, The system currently automatically determines the grade for a particular inspection based on the survey questions that are answered by Inspectors. Please describe how the requested enhanced functionality would differ from this capability that already exists currently. In particular, what entity receives the grade in the enhanced scenario? Our current understanding is that Grades are only generated within daily inspections and then attached to a project. Is the enhanced request to produce a grade value for the project using logic that considers all associated inspections (using the average or most-recent value)? Please elaborate on this thought without abbreviating words or ideas.

**- Look to the answer above; This comment is about the system calculating average grades between set dates.  This is answered in the answer to question 1.**

3.In regard to no. 3 above, what attribute information is displayed within the conceptual report? We're very unclear what is intended by the term "incentive tracking system" - please provide a much more detailed explanation of all aspects of the conceptual "incentive tracking system" (what information is displayed? what functions are available?) .

**- will provide concept as a PDF.**

**Comment by Tad-Daniel** [comment]
This has been completed and implemented in production.
